// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"reflect"
	"strconv"
	"strings"
	"time"
)

// ClientConfig configures a generated API client.
type ClientConfig struct {
	BaseURL      string
	APIKey       string
	APIKeyHeader string
	APIKeyPrefix string
	HTTPClient   *http.Client
	// Retry configures safe automatic retries. Nil uses Kaji defaults; set
	// MaxAttempts to 1 to disable retries.
	Retry        *RetryConfig
	// Hooks observes the final lifecycle of a logical request. It receives no
	// request headers or bodies, so credentials stay private by default.
	Hooks        KajiClientHooks
}

// Client is safe for concurrent use after construction.
type Client struct {
	baseURL      string
	apiKey       string
	apiKeyHeader string
	apiKeyPrefix string
	httpClient   *http.Client
	retry        retryConfig
	hooks        KajiClientHooks
	AuthCheckResource *AuthCheckResourceService
	Contacts *ContactsService
	Crm *CrmService
	Domains *DomainsService
	Events *EventsService
	Inbound *InboundService
	Segments *SegmentsService
	SenderIdentities *SenderIdentitiesService
	Sends *SendsService
	Webhooks *WebhooksService
}

// NewClient builds a client from explicit configuration. BaseURL is required.
func NewClient(config ClientConfig) (*Client, error) {
	baseURL := strings.TrimRight(config.BaseURL, "/")
	if baseURL == "" {
		return nil, fmt.Errorf("kaji: BaseURL is required")
	}
	header := config.APIKeyHeader
	if header == "" {
		header = "Authorization"
	}
	httpClient := config.HTTPClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	client := &Client{baseURL: baseURL, apiKey: config.APIKey, apiKeyHeader: header, apiKeyPrefix: config.APIKeyPrefix, httpClient: httpClient, retry: normalizeRetry(config.Retry), hooks: config.Hooks}
	client.AuthCheckResource = &AuthCheckResourceService{client: client}
	client.Contacts = &ContactsService{client: client}
	client.Crm = &CrmService{client: client}
	client.Domains = &DomainsService{client: client}
	client.Events = &EventsService{client: client}
	client.Inbound = &InboundService{client: client}
	client.Segments = &SegmentsService{client: client}
	client.SenderIdentities = &SenderIdentitiesService{client: client}
	client.Sends = &SendsService{client: client}
	client.Webhooks = &WebhooksService{client: client}
	return client, nil
}

// kajiAPIError describes a non-success HTTP response.
type kajiAPIError struct {
	StatusCode int
	Body        []byte
	ContentType string
}

func (errorResponse *kajiAPIError) Error() string {
	return fmt.Sprintf("kaji: API request failed with status %d: %s", errorResponse.StatusCode, string(errorResponse.Body))
}

func (client *Client) newRequest(ctx context.Context, method, path string, query url.Values, headers http.Header, body any) (*http.Request, error) {
	endpoint := client.baseURL + path
	if len(query) > 0 { endpoint += "?" + query.Encode() }
	return client.newRequestURL(ctx, method, endpoint, headers, body)
}

// newPaginationRequest is private on purpose: a generated pager may follow
// only a same-origin URL supplied by its declared response contract. It still
// uses the normal request builder, so auth, caller headers, and body encoding
// cannot be bypassed by a continuation link.
func (client *Client) newPaginationRequest(ctx context.Context, method, continuation string, headers http.Header, body any) (*http.Request, error) {
	base, err := url.Parse(client.baseURL)
	if err != nil { return nil, fmt.Errorf("kaji: parse BaseURL: %w", err) }
	next, err := url.Parse(continuation)
	if err != nil { return nil, fmt.Errorf("kaji: parse pagination URL: %w", err) }
	endpoint := base.ResolveReference(next)
	if endpoint.Scheme != base.Scheme || endpoint.Host != base.Host {
		return nil, fmt.Errorf("kaji: pagination URL must remain on the configured API origin")
	}
	return client.newRequestURL(ctx, method, endpoint.String(), headers, body)
}

func (client *Client) newRequestURL(ctx context.Context, method, endpoint string, headers http.Header, body any) (*http.Request, error) {
	var reader io.Reader
	if body != nil {
		encoded, err := json.Marshal(body)
		if err != nil {
			return nil, fmt.Errorf("kaji: encode request body: %w", err)
		}
		reader = bytes.NewReader(encoded)
	}
	request, err := http.NewRequestWithContext(ctx, method, endpoint, reader)
	if err != nil {
		return nil, fmt.Errorf("kaji: build request: %w", err)
	}
	request.Header.Set("Accept", "application/json")
	if body != nil {
		request.Header.Set("Content-Type", "application/json")
	}
	for name, values := range headers {
		for _, value := range values {
			request.Header.Add(name, value)
		}
	}
	if client.apiKey != "" {
		credential := client.apiKey
		if client.apiKeyPrefix != "" {
			credential = client.apiKeyPrefix + " " + credential
		}
		request.Header.Set(client.apiKeyHeader, credential)
	}
	return request, nil
}

func (client *Client) do(request *http.Request, destination any) error {
	response, err := client.httpClient.Do(request)
	if err != nil {
		return fmt.Errorf("kaji: execute request: %w", err)
	}
	defer response.Body.Close()
	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		body, _ := io.ReadAll(io.LimitReader(response.Body, 1<<20))
		return &kajiAPIError{StatusCode: response.StatusCode, Body: body, ContentType: response.Header.Get("Content-Type")}
	}
	if destination == nil || response.StatusCode == http.StatusNoContent {
		return nil
	}
	if err := json.NewDecoder(response.Body).Decode(destination); err != nil && err != io.EOF {
		return fmt.Errorf("kaji: decode response: %w", err)
	}
	return nil
}

func addQuery(query url.Values, name string, value any) error {
	if value == nil {
		return nil
	}
	reflected := reflect.ValueOf(value)
	if reflected.Kind() == reflect.Pointer {
		if reflected.IsNil() {
			return nil
		}
		return addQuery(query, name, reflected.Elem().Interface())
	}
	if reflected.Kind() == reflect.Slice || reflected.Kind() == reflect.Array {
		for index := 0; index < reflected.Len(); index++ {
			if err := addQuery(query, name, reflected.Index(index).Interface()); err != nil {
				return err
			}
		}
		return nil
	}
	switch value.(type) {
	case string, bool, int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, float32, float64:
		query.Add(name, fmt.Sprint(value))
		return nil
	default:
		encoded, err := json.Marshal(value)
		if err != nil {
			return fmt.Errorf("kaji: encode query %s: %w", name, err)
		}
		query.Add(name, string(encoded))
		return nil
	}

}


// RetryConfig controls safe retries performed by the generated client.
// A nil ClientConfig.Retry uses three attempts, a 250ms initial delay, and an
// 8s maximum delay. Set MaxAttempts to 1 to make requests single-attempt.
type RetryConfig struct {
	MaxAttempts  int
	InitialDelay time.Duration
	MaxDelay     time.Duration
}

// KajiRequestInfo is safe request metadata for lifecycle hooks. Request
// headers and bodies are deliberately omitted so observability integrations do
// not accidentally receive credentials or customer data.
type KajiRequestInfo struct {
	Method string
	URL    string
}

// KajiResponseInfo describes the final HTTP response observed by a request.
// Intermediate retry responses are intentionally not reported.
type KajiResponseInfo struct {
	Request    KajiRequestInfo
	StatusCode int
	Headers    http.Header
}

// KajiClientHooks receives lifecycle events for one logical generated SDK
// request. BeforeRequest, AfterResponse, and OnError run at most once each;
// retries remain an implementation detail of the transport.
type KajiClientHooks interface {
	BeforeRequest(KajiRequestInfo)
	AfterResponse(KajiResponseInfo)
	OnError(KajiRequestInfo, error)
}

func (client *Client) beforeRequest(request KajiRequestInfo) {
	if client.hooks != nil {
		client.hooks.BeforeRequest(request)
	}
}

func (client *Client) afterResponse(request KajiRequestInfo, response *http.Response) {
	if client.hooks != nil {
		client.hooks.AfterResponse(KajiResponseInfo{Request: request, StatusCode: response.StatusCode, Headers: response.Header.Clone()})
	}
}

func (client *Client) onError(request KajiRequestInfo, err error) {
	if client.hooks != nil {
		client.hooks.OnError(request, err)
	}
}

type retryConfig struct {
	maxAttempts  int
	initialDelay time.Duration
	maxDelay     time.Duration
}

func normalizeRetry(config *RetryConfig) retryConfig {
	result := retryConfig{maxAttempts: 3, initialDelay: 250 * time.Millisecond, maxDelay: 8 * time.Second}
	if config == nil {
		return result
	}
	if config.MaxAttempts > 0 {
		result.maxAttempts = config.MaxAttempts
	}
	if config.InitialDelay > 0 {
		result.initialDelay = config.InitialDelay
	}
	if config.MaxDelay > 0 {
		result.maxDelay = config.MaxDelay
	}
	if result.maxDelay < result.initialDelay {
		result.maxDelay = result.initialDelay
	}
	return result
}

func canRetry(request *http.Request) bool {
	switch request.Method {
	case http.MethodGet, http.MethodPut, http.MethodPatch, http.MethodDelete:
		return true
	case http.MethodPost:
		return request.Header.Get("Idempotency-Key") != ""
	default:
		return false
	}
}

func isRetryableStatus(status int) bool {
	switch status {
	case http.StatusRequestTimeout, http.StatusTooManyRequests, http.StatusInternalServerError,
		http.StatusBadGateway, http.StatusServiceUnavailable, http.StatusGatewayTimeout:
		return true
	default:
		return false
	}
}

func (config retryConfig) delay(response *http.Response, attempt int) time.Duration {
	if response != nil {
		if retryAfter, ok := parseRetryAfter(response.Header.Get("Retry-After")); ok {
			return retryAfter
		}
	}
	delay := config.initialDelay
	for retry := 1; retry < attempt && delay < config.maxDelay; retry++ {
		if delay > config.maxDelay/2 {
			return config.maxDelay
		}
		delay *= 2
	}
	return delay
}

func parseRetryAfter(value string) (time.Duration, bool) {
	if seconds, err := strconv.Atoi(strings.TrimSpace(value)); err == nil && seconds >= 0 {
		return time.Duration(seconds) * time.Second, true
	}
	if when, err := http.ParseTime(value); err == nil {
		if delay := time.Until(when); delay > 0 {
			return delay, true
		}
	}
	return 0, false
}

func waitForRetry(ctx context.Context, delay time.Duration) error {
	timer := time.NewTimer(delay)
	defer timer.Stop()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-timer.C:
		return nil
	}
}

func replayRequest(request *http.Request) (*http.Request, error) {
	retry := request.Clone(request.Context())
	if request.GetBody == nil {
		if request.Body == nil || request.Body == http.NoBody {
			return retry, nil
		}
		return nil, fmt.Errorf("kaji: cannot retry a request whose body cannot be replayed")
	}
	body, err := request.GetBody()
	if err != nil {
		return nil, fmt.Errorf("kaji: replay request body: %w", err)
	}
	retry.Body = body
	return retry, nil
}

func (client *Client) doWithRetry(request *http.Request, destination any) error {
	retryAllowed := canRetry(request)
	requestInfo := KajiRequestInfo{Method: request.Method, URL: request.URL.String()}
	client.beforeRequest(requestInfo)
	for attempt := 1; ; attempt++ {
		response, err := client.httpClient.Do(request)
		if err != nil {
			if !retryAllowed || attempt >= client.retry.maxAttempts || request.Context().Err() != nil {
				result := fmt.Errorf("kaji: execute request: %w", err)
				client.onError(requestInfo, result)
				return result
			}
			if err := waitForRetry(request.Context(), client.retry.delay(nil, attempt)); err != nil {
				result := fmt.Errorf("kaji: execute request: %w", err)
				client.onError(requestInfo, result)
				return result
			}
			request, err = replayRequest(request)
			if err != nil {
				client.onError(requestInfo, err)
				return err
			}
			continue
		}

		if response.StatusCode >= http.StatusOK && response.StatusCode < http.StatusMultipleChoices {
			defer response.Body.Close()
			client.afterResponse(requestInfo, response)
			if destination == nil || response.StatusCode == http.StatusNoContent {
				return nil
			}
			if bytesDestination, ok := destination.(*[]byte); ok {
				body, err := io.ReadAll(response.Body)
				if err != nil { result := fmt.Errorf("kaji: read binary response: %w", err); client.onError(requestInfo, result); return result }
				*bytesDestination = body
				return nil
			}
			if textDestination, ok := destination.(*string); ok {
				body, err := io.ReadAll(response.Body)
				if err != nil { result := fmt.Errorf("kaji: read text response: %w", err); client.onError(requestInfo, result); return result }
				*textDestination = string(body)
				return nil
			}
			if err := json.NewDecoder(response.Body).Decode(destination); err != nil && err != io.EOF {
				result := fmt.Errorf("kaji: decode response: %w", err)
				client.onError(requestInfo, result)
				return result
			}
			return nil
		}

		if retryAllowed && isRetryableStatus(response.StatusCode) && attempt < client.retry.maxAttempts {
			delay := client.retry.delay(response, attempt)
			response.Body.Close()
			if err := waitForRetry(request.Context(), delay); err != nil {
				return fmt.Errorf("kaji: execute request: %w", err)
			}
			request, err = replayRequest(request)
			if err != nil {
				return err
			}
			continue
		}

		body, _ := io.ReadAll(io.LimitReader(response.Body, 1<<20))
		client.afterResponse(requestInfo, response)
		response.Body.Close()
		result := &kajiAPIError{StatusCode: response.StatusCode, Body: body, ContentType: response.Header.Get("Content-Type")}
		client.onError(requestInfo, result)
		return result
	}
}

// stream returns an open Server-Sent Events response body. Callers must close it.
// It uses the same retry policy before the stream is established; once bytes are
// flowing, reconnect policy belongs to the consuming application.
func (client *Client) stream(request *http.Request) (io.ReadCloser, error) {
	retryAllowed := canRetry(request)
	requestInfo := KajiRequestInfo{Method: request.Method, URL: request.URL.String()}
	client.beforeRequest(requestInfo)
	for attempt := 1; ; attempt++ {
		response, err := client.httpClient.Do(request)
		if err != nil {
			if !retryAllowed || attempt >= client.retry.maxAttempts || request.Context().Err() != nil {
				result := fmt.Errorf("kaji: execute request: %w", err)
				client.onError(requestInfo, result)
				return nil, result
			}
			if err := waitForRetry(request.Context(), client.retry.delay(nil, attempt)); err != nil {
				result := fmt.Errorf("kaji: execute request: %w", err)
				client.onError(requestInfo, result)
				return nil, result
			}
			request, err = replayRequest(request)
			if err != nil { client.onError(requestInfo, err); return nil, err }
			continue
		}
		if response.StatusCode >= http.StatusOK && response.StatusCode < http.StatusMultipleChoices {
			client.afterResponse(requestInfo, response)
			return response.Body, nil
		}
		if retryAllowed && isRetryableStatus(response.StatusCode) && attempt < client.retry.maxAttempts {
			delay := client.retry.delay(response, attempt)
			response.Body.Close()
			if err := waitForRetry(request.Context(), delay); err != nil {
				result := fmt.Errorf("kaji: execute request: %w", err)
				client.onError(requestInfo, result)
				return nil, result
			}
			request, err = replayRequest(request)
			if err != nil { client.onError(requestInfo, err); return nil, err }
			continue
		}
		body, _ := io.ReadAll(io.LimitReader(response.Body, 1<<20))
		client.afterResponse(requestInfo, response)
		response.Body.Close()
		result := &kajiAPIError{StatusCode: response.StatusCode, Body: body, ContentType: response.Header.Get("Content-Type")}
		client.onError(requestInfo, result)
		return nil, result
	}
}
