// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

type EventResponse struct {
	APIVersion string `json:"api_version"`
	EventID string `json:"event_id"`
	ReceivedAt string `json:"received_at"`
	Replayed bool `json:"replayed"`
}
