// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

type CrmCreateListEntry struct {
	RecordID string `json:"record_id"`
	Values *map[string]any `json:"values,omitempty"`
}
