// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

type CrmListEntriesPage struct {
	APIVersion string `json:"api_version"`
	Data []CrmListEntry `json:"data"`
	Page map[string]any `json:"page"`
}
