// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

type CrmAttributeDiscovery struct {
	CurrencyCode *string `json:"currency_code,omitempty"`
	Expression *string `json:"expression,omitempty"`
	ID string `json:"id"`
	IsSystem *bool `json:"is_system,omitempty"`
	Key string `json:"key"`
	Multiple bool `json:"multiple"`
	Name string `json:"name"`
	Options []string `json:"options"`
	ReadOnly bool `json:"read_only"`
	Required bool `json:"required"`
	TargetObjectID *string `json:"target_object_id,omitempty"`
	Type string `json:"type"`
}
