// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

type CrmRecord struct {
	ArchivedAt *string `json:"archived_at,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	DisplayName string `json:"display_name"`
	ExternalID *string `json:"external_id,omitempty"`
	ID string `json:"id"`
	ObjectID string `json:"object_id"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	Values map[string]any `json:"values"`
}
