// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

type ContactQueryResponse struct {
	APIVersion string `json:"api_version"`
	Data []Contact `json:"data"`
	Page Page `json:"page"`
}
