// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"encoding/json"
)

type CrmNoteWrite struct {
	Body *string `json:"body,omitempty"`
	Content *json.RawMessage `json:"content,omitempty"`
	Mentions *[]CrmNoteMention `json:"mentions,omitempty"`
	Title *string `json:"title,omitempty"`
}
