// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

type CrmCreateList struct {
	Description *string `json:"description,omitempty"`
	Name string `json:"name"`
	ObjectID string `json:"object_id"`
}
