// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

type Page struct {
	Limit int64 `json:"limit"`
	NextOffset *int64 `json:"next_offset,omitempty"`
	Offset int64 `json:"offset"`
}
