// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

type CrmObjectDeletionPreviewData struct {
	BlockingRelationships []map[string]any `json:"blocking_relationships"`
	ListCount int64 `json:"list_count"`
	Object CrmMetadataObject `json:"object"`
	RecordCount int64 `json:"record_count"`
}
