// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

type SenderIdentityListResponse struct {
	APIVersion string `json:"api_version"`
	Data []SenderIdentity `json:"data"`
}
