// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

type HookUpdate struct {
	EventTypes *[]string `json:"event_types,omitempty"`
	Status *string `json:"status,omitempty"`
	URL *string `json:"url,omitempty"`
}
