// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

type CrmMetadataAttribute struct {
	CreatedAt *string `json:"created_at,omitempty"`
	CurrencyCode *string `json:"currency_code,omitempty"`
	Expression *string `json:"expression,omitempty"`
	ID string `json:"id"`
	IsSystem bool `json:"is_system"`
	Key string `json:"key"`
	ListID *string `json:"list_id,omitempty"`
	Multiple bool `json:"multiple"`
	Name string `json:"name"`
	ObjectID *string `json:"object_id,omitempty"`
	Options []string `json:"options"`
	OrganizationID *string `json:"organization_id,omitempty"`
	Required bool `json:"required"`
	TargetObjectID *string `json:"target_object_id,omitempty"`
	Type string `json:"type"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}
