// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// CreateCrmListAttributeRequest contains the inputs for CreateCrmListAttribute.
type CreateCrmListAttributeRequest struct {
	List string `json:"list,omitempty"`
	Body CrmAttributeCreate `json:"body,omitempty"`
}

// CreateCrmListAttributeError400 is returned when CreateCrmListAttribute responds with status 400.
type CreateCrmListAttributeError400 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmListAttributeError400) Error() string {
	return fmt.Sprintf("kaji: CreateCrmListAttribute failed with status %d", errorResponse.StatusCode)
}

// CreateCrmListAttributeError401 is returned when CreateCrmListAttribute responds with status 401.
type CreateCrmListAttributeError401 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmListAttributeError401) Error() string {
	return fmt.Sprintf("kaji: CreateCrmListAttribute failed with status %d", errorResponse.StatusCode)
}

// CreateCrmListAttributeError403 is returned when CreateCrmListAttribute responds with status 403.
type CreateCrmListAttributeError403 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmListAttributeError403) Error() string {
	return fmt.Sprintf("kaji: CreateCrmListAttribute failed with status %d", errorResponse.StatusCode)
}

// CreateCrmListAttributeError404 is returned when CreateCrmListAttribute responds with status 404.
type CreateCrmListAttributeError404 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmListAttributeError404) Error() string {
	return fmt.Sprintf("kaji: CreateCrmListAttribute failed with status %d", errorResponse.StatusCode)
}

// CreateCrmListAttributeError409 is returned when CreateCrmListAttribute responds with status 409.
type CreateCrmListAttributeError409 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmListAttributeError409) Error() string {
	return fmt.Sprintf("kaji: CreateCrmListAttribute failed with status %d", errorResponse.StatusCode)
}

// CreateCrmListAttributeError413 is returned when CreateCrmListAttribute responds with status 413.
type CreateCrmListAttributeError413 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmListAttributeError413) Error() string {
	return fmt.Sprintf("kaji: CreateCrmListAttribute failed with status %d", errorResponse.StatusCode)
}

// CreateCrmListAttributeError415 is returned when CreateCrmListAttribute responds with status 415.
type CreateCrmListAttributeError415 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmListAttributeError415) Error() string {
	return fmt.Sprintf("kaji: CreateCrmListAttribute failed with status %d", errorResponse.StatusCode)
}

// CreateCrmListAttributeError503 is returned when CreateCrmListAttribute responds with status 503.
type CreateCrmListAttributeError503 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmListAttributeError503) Error() string {
	return fmt.Sprintf("kaji: CreateCrmListAttribute failed with status %d", errorResponse.StatusCode)
}

func decodeCreateCrmListAttributeError(requestError error) error {
	var transportError *kajiAPIError
	if !errors.As(requestError, &transportError) { return requestError }
	switch transportError.StatusCode {
	case 400:
		result := &CreateCrmListAttributeError400{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 401:
		result := &CreateCrmListAttributeError401{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 403:
		result := &CreateCrmListAttributeError403{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 404:
		result := &CreateCrmListAttributeError404{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 409:
		result := &CreateCrmListAttributeError409{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 413:
		result := &CreateCrmListAttributeError413{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 415:
		result := &CreateCrmListAttributeError415{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 503:
		result := &CreateCrmListAttributeError503{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	default:
		return requestError
	}
}

// CreateCrmListAttribute invokes POST /v1/crm/lists/{list}/attributes.
func (client *Client) CreateCrmListAttribute(ctx context.Context, input *CreateCrmListAttributeRequest) (*CrmMetadataAttributeResponse, error) {
	if input == nil {
		input = &CreateCrmListAttributeRequest{}
	}
	path := "/v1/crm/lists/{list}/attributes"
	query := url.Values{}
	headers := http.Header{}
	path = strings.ReplaceAll(path, "{list}", url.PathEscape(fmt.Sprint(input.List)))
	body := input.Body
	request, err := client.newRequest(ctx, "POST", path, query, headers, body)
	if err != nil {
		return nil, decodeCreateCrmListAttributeError(err)
	}
	var response CrmMetadataAttributeResponse
	if err := client.doWithRetry(request, &response); err != nil {
		return nil, decodeCreateCrmListAttributeError(err)
	}
	return &response, nil
}

