// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// GetCrmNoteRequest contains the inputs for GetCrmNote.
type GetCrmNoteRequest struct {
	NoteID string `json:"note_id,omitempty"`
}

// GetCrmNoteError400 is returned when GetCrmNote responds with status 400.
type GetCrmNoteError400 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmNoteError400) Error() string {
	return fmt.Sprintf("kaji: GetCrmNote failed with status %d", errorResponse.StatusCode)
}

// GetCrmNoteError401 is returned when GetCrmNote responds with status 401.
type GetCrmNoteError401 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmNoteError401) Error() string {
	return fmt.Sprintf("kaji: GetCrmNote failed with status %d", errorResponse.StatusCode)
}

// GetCrmNoteError403 is returned when GetCrmNote responds with status 403.
type GetCrmNoteError403 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmNoteError403) Error() string {
	return fmt.Sprintf("kaji: GetCrmNote failed with status %d", errorResponse.StatusCode)
}

// GetCrmNoteError404 is returned when GetCrmNote responds with status 404.
type GetCrmNoteError404 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmNoteError404) Error() string {
	return fmt.Sprintf("kaji: GetCrmNote failed with status %d", errorResponse.StatusCode)
}

// GetCrmNoteError409 is returned when GetCrmNote responds with status 409.
type GetCrmNoteError409 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmNoteError409) Error() string {
	return fmt.Sprintf("kaji: GetCrmNote failed with status %d", errorResponse.StatusCode)
}

// GetCrmNoteError413 is returned when GetCrmNote responds with status 413.
type GetCrmNoteError413 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmNoteError413) Error() string {
	return fmt.Sprintf("kaji: GetCrmNote failed with status %d", errorResponse.StatusCode)
}

// GetCrmNoteError415 is returned when GetCrmNote responds with status 415.
type GetCrmNoteError415 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmNoteError415) Error() string {
	return fmt.Sprintf("kaji: GetCrmNote failed with status %d", errorResponse.StatusCode)
}

// GetCrmNoteError503 is returned when GetCrmNote responds with status 503.
type GetCrmNoteError503 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmNoteError503) Error() string {
	return fmt.Sprintf("kaji: GetCrmNote failed with status %d", errorResponse.StatusCode)
}

func decodeGetCrmNoteError(requestError error) error {
	var transportError *kajiAPIError
	if !errors.As(requestError, &transportError) { return requestError }
	switch transportError.StatusCode {
	case 400:
		result := &GetCrmNoteError400{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 401:
		result := &GetCrmNoteError401{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 403:
		result := &GetCrmNoteError403{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 404:
		result := &GetCrmNoteError404{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 409:
		result := &GetCrmNoteError409{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 413:
		result := &GetCrmNoteError413{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 415:
		result := &GetCrmNoteError415{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 503:
		result := &GetCrmNoteError503{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	default:
		return requestError
	}
}

// GetCrmNote invokes GET /v1/crm/notes/{note_id}.
func (client *Client) GetCrmNote(ctx context.Context, input *GetCrmNoteRequest) (*map[string]any, error) {
	if input == nil {
		input = &GetCrmNoteRequest{}
	}
	path := "/v1/crm/notes/{note_id}"
	query := url.Values{}
	headers := http.Header{}
	path = strings.ReplaceAll(path, "{note_id}", url.PathEscape(fmt.Sprint(input.NoteID)))
	var body any
	request, err := client.newRequest(ctx, "GET", path, query, headers, body)
	if err != nil {
		return nil, decodeGetCrmNoteError(err)
	}
	var response map[string]any
	if err := client.doWithRetry(request, &response); err != nil {
		return nil, decodeGetCrmNoteError(err)
	}
	return &response, nil
}

