// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// CreateCrmObjectAttributeRequest contains the inputs for CreateCrmObjectAttribute.
type CreateCrmObjectAttributeRequest struct {
	Object string `json:"object,omitempty"`
	Body CrmAttributeCreate `json:"body,omitempty"`
}

// CreateCrmObjectAttributeError400 is returned when CreateCrmObjectAttribute responds with status 400.
type CreateCrmObjectAttributeError400 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmObjectAttributeError400) Error() string {
	return fmt.Sprintf("kaji: CreateCrmObjectAttribute failed with status %d", errorResponse.StatusCode)
}

// CreateCrmObjectAttributeError401 is returned when CreateCrmObjectAttribute responds with status 401.
type CreateCrmObjectAttributeError401 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmObjectAttributeError401) Error() string {
	return fmt.Sprintf("kaji: CreateCrmObjectAttribute failed with status %d", errorResponse.StatusCode)
}

// CreateCrmObjectAttributeError403 is returned when CreateCrmObjectAttribute responds with status 403.
type CreateCrmObjectAttributeError403 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmObjectAttributeError403) Error() string {
	return fmt.Sprintf("kaji: CreateCrmObjectAttribute failed with status %d", errorResponse.StatusCode)
}

// CreateCrmObjectAttributeError404 is returned when CreateCrmObjectAttribute responds with status 404.
type CreateCrmObjectAttributeError404 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmObjectAttributeError404) Error() string {
	return fmt.Sprintf("kaji: CreateCrmObjectAttribute failed with status %d", errorResponse.StatusCode)
}

// CreateCrmObjectAttributeError409 is returned when CreateCrmObjectAttribute responds with status 409.
type CreateCrmObjectAttributeError409 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmObjectAttributeError409) Error() string {
	return fmt.Sprintf("kaji: CreateCrmObjectAttribute failed with status %d", errorResponse.StatusCode)
}

// CreateCrmObjectAttributeError413 is returned when CreateCrmObjectAttribute responds with status 413.
type CreateCrmObjectAttributeError413 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmObjectAttributeError413) Error() string {
	return fmt.Sprintf("kaji: CreateCrmObjectAttribute failed with status %d", errorResponse.StatusCode)
}

// CreateCrmObjectAttributeError415 is returned when CreateCrmObjectAttribute responds with status 415.
type CreateCrmObjectAttributeError415 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmObjectAttributeError415) Error() string {
	return fmt.Sprintf("kaji: CreateCrmObjectAttribute failed with status %d", errorResponse.StatusCode)
}

// CreateCrmObjectAttributeError503 is returned when CreateCrmObjectAttribute responds with status 503.
type CreateCrmObjectAttributeError503 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmObjectAttributeError503) Error() string {
	return fmt.Sprintf("kaji: CreateCrmObjectAttribute failed with status %d", errorResponse.StatusCode)
}

func decodeCreateCrmObjectAttributeError(requestError error) error {
	var transportError *kajiAPIError
	if !errors.As(requestError, &transportError) { return requestError }
	switch transportError.StatusCode {
	case 400:
		result := &CreateCrmObjectAttributeError400{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 401:
		result := &CreateCrmObjectAttributeError401{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 403:
		result := &CreateCrmObjectAttributeError403{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 404:
		result := &CreateCrmObjectAttributeError404{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 409:
		result := &CreateCrmObjectAttributeError409{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 413:
		result := &CreateCrmObjectAttributeError413{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 415:
		result := &CreateCrmObjectAttributeError415{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 503:
		result := &CreateCrmObjectAttributeError503{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	default:
		return requestError
	}
}

// CreateCrmObjectAttribute invokes POST /v1/crm/objects/{object}/attributes.
func (client *Client) CreateCrmObjectAttribute(ctx context.Context, input *CreateCrmObjectAttributeRequest) (*CrmMetadataAttributeResponse, error) {
	if input == nil {
		input = &CreateCrmObjectAttributeRequest{}
	}
	path := "/v1/crm/objects/{object}/attributes"
	query := url.Values{}
	headers := http.Header{}
	path = strings.ReplaceAll(path, "{object}", url.PathEscape(fmt.Sprint(input.Object)))
	body := input.Body
	request, err := client.newRequest(ctx, "POST", path, query, headers, body)
	if err != nil {
		return nil, decodeCreateCrmObjectAttributeError(err)
	}
	var response CrmMetadataAttributeResponse
	if err := client.doWithRetry(request, &response); err != nil {
		return nil, decodeCreateCrmObjectAttributeError(err)
	}
	return &response, nil
}

