// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// ListCrmActivitiesRequest contains the inputs for ListCrmActivities.
type ListCrmActivitiesRequest struct {
	RecordID string `json:"record_id,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	After *string `json:"after,omitempty"`
}

// ListCrmActivitiesError400 is returned when ListCrmActivities responds with status 400.
type ListCrmActivitiesError400 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmActivitiesError400) Error() string {
	return fmt.Sprintf("kaji: ListCrmActivities failed with status %d", errorResponse.StatusCode)
}

// ListCrmActivitiesError401 is returned when ListCrmActivities responds with status 401.
type ListCrmActivitiesError401 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmActivitiesError401) Error() string {
	return fmt.Sprintf("kaji: ListCrmActivities failed with status %d", errorResponse.StatusCode)
}

// ListCrmActivitiesError403 is returned when ListCrmActivities responds with status 403.
type ListCrmActivitiesError403 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmActivitiesError403) Error() string {
	return fmt.Sprintf("kaji: ListCrmActivities failed with status %d", errorResponse.StatusCode)
}

// ListCrmActivitiesError404 is returned when ListCrmActivities responds with status 404.
type ListCrmActivitiesError404 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmActivitiesError404) Error() string {
	return fmt.Sprintf("kaji: ListCrmActivities failed with status %d", errorResponse.StatusCode)
}

// ListCrmActivitiesError409 is returned when ListCrmActivities responds with status 409.
type ListCrmActivitiesError409 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmActivitiesError409) Error() string {
	return fmt.Sprintf("kaji: ListCrmActivities failed with status %d", errorResponse.StatusCode)
}

// ListCrmActivitiesError413 is returned when ListCrmActivities responds with status 413.
type ListCrmActivitiesError413 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmActivitiesError413) Error() string {
	return fmt.Sprintf("kaji: ListCrmActivities failed with status %d", errorResponse.StatusCode)
}

// ListCrmActivitiesError415 is returned when ListCrmActivities responds with status 415.
type ListCrmActivitiesError415 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmActivitiesError415) Error() string {
	return fmt.Sprintf("kaji: ListCrmActivities failed with status %d", errorResponse.StatusCode)
}

// ListCrmActivitiesError503 is returned when ListCrmActivities responds with status 503.
type ListCrmActivitiesError503 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmActivitiesError503) Error() string {
	return fmt.Sprintf("kaji: ListCrmActivities failed with status %d", errorResponse.StatusCode)
}

func decodeListCrmActivitiesError(requestError error) error {
	var transportError *kajiAPIError
	if !errors.As(requestError, &transportError) { return requestError }
	switch transportError.StatusCode {
	case 400:
		result := &ListCrmActivitiesError400{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 401:
		result := &ListCrmActivitiesError401{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 403:
		result := &ListCrmActivitiesError403{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 404:
		result := &ListCrmActivitiesError404{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 409:
		result := &ListCrmActivitiesError409{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 413:
		result := &ListCrmActivitiesError413{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 415:
		result := &ListCrmActivitiesError415{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 503:
		result := &ListCrmActivitiesError503{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	default:
		return requestError
	}
}

// ListCrmActivities invokes GET /v1/crm/records/{record_id}/activities.
func (client *Client) ListCrmActivities(ctx context.Context, input *ListCrmActivitiesRequest) (*map[string]any, error) {
	if input == nil {
		input = &ListCrmActivitiesRequest{}
	}
	path := "/v1/crm/records/{record_id}/activities"
	query := url.Values{}
	headers := http.Header{}
	path = strings.ReplaceAll(path, "{record_id}", url.PathEscape(fmt.Sprint(input.RecordID)))
	if err := addQuery(query, "limit", input.Limit); err != nil {
		return nil, err
	}
	if err := addQuery(query, "after", input.After); err != nil {
		return nil, err
	}
	var body any
	request, err := client.newRequest(ctx, "GET", path, query, headers, body)
	if err != nil {
		return nil, decodeListCrmActivitiesError(err)
	}
	var response map[string]any
	if err := client.doWithRetry(request, &response); err != nil {
		return nil, decodeListCrmActivitiesError(err)
	}
	return &response, nil
}

