// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// UpdateContactRequest contains the inputs for UpdateContact.
type UpdateContactRequest struct {
	ID string `json:"id,omitempty"`
	Body UpdateContact `json:"body,omitempty"`
}

// UpdateContactError401 is returned when UpdateContact responds with status 401.
type UpdateContactError401 struct {
	StatusCode int
	RawBody    []byte
	Body       ErrorResponse
}

func (errorResponse *UpdateContactError401) Error() string {
	return fmt.Sprintf("kaji: UpdateContact failed with status %d", errorResponse.StatusCode)
}

// UpdateContactError404 is returned when UpdateContact responds with status 404.
type UpdateContactError404 struct {
	StatusCode int
	RawBody    []byte
	Body       ErrorResponse
}

func (errorResponse *UpdateContactError404) Error() string {
	return fmt.Sprintf("kaji: UpdateContact failed with status %d", errorResponse.StatusCode)
}

// UpdateContactError422 is returned when UpdateContact responds with status 422.
type UpdateContactError422 struct {
	StatusCode int
	RawBody    []byte
	Body       ErrorResponse
}

func (errorResponse *UpdateContactError422) Error() string {
	return fmt.Sprintf("kaji: UpdateContact failed with status %d", errorResponse.StatusCode)
}

// UpdateContactError503 is returned when UpdateContact responds with status 503.
type UpdateContactError503 struct {
	StatusCode int
	RawBody    []byte
	Body       ErrorResponse
}

func (errorResponse *UpdateContactError503) Error() string {
	return fmt.Sprintf("kaji: UpdateContact failed with status %d", errorResponse.StatusCode)
}

func decodeUpdateContactError(requestError error) error {
	var transportError *kajiAPIError
	if !errors.As(requestError, &transportError) { return requestError }
	switch transportError.StatusCode {
	case 401:
		result := &UpdateContactError401{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 404:
		result := &UpdateContactError404{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 422:
		result := &UpdateContactError422{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 503:
		result := &UpdateContactError503{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	default:
		return requestError
	}
}

// UpdateContact invokes PATCH /v1/email/contacts/{id}.
func (client *Client) UpdateContact(ctx context.Context, input *UpdateContactRequest) (*ContactResponse, error) {
	if input == nil {
		input = &UpdateContactRequest{}
	}
	path := "/v1/email/contacts/{id}"
	query := url.Values{}
	headers := http.Header{}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(fmt.Sprint(input.ID)))
	body := input.Body
	request, err := client.newRequest(ctx, "PATCH", path, query, headers, body)
	if err != nil {
		return nil, decodeUpdateContactError(err)
	}
	var response ContactResponse
	if err := client.doWithRetry(request, &response); err != nil {
		return nil, decodeUpdateContactError(err)
	}
	return &response, nil
}

