// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
)

// ListCrmObjectsRequest contains the inputs for ListCrmObjects.
type ListCrmObjectsRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	After *string `json:"after,omitempty"`
	IncludeDisabled *bool `json:"include_disabled,omitempty"`
}

// ListCrmObjectsError400 is returned when ListCrmObjects responds with status 400.
type ListCrmObjectsError400 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmObjectsError400) Error() string {
	return fmt.Sprintf("kaji: ListCrmObjects failed with status %d", errorResponse.StatusCode)
}

// ListCrmObjectsError401 is returned when ListCrmObjects responds with status 401.
type ListCrmObjectsError401 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmObjectsError401) Error() string {
	return fmt.Sprintf("kaji: ListCrmObjects failed with status %d", errorResponse.StatusCode)
}

// ListCrmObjectsError403 is returned when ListCrmObjects responds with status 403.
type ListCrmObjectsError403 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmObjectsError403) Error() string {
	return fmt.Sprintf("kaji: ListCrmObjects failed with status %d", errorResponse.StatusCode)
}

// ListCrmObjectsError404 is returned when ListCrmObjects responds with status 404.
type ListCrmObjectsError404 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmObjectsError404) Error() string {
	return fmt.Sprintf("kaji: ListCrmObjects failed with status %d", errorResponse.StatusCode)
}

// ListCrmObjectsError409 is returned when ListCrmObjects responds with status 409.
type ListCrmObjectsError409 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmObjectsError409) Error() string {
	return fmt.Sprintf("kaji: ListCrmObjects failed with status %d", errorResponse.StatusCode)
}

// ListCrmObjectsError413 is returned when ListCrmObjects responds with status 413.
type ListCrmObjectsError413 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmObjectsError413) Error() string {
	return fmt.Sprintf("kaji: ListCrmObjects failed with status %d", errorResponse.StatusCode)
}

// ListCrmObjectsError415 is returned when ListCrmObjects responds with status 415.
type ListCrmObjectsError415 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmObjectsError415) Error() string {
	return fmt.Sprintf("kaji: ListCrmObjects failed with status %d", errorResponse.StatusCode)
}

// ListCrmObjectsError503 is returned when ListCrmObjects responds with status 503.
type ListCrmObjectsError503 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmObjectsError503) Error() string {
	return fmt.Sprintf("kaji: ListCrmObjects failed with status %d", errorResponse.StatusCode)
}

func decodeListCrmObjectsError(requestError error) error {
	var transportError *kajiAPIError
	if !errors.As(requestError, &transportError) { return requestError }
	switch transportError.StatusCode {
	case 400:
		result := &ListCrmObjectsError400{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 401:
		result := &ListCrmObjectsError401{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 403:
		result := &ListCrmObjectsError403{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 404:
		result := &ListCrmObjectsError404{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 409:
		result := &ListCrmObjectsError409{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 413:
		result := &ListCrmObjectsError413{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 415:
		result := &ListCrmObjectsError415{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 503:
		result := &ListCrmObjectsError503{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	default:
		return requestError
	}
}

// ListCrmObjects invokes GET /v1/crm/objects.
func (client *Client) ListCrmObjects(ctx context.Context, input *ListCrmObjectsRequest) (*map[string]any, error) {
	if input == nil {
		input = &ListCrmObjectsRequest{}
	}
	path := "/v1/crm/objects"
	query := url.Values{}
	headers := http.Header{}
	if err := addQuery(query, "limit", input.Limit); err != nil {
		return nil, err
	}
	if err := addQuery(query, "after", input.After); err != nil {
		return nil, err
	}
	if err := addQuery(query, "include_disabled", input.IncludeDisabled); err != nil {
		return nil, err
	}
	var body any
	request, err := client.newRequest(ctx, "GET", path, query, headers, body)
	if err != nil {
		return nil, decodeListCrmObjectsError(err)
	}
	var response map[string]any
	if err := client.doWithRetry(request, &response); err != nil {
		return nil, decodeListCrmObjectsError(err)
	}
	return &response, nil
}

