// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// GetInboundRequest contains the inputs for GetInbound.
type GetInboundRequest struct {
	MessageID string `json:"message_id,omitempty"`
}

// GetInboundError401 is returned when GetInbound responds with status 401.
type GetInboundError401 struct {
	StatusCode int
	RawBody    []byte
	Body       ErrorResponse
}

func (errorResponse *GetInboundError401) Error() string {
	return fmt.Sprintf("kaji: GetInbound failed with status %d", errorResponse.StatusCode)
}

// GetInboundError404 is returned when GetInbound responds with status 404.
type GetInboundError404 struct {
	StatusCode int
	RawBody    []byte
	Body       ErrorResponse
}

func (errorResponse *GetInboundError404) Error() string {
	return fmt.Sprintf("kaji: GetInbound failed with status %d", errorResponse.StatusCode)
}

// GetInboundError503 is returned when GetInbound responds with status 503.
type GetInboundError503 struct {
	StatusCode int
	RawBody    []byte
	Body       ErrorResponse
}

func (errorResponse *GetInboundError503) Error() string {
	return fmt.Sprintf("kaji: GetInbound failed with status %d", errorResponse.StatusCode)
}

func decodeGetInboundError(requestError error) error {
	var transportError *kajiAPIError
	if !errors.As(requestError, &transportError) { return requestError }
	switch transportError.StatusCode {
	case 401:
		result := &GetInboundError401{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 404:
		result := &GetInboundError404{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 503:
		result := &GetInboundError503{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	default:
		return requestError
	}
}

// GetInbound invokes GET /v1/email/inbound/{message_id}.
func (client *Client) GetInbound(ctx context.Context, input *GetInboundRequest) (*InboundResponse, error) {
	if input == nil {
		input = &GetInboundRequest{}
	}
	path := "/v1/email/inbound/{message_id}"
	query := url.Values{}
	headers := http.Header{}
	path = strings.ReplaceAll(path, "{message_id}", url.PathEscape(fmt.Sprint(input.MessageID)))
	var body any
	request, err := client.newRequest(ctx, "GET", path, query, headers, body)
	if err != nil {
		return nil, decodeGetInboundError(err)
	}
	var response InboundResponse
	if err := client.doWithRetry(request, &response); err != nil {
		return nil, decodeGetInboundError(err)
	}
	return &response, nil
}

