// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// GetCrmRecordRequest contains the inputs for GetCrmRecord.
type GetCrmRecordRequest struct {
	RecordID string `json:"record_id,omitempty"`
}

// GetCrmRecordError400 is returned when GetCrmRecord responds with status 400.
type GetCrmRecordError400 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmRecordError400) Error() string {
	return fmt.Sprintf("kaji: GetCrmRecord failed with status %d", errorResponse.StatusCode)
}

// GetCrmRecordError401 is returned when GetCrmRecord responds with status 401.
type GetCrmRecordError401 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmRecordError401) Error() string {
	return fmt.Sprintf("kaji: GetCrmRecord failed with status %d", errorResponse.StatusCode)
}

// GetCrmRecordError403 is returned when GetCrmRecord responds with status 403.
type GetCrmRecordError403 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmRecordError403) Error() string {
	return fmt.Sprintf("kaji: GetCrmRecord failed with status %d", errorResponse.StatusCode)
}

// GetCrmRecordError404 is returned when GetCrmRecord responds with status 404.
type GetCrmRecordError404 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmRecordError404) Error() string {
	return fmt.Sprintf("kaji: GetCrmRecord failed with status %d", errorResponse.StatusCode)
}

// GetCrmRecordError409 is returned when GetCrmRecord responds with status 409.
type GetCrmRecordError409 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmRecordError409) Error() string {
	return fmt.Sprintf("kaji: GetCrmRecord failed with status %d", errorResponse.StatusCode)
}

// GetCrmRecordError413 is returned when GetCrmRecord responds with status 413.
type GetCrmRecordError413 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmRecordError413) Error() string {
	return fmt.Sprintf("kaji: GetCrmRecord failed with status %d", errorResponse.StatusCode)
}

// GetCrmRecordError415 is returned when GetCrmRecord responds with status 415.
type GetCrmRecordError415 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmRecordError415) Error() string {
	return fmt.Sprintf("kaji: GetCrmRecord failed with status %d", errorResponse.StatusCode)
}

// GetCrmRecordError503 is returned when GetCrmRecord responds with status 503.
type GetCrmRecordError503 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmRecordError503) Error() string {
	return fmt.Sprintf("kaji: GetCrmRecord failed with status %d", errorResponse.StatusCode)
}

func decodeGetCrmRecordError(requestError error) error {
	var transportError *kajiAPIError
	if !errors.As(requestError, &transportError) { return requestError }
	switch transportError.StatusCode {
	case 400:
		result := &GetCrmRecordError400{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 401:
		result := &GetCrmRecordError401{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 403:
		result := &GetCrmRecordError403{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 404:
		result := &GetCrmRecordError404{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 409:
		result := &GetCrmRecordError409{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 413:
		result := &GetCrmRecordError413{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 415:
		result := &GetCrmRecordError415{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 503:
		result := &GetCrmRecordError503{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	default:
		return requestError
	}
}

// GetCrmRecord invokes GET /v1/crm/records/{record_id}.
func (client *Client) GetCrmRecord(ctx context.Context, input *GetCrmRecordRequest) (*CrmRecordResponse, error) {
	if input == nil {
		input = &GetCrmRecordRequest{}
	}
	path := "/v1/crm/records/{record_id}"
	query := url.Values{}
	headers := http.Header{}
	path = strings.ReplaceAll(path, "{record_id}", url.PathEscape(fmt.Sprint(input.RecordID)))
	var body any
	request, err := client.newRequest(ctx, "GET", path, query, headers, body)
	if err != nil {
		return nil, decodeGetCrmRecordError(err)
	}
	var response CrmRecordResponse
	if err := client.doWithRetry(request, &response); err != nil {
		return nil, decodeGetCrmRecordError(err)
	}
	return &response, nil
}

