// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// CancelRequest contains the inputs for Cancel.
type CancelRequest struct {
	SendID string `json:"send_id,omitempty"`
}

// CancelError401 is returned when Cancel responds with status 401.
type CancelError401 struct {
	StatusCode int
	RawBody    []byte
	Body       ErrorResponse
}

func (errorResponse *CancelError401) Error() string {
	return fmt.Sprintf("kaji: Cancel failed with status %d", errorResponse.StatusCode)
}

// CancelError403 is returned when Cancel responds with status 403.
type CancelError403 struct {
	StatusCode int
	RawBody    []byte
	Body       ErrorResponse
}

func (errorResponse *CancelError403) Error() string {
	return fmt.Sprintf("kaji: Cancel failed with status %d", errorResponse.StatusCode)
}

// CancelError404 is returned when Cancel responds with status 404.
type CancelError404 struct {
	StatusCode int
	RawBody    []byte
	Body       ErrorResponse
}

func (errorResponse *CancelError404) Error() string {
	return fmt.Sprintf("kaji: Cancel failed with status %d", errorResponse.StatusCode)
}

// CancelError409 is returned when Cancel responds with status 409.
type CancelError409 struct {
	StatusCode int
	RawBody    []byte
	Body       ErrorResponse
}

func (errorResponse *CancelError409) Error() string {
	return fmt.Sprintf("kaji: Cancel failed with status %d", errorResponse.StatusCode)
}

// CancelError503 is returned when Cancel responds with status 503.
type CancelError503 struct {
	StatusCode int
	RawBody    []byte
	Body       ErrorResponse
}

func (errorResponse *CancelError503) Error() string {
	return fmt.Sprintf("kaji: Cancel failed with status %d", errorResponse.StatusCode)
}

func decodeCancelError(requestError error) error {
	var transportError *kajiAPIError
	if !errors.As(requestError, &transportError) { return requestError }
	switch transportError.StatusCode {
	case 401:
		result := &CancelError401{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 403:
		result := &CancelError403{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 404:
		result := &CancelError404{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 409:
		result := &CancelError409{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 503:
		result := &CancelError503{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	default:
		return requestError
	}
}

// Cancel invokes DELETE /v1/email/sends/{send_id}.
func (client *Client) Cancel(ctx context.Context, input *CancelRequest) (*SendResponse, error) {
	if input == nil {
		input = &CancelRequest{}
	}
	path := "/v1/email/sends/{send_id}"
	query := url.Values{}
	headers := http.Header{}
	path = strings.ReplaceAll(path, "{send_id}", url.PathEscape(fmt.Sprint(input.SendID)))
	var body any
	request, err := client.newRequest(ctx, "DELETE", path, query, headers, body)
	if err != nil {
		return nil, decodeCancelError(err)
	}
	var response SendResponse
	if err := client.doWithRetry(request, &response); err != nil {
		return nil, decodeCancelError(err)
	}
	return &response, nil
}

