// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// UpdateWebhookRequest contains the inputs for UpdateWebhook.
type UpdateWebhookRequest struct {
	WebhookID string `json:"webhook_id,omitempty"`
	Body HookUpdate `json:"body,omitempty"`
}

// UpdateWebhookError401 is returned when UpdateWebhook responds with status 401.
type UpdateWebhookError401 struct {
	StatusCode int
	RawBody    []byte
	Body       ErrorResponse
}

func (errorResponse *UpdateWebhookError401) Error() string {
	return fmt.Sprintf("kaji: UpdateWebhook failed with status %d", errorResponse.StatusCode)
}

// UpdateWebhookError404 is returned when UpdateWebhook responds with status 404.
type UpdateWebhookError404 struct {
	StatusCode int
	RawBody    []byte
	Body       ErrorResponse
}

func (errorResponse *UpdateWebhookError404) Error() string {
	return fmt.Sprintf("kaji: UpdateWebhook failed with status %d", errorResponse.StatusCode)
}

// UpdateWebhookError422 is returned when UpdateWebhook responds with status 422.
type UpdateWebhookError422 struct {
	StatusCode int
	RawBody    []byte
	Body       ErrorResponse
}

func (errorResponse *UpdateWebhookError422) Error() string {
	return fmt.Sprintf("kaji: UpdateWebhook failed with status %d", errorResponse.StatusCode)
}

// UpdateWebhookError503 is returned when UpdateWebhook responds with status 503.
type UpdateWebhookError503 struct {
	StatusCode int
	RawBody    []byte
	Body       ErrorResponse
}

func (errorResponse *UpdateWebhookError503) Error() string {
	return fmt.Sprintf("kaji: UpdateWebhook failed with status %d", errorResponse.StatusCode)
}

func decodeUpdateWebhookError(requestError error) error {
	var transportError *kajiAPIError
	if !errors.As(requestError, &transportError) { return requestError }
	switch transportError.StatusCode {
	case 401:
		result := &UpdateWebhookError401{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 404:
		result := &UpdateWebhookError404{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 422:
		result := &UpdateWebhookError422{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 503:
		result := &UpdateWebhookError503{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	default:
		return requestError
	}
}

// UpdateWebhook invokes PATCH /v1/email/webhooks/{webhook_id}.
func (client *Client) UpdateWebhook(ctx context.Context, input *UpdateWebhookRequest) (*WebhookResponse, error) {
	if input == nil {
		input = &UpdateWebhookRequest{}
	}
	path := "/v1/email/webhooks/{webhook_id}"
	query := url.Values{}
	headers := http.Header{}
	path = strings.ReplaceAll(path, "{webhook_id}", url.PathEscape(fmt.Sprint(input.WebhookID)))
	body := input.Body
	request, err := client.newRequest(ctx, "PATCH", path, query, headers, body)
	if err != nil {
		return nil, decodeUpdateWebhookError(err)
	}
	var response WebhookResponse
	if err := client.doWithRetry(request, &response); err != nil {
		return nil, decodeUpdateWebhookError(err)
	}
	return &response, nil
}

