// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// UpdateCrmObjectAttributeRequest contains the inputs for UpdateCrmObjectAttribute.
type UpdateCrmObjectAttributeRequest struct {
	Object string `json:"object,omitempty"`
	Attribute string `json:"attribute,omitempty"`
	Body CrmAttributePatch `json:"body,omitempty"`
}

// UpdateCrmObjectAttributeError400 is returned when UpdateCrmObjectAttribute responds with status 400.
type UpdateCrmObjectAttributeError400 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmObjectAttributeError400) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmObjectAttribute failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmObjectAttributeError401 is returned when UpdateCrmObjectAttribute responds with status 401.
type UpdateCrmObjectAttributeError401 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmObjectAttributeError401) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmObjectAttribute failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmObjectAttributeError403 is returned when UpdateCrmObjectAttribute responds with status 403.
type UpdateCrmObjectAttributeError403 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmObjectAttributeError403) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmObjectAttribute failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmObjectAttributeError404 is returned when UpdateCrmObjectAttribute responds with status 404.
type UpdateCrmObjectAttributeError404 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmObjectAttributeError404) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmObjectAttribute failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmObjectAttributeError409 is returned when UpdateCrmObjectAttribute responds with status 409.
type UpdateCrmObjectAttributeError409 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmObjectAttributeError409) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmObjectAttribute failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmObjectAttributeError413 is returned when UpdateCrmObjectAttribute responds with status 413.
type UpdateCrmObjectAttributeError413 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmObjectAttributeError413) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmObjectAttribute failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmObjectAttributeError415 is returned when UpdateCrmObjectAttribute responds with status 415.
type UpdateCrmObjectAttributeError415 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmObjectAttributeError415) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmObjectAttribute failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmObjectAttributeError503 is returned when UpdateCrmObjectAttribute responds with status 503.
type UpdateCrmObjectAttributeError503 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmObjectAttributeError503) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmObjectAttribute failed with status %d", errorResponse.StatusCode)
}

func decodeUpdateCrmObjectAttributeError(requestError error) error {
	var transportError *kajiAPIError
	if !errors.As(requestError, &transportError) { return requestError }
	switch transportError.StatusCode {
	case 400:
		result := &UpdateCrmObjectAttributeError400{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 401:
		result := &UpdateCrmObjectAttributeError401{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 403:
		result := &UpdateCrmObjectAttributeError403{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 404:
		result := &UpdateCrmObjectAttributeError404{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 409:
		result := &UpdateCrmObjectAttributeError409{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 413:
		result := &UpdateCrmObjectAttributeError413{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 415:
		result := &UpdateCrmObjectAttributeError415{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 503:
		result := &UpdateCrmObjectAttributeError503{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	default:
		return requestError
	}
}

// UpdateCrmObjectAttribute invokes PATCH /v1/crm/objects/{object}/attributes/{attribute}.
func (client *Client) UpdateCrmObjectAttribute(ctx context.Context, input *UpdateCrmObjectAttributeRequest) (*CrmMetadataAttributeResponse, error) {
	if input == nil {
		input = &UpdateCrmObjectAttributeRequest{}
	}
	path := "/v1/crm/objects/{object}/attributes/{attribute}"
	query := url.Values{}
	headers := http.Header{}
	path = strings.ReplaceAll(path, "{object}", url.PathEscape(fmt.Sprint(input.Object)))
	path = strings.ReplaceAll(path, "{attribute}", url.PathEscape(fmt.Sprint(input.Attribute)))
	body := input.Body
	request, err := client.newRequest(ctx, "PATCH", path, query, headers, body)
	if err != nil {
		return nil, decodeUpdateCrmObjectAttributeError(err)
	}
	var response CrmMetadataAttributeResponse
	if err := client.doWithRetry(request, &response); err != nil {
		return nil, decodeUpdateCrmObjectAttributeError(err)
	}
	return &response, nil
}

