// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// GetCrmObjectQualityRequest contains the inputs for GetCrmObjectQuality.
type GetCrmObjectQualityRequest struct {
	Object string `json:"object,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	After *string `json:"after,omitempty"`
	IncludeArchived *bool `json:"include_archived,omitempty"`
}

// GetCrmObjectQualityError400 is returned when GetCrmObjectQuality responds with status 400.
type GetCrmObjectQualityError400 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmObjectQualityError400) Error() string {
	return fmt.Sprintf("kaji: GetCrmObjectQuality failed with status %d", errorResponse.StatusCode)
}

// GetCrmObjectQualityError401 is returned when GetCrmObjectQuality responds with status 401.
type GetCrmObjectQualityError401 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmObjectQualityError401) Error() string {
	return fmt.Sprintf("kaji: GetCrmObjectQuality failed with status %d", errorResponse.StatusCode)
}

// GetCrmObjectQualityError403 is returned when GetCrmObjectQuality responds with status 403.
type GetCrmObjectQualityError403 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmObjectQualityError403) Error() string {
	return fmt.Sprintf("kaji: GetCrmObjectQuality failed with status %d", errorResponse.StatusCode)
}

// GetCrmObjectQualityError404 is returned when GetCrmObjectQuality responds with status 404.
type GetCrmObjectQualityError404 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmObjectQualityError404) Error() string {
	return fmt.Sprintf("kaji: GetCrmObjectQuality failed with status %d", errorResponse.StatusCode)
}

// GetCrmObjectQualityError409 is returned when GetCrmObjectQuality responds with status 409.
type GetCrmObjectQualityError409 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmObjectQualityError409) Error() string {
	return fmt.Sprintf("kaji: GetCrmObjectQuality failed with status %d", errorResponse.StatusCode)
}

// GetCrmObjectQualityError413 is returned when GetCrmObjectQuality responds with status 413.
type GetCrmObjectQualityError413 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmObjectQualityError413) Error() string {
	return fmt.Sprintf("kaji: GetCrmObjectQuality failed with status %d", errorResponse.StatusCode)
}

// GetCrmObjectQualityError415 is returned when GetCrmObjectQuality responds with status 415.
type GetCrmObjectQualityError415 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmObjectQualityError415) Error() string {
	return fmt.Sprintf("kaji: GetCrmObjectQuality failed with status %d", errorResponse.StatusCode)
}

// GetCrmObjectQualityError503 is returned when GetCrmObjectQuality responds with status 503.
type GetCrmObjectQualityError503 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *GetCrmObjectQualityError503) Error() string {
	return fmt.Sprintf("kaji: GetCrmObjectQuality failed with status %d", errorResponse.StatusCode)
}

func decodeGetCrmObjectQualityError(requestError error) error {
	var transportError *kajiAPIError
	if !errors.As(requestError, &transportError) { return requestError }
	switch transportError.StatusCode {
	case 400:
		result := &GetCrmObjectQualityError400{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 401:
		result := &GetCrmObjectQualityError401{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 403:
		result := &GetCrmObjectQualityError403{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 404:
		result := &GetCrmObjectQualityError404{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 409:
		result := &GetCrmObjectQualityError409{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 413:
		result := &GetCrmObjectQualityError413{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 415:
		result := &GetCrmObjectQualityError415{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 503:
		result := &GetCrmObjectQualityError503{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	default:
		return requestError
	}
}

// GetCrmObjectQuality invokes GET /v1/crm/objects/{object}/quality.
func (client *Client) GetCrmObjectQuality(ctx context.Context, input *GetCrmObjectQualityRequest) (*CrmQualityResponse, error) {
	if input == nil {
		input = &GetCrmObjectQualityRequest{}
	}
	path := "/v1/crm/objects/{object}/quality"
	query := url.Values{}
	headers := http.Header{}
	path = strings.ReplaceAll(path, "{object}", url.PathEscape(fmt.Sprint(input.Object)))
	if err := addQuery(query, "limit", input.Limit); err != nil {
		return nil, err
	}
	if err := addQuery(query, "after", input.After); err != nil {
		return nil, err
	}
	if err := addQuery(query, "include_archived", input.IncludeArchived); err != nil {
		return nil, err
	}
	var body any
	request, err := client.newRequest(ctx, "GET", path, query, headers, body)
	if err != nil {
		return nil, decodeGetCrmObjectQualityError(err)
	}
	var response CrmQualityResponse
	if err := client.doWithRetry(request, &response); err != nil {
		return nil, decodeGetCrmObjectQualityError(err)
	}
	return &response, nil
}

