// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// UpdateCrmListRequest contains the inputs for UpdateCrmList.
type UpdateCrmListRequest struct {
	List string `json:"list,omitempty"`
	Body CrmUpdateList `json:"body,omitempty"`
}

// UpdateCrmListError400 is returned when UpdateCrmList responds with status 400.
type UpdateCrmListError400 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmListError400) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmList failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmListError401 is returned when UpdateCrmList responds with status 401.
type UpdateCrmListError401 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmListError401) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmList failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmListError403 is returned when UpdateCrmList responds with status 403.
type UpdateCrmListError403 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmListError403) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmList failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmListError404 is returned when UpdateCrmList responds with status 404.
type UpdateCrmListError404 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmListError404) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmList failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmListError409 is returned when UpdateCrmList responds with status 409.
type UpdateCrmListError409 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmListError409) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmList failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmListError413 is returned when UpdateCrmList responds with status 413.
type UpdateCrmListError413 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmListError413) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmList failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmListError415 is returned when UpdateCrmList responds with status 415.
type UpdateCrmListError415 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmListError415) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmList failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmListError503 is returned when UpdateCrmList responds with status 503.
type UpdateCrmListError503 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmListError503) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmList failed with status %d", errorResponse.StatusCode)
}

func decodeUpdateCrmListError(requestError error) error {
	var transportError *kajiAPIError
	if !errors.As(requestError, &transportError) { return requestError }
	switch transportError.StatusCode {
	case 400:
		result := &UpdateCrmListError400{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 401:
		result := &UpdateCrmListError401{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 403:
		result := &UpdateCrmListError403{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 404:
		result := &UpdateCrmListError404{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 409:
		result := &UpdateCrmListError409{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 413:
		result := &UpdateCrmListError413{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 415:
		result := &UpdateCrmListError415{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 503:
		result := &UpdateCrmListError503{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	default:
		return requestError
	}
}

// UpdateCrmList invokes PATCH /v1/crm/lists/{list}.
func (client *Client) UpdateCrmList(ctx context.Context, input *UpdateCrmListRequest) (*CrmListResponse, error) {
	if input == nil {
		input = &UpdateCrmListRequest{}
	}
	path := "/v1/crm/lists/{list}"
	query := url.Values{}
	headers := http.Header{}
	path = strings.ReplaceAll(path, "{list}", url.PathEscape(fmt.Sprint(input.List)))
	body := input.Body
	request, err := client.newRequest(ctx, "PATCH", path, query, headers, body)
	if err != nil {
		return nil, decodeUpdateCrmListError(err)
	}
	var response CrmListResponse
	if err := client.doWithRetry(request, &response); err != nil {
		return nil, decodeUpdateCrmListError(err)
	}
	return &response, nil
}

