// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// UpdateCrmTaskRequest contains the inputs for UpdateCrmTask.
type UpdateCrmTaskRequest struct {
	TaskID string `json:"task_id,omitempty"`
	Body CrmTaskPatch `json:"body,omitempty"`
}

// UpdateCrmTaskError400 is returned when UpdateCrmTask responds with status 400.
type UpdateCrmTaskError400 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmTaskError400) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmTask failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmTaskError401 is returned when UpdateCrmTask responds with status 401.
type UpdateCrmTaskError401 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmTaskError401) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmTask failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmTaskError403 is returned when UpdateCrmTask responds with status 403.
type UpdateCrmTaskError403 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmTaskError403) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmTask failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmTaskError404 is returned when UpdateCrmTask responds with status 404.
type UpdateCrmTaskError404 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmTaskError404) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmTask failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmTaskError409 is returned when UpdateCrmTask responds with status 409.
type UpdateCrmTaskError409 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmTaskError409) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmTask failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmTaskError413 is returned when UpdateCrmTask responds with status 413.
type UpdateCrmTaskError413 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmTaskError413) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmTask failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmTaskError415 is returned when UpdateCrmTask responds with status 415.
type UpdateCrmTaskError415 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmTaskError415) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmTask failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmTaskError503 is returned when UpdateCrmTask responds with status 503.
type UpdateCrmTaskError503 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmTaskError503) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmTask failed with status %d", errorResponse.StatusCode)
}

func decodeUpdateCrmTaskError(requestError error) error {
	var transportError *kajiAPIError
	if !errors.As(requestError, &transportError) { return requestError }
	switch transportError.StatusCode {
	case 400:
		result := &UpdateCrmTaskError400{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 401:
		result := &UpdateCrmTaskError401{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 403:
		result := &UpdateCrmTaskError403{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 404:
		result := &UpdateCrmTaskError404{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 409:
		result := &UpdateCrmTaskError409{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 413:
		result := &UpdateCrmTaskError413{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 415:
		result := &UpdateCrmTaskError415{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 503:
		result := &UpdateCrmTaskError503{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	default:
		return requestError
	}
}

// UpdateCrmTask invokes PATCH /v1/crm/tasks/{task_id}.
func (client *Client) UpdateCrmTask(ctx context.Context, input *UpdateCrmTaskRequest) (*map[string]any, error) {
	if input == nil {
		input = &UpdateCrmTaskRequest{}
	}
	path := "/v1/crm/tasks/{task_id}"
	query := url.Values{}
	headers := http.Header{}
	path = strings.ReplaceAll(path, "{task_id}", url.PathEscape(fmt.Sprint(input.TaskID)))
	body := input.Body
	request, err := client.newRequest(ctx, "PATCH", path, query, headers, body)
	if err != nil {
		return nil, decodeUpdateCrmTaskError(err)
	}
	var response map[string]any
	if err := client.doWithRetry(request, &response); err != nil {
		return nil, decodeUpdateCrmTaskError(err)
	}
	return &response, nil
}

