// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
)

// ListWebhooksError401 is returned when ListWebhooks responds with status 401.
type ListWebhooksError401 struct {
	StatusCode int
	RawBody    []byte
	Body       ErrorResponse
}

func (errorResponse *ListWebhooksError401) Error() string {
	return fmt.Sprintf("kaji: ListWebhooks failed with status %d", errorResponse.StatusCode)
}

// ListWebhooksError503 is returned when ListWebhooks responds with status 503.
type ListWebhooksError503 struct {
	StatusCode int
	RawBody    []byte
	Body       ErrorResponse
}

func (errorResponse *ListWebhooksError503) Error() string {
	return fmt.Sprintf("kaji: ListWebhooks failed with status %d", errorResponse.StatusCode)
}

func decodeListWebhooksError(requestError error) error {
	var transportError *kajiAPIError
	if !errors.As(requestError, &transportError) { return requestError }
	switch transportError.StatusCode {
	case 401:
		result := &ListWebhooksError401{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 503:
		result := &ListWebhooksError503{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	default:
		return requestError
	}
}

// ListWebhooks invokes GET /v1/email/webhooks.
func (client *Client) ListWebhooks(ctx context.Context) (*WebhookListResponse, error) {
	path := "/v1/email/webhooks"
	query := url.Values{}
	headers := http.Header{}
	var body any
	request, err := client.newRequest(ctx, "GET", path, query, headers, body)
	if err != nil {
		return nil, decodeListWebhooksError(err)
	}
	var response WebhookListResponse
	if err := client.doWithRetry(request, &response); err != nil {
		return nil, decodeListWebhooksError(err)
	}
	return &response, nil
}

