// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// ListCrmListEntriesRequest contains the inputs for ListCrmListEntries.
type ListCrmListEntriesRequest struct {
	List string `json:"list,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	After *string `json:"after,omitempty"`
}

// ListCrmListEntriesError400 is returned when ListCrmListEntries responds with status 400.
type ListCrmListEntriesError400 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmListEntriesError400) Error() string {
	return fmt.Sprintf("kaji: ListCrmListEntries failed with status %d", errorResponse.StatusCode)
}

// ListCrmListEntriesError401 is returned when ListCrmListEntries responds with status 401.
type ListCrmListEntriesError401 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmListEntriesError401) Error() string {
	return fmt.Sprintf("kaji: ListCrmListEntries failed with status %d", errorResponse.StatusCode)
}

// ListCrmListEntriesError403 is returned when ListCrmListEntries responds with status 403.
type ListCrmListEntriesError403 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmListEntriesError403) Error() string {
	return fmt.Sprintf("kaji: ListCrmListEntries failed with status %d", errorResponse.StatusCode)
}

// ListCrmListEntriesError404 is returned when ListCrmListEntries responds with status 404.
type ListCrmListEntriesError404 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmListEntriesError404) Error() string {
	return fmt.Sprintf("kaji: ListCrmListEntries failed with status %d", errorResponse.StatusCode)
}

// ListCrmListEntriesError409 is returned when ListCrmListEntries responds with status 409.
type ListCrmListEntriesError409 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmListEntriesError409) Error() string {
	return fmt.Sprintf("kaji: ListCrmListEntries failed with status %d", errorResponse.StatusCode)
}

// ListCrmListEntriesError413 is returned when ListCrmListEntries responds with status 413.
type ListCrmListEntriesError413 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmListEntriesError413) Error() string {
	return fmt.Sprintf("kaji: ListCrmListEntries failed with status %d", errorResponse.StatusCode)
}

// ListCrmListEntriesError415 is returned when ListCrmListEntries responds with status 415.
type ListCrmListEntriesError415 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmListEntriesError415) Error() string {
	return fmt.Sprintf("kaji: ListCrmListEntries failed with status %d", errorResponse.StatusCode)
}

// ListCrmListEntriesError503 is returned when ListCrmListEntries responds with status 503.
type ListCrmListEntriesError503 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *ListCrmListEntriesError503) Error() string {
	return fmt.Sprintf("kaji: ListCrmListEntries failed with status %d", errorResponse.StatusCode)
}

func decodeListCrmListEntriesError(requestError error) error {
	var transportError *kajiAPIError
	if !errors.As(requestError, &transportError) { return requestError }
	switch transportError.StatusCode {
	case 400:
		result := &ListCrmListEntriesError400{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 401:
		result := &ListCrmListEntriesError401{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 403:
		result := &ListCrmListEntriesError403{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 404:
		result := &ListCrmListEntriesError404{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 409:
		result := &ListCrmListEntriesError409{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 413:
		result := &ListCrmListEntriesError413{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 415:
		result := &ListCrmListEntriesError415{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 503:
		result := &ListCrmListEntriesError503{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	default:
		return requestError
	}
}

// ListCrmListEntries invokes GET /v1/crm/lists/{list}/entries.
func (client *Client) ListCrmListEntries(ctx context.Context, input *ListCrmListEntriesRequest) (*CrmListEntriesPage, error) {
	if input == nil {
		input = &ListCrmListEntriesRequest{}
	}
	path := "/v1/crm/lists/{list}/entries"
	query := url.Values{}
	headers := http.Header{}
	path = strings.ReplaceAll(path, "{list}", url.PathEscape(fmt.Sprint(input.List)))
	if err := addQuery(query, "limit", input.Limit); err != nil {
		return nil, err
	}
	if err := addQuery(query, "after", input.After); err != nil {
		return nil, err
	}
	var body any
	request, err := client.newRequest(ctx, "GET", path, query, headers, body)
	if err != nil {
		return nil, decodeListCrmListEntriesError(err)
	}
	var response CrmListEntriesPage
	if err := client.doWithRetry(request, &response); err != nil {
		return nil, decodeListCrmListEntriesError(err)
	}
	return &response, nil
}

