// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// CreateCrmRecordRequest contains the inputs for CreateCrmRecord.
type CreateCrmRecordRequest struct {
	Object string `json:"object,omitempty"`
	Body CrmRecordCreate `json:"body,omitempty"`
}

// CreateCrmRecordError400 is returned when CreateCrmRecord responds with status 400.
type CreateCrmRecordError400 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmRecordError400) Error() string {
	return fmt.Sprintf("kaji: CreateCrmRecord failed with status %d", errorResponse.StatusCode)
}

// CreateCrmRecordError401 is returned when CreateCrmRecord responds with status 401.
type CreateCrmRecordError401 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmRecordError401) Error() string {
	return fmt.Sprintf("kaji: CreateCrmRecord failed with status %d", errorResponse.StatusCode)
}

// CreateCrmRecordError403 is returned when CreateCrmRecord responds with status 403.
type CreateCrmRecordError403 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmRecordError403) Error() string {
	return fmt.Sprintf("kaji: CreateCrmRecord failed with status %d", errorResponse.StatusCode)
}

// CreateCrmRecordError404 is returned when CreateCrmRecord responds with status 404.
type CreateCrmRecordError404 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmRecordError404) Error() string {
	return fmt.Sprintf("kaji: CreateCrmRecord failed with status %d", errorResponse.StatusCode)
}

// CreateCrmRecordError409 is returned when CreateCrmRecord responds with status 409.
type CreateCrmRecordError409 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmRecordError409) Error() string {
	return fmt.Sprintf("kaji: CreateCrmRecord failed with status %d", errorResponse.StatusCode)
}

// CreateCrmRecordError413 is returned when CreateCrmRecord responds with status 413.
type CreateCrmRecordError413 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmRecordError413) Error() string {
	return fmt.Sprintf("kaji: CreateCrmRecord failed with status %d", errorResponse.StatusCode)
}

// CreateCrmRecordError415 is returned when CreateCrmRecord responds with status 415.
type CreateCrmRecordError415 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmRecordError415) Error() string {
	return fmt.Sprintf("kaji: CreateCrmRecord failed with status %d", errorResponse.StatusCode)
}

// CreateCrmRecordError503 is returned when CreateCrmRecord responds with status 503.
type CreateCrmRecordError503 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *CreateCrmRecordError503) Error() string {
	return fmt.Sprintf("kaji: CreateCrmRecord failed with status %d", errorResponse.StatusCode)
}

func decodeCreateCrmRecordError(requestError error) error {
	var transportError *kajiAPIError
	if !errors.As(requestError, &transportError) { return requestError }
	switch transportError.StatusCode {
	case 400:
		result := &CreateCrmRecordError400{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 401:
		result := &CreateCrmRecordError401{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 403:
		result := &CreateCrmRecordError403{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 404:
		result := &CreateCrmRecordError404{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 409:
		result := &CreateCrmRecordError409{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 413:
		result := &CreateCrmRecordError413{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 415:
		result := &CreateCrmRecordError415{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 503:
		result := &CreateCrmRecordError503{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	default:
		return requestError
	}
}

// CreateCrmRecord invokes POST /v1/crm/objects/{object}/records.
func (client *Client) CreateCrmRecord(ctx context.Context, input *CreateCrmRecordRequest) (*CrmRecordResponse, error) {
	if input == nil {
		input = &CreateCrmRecordRequest{}
	}
	path := "/v1/crm/objects/{object}/records"
	query := url.Values{}
	headers := http.Header{}
	path = strings.ReplaceAll(path, "{object}", url.PathEscape(fmt.Sprint(input.Object)))
	body := input.Body
	request, err := client.newRequest(ctx, "POST", path, query, headers, body)
	if err != nil {
		return nil, decodeCreateCrmRecordError(err)
	}
	var response CrmRecordResponse
	if err := client.doWithRetry(request, &response); err != nil {
		return nil, decodeCreateCrmRecordError(err)
	}
	return &response, nil
}

