// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// UpdateCrmListEntryRequest contains the inputs for UpdateCrmListEntry.
type UpdateCrmListEntryRequest struct {
	List string `json:"list,omitempty"`
	Entry string `json:"entry,omitempty"`
	Body CrmUpdateListEntry `json:"body,omitempty"`
}

// UpdateCrmListEntryError400 is returned when UpdateCrmListEntry responds with status 400.
type UpdateCrmListEntryError400 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmListEntryError400) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmListEntry failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmListEntryError401 is returned when UpdateCrmListEntry responds with status 401.
type UpdateCrmListEntryError401 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmListEntryError401) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmListEntry failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmListEntryError403 is returned when UpdateCrmListEntry responds with status 403.
type UpdateCrmListEntryError403 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmListEntryError403) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmListEntry failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmListEntryError404 is returned when UpdateCrmListEntry responds with status 404.
type UpdateCrmListEntryError404 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmListEntryError404) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmListEntry failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmListEntryError409 is returned when UpdateCrmListEntry responds with status 409.
type UpdateCrmListEntryError409 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmListEntryError409) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmListEntry failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmListEntryError413 is returned when UpdateCrmListEntry responds with status 413.
type UpdateCrmListEntryError413 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmListEntryError413) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmListEntry failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmListEntryError415 is returned when UpdateCrmListEntry responds with status 415.
type UpdateCrmListEntryError415 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmListEntryError415) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmListEntry failed with status %d", errorResponse.StatusCode)
}

// UpdateCrmListEntryError503 is returned when UpdateCrmListEntry responds with status 503.
type UpdateCrmListEntryError503 struct {
	StatusCode int
	RawBody    []byte
	Body       CrmAPIError
}

func (errorResponse *UpdateCrmListEntryError503) Error() string {
	return fmt.Sprintf("kaji: UpdateCrmListEntry failed with status %d", errorResponse.StatusCode)
}

func decodeUpdateCrmListEntryError(requestError error) error {
	var transportError *kajiAPIError
	if !errors.As(requestError, &transportError) { return requestError }
	switch transportError.StatusCode {
	case 400:
		result := &UpdateCrmListEntryError400{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 401:
		result := &UpdateCrmListEntryError401{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 403:
		result := &UpdateCrmListEntryError403{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 404:
		result := &UpdateCrmListEntryError404{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 409:
		result := &UpdateCrmListEntryError409{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 413:
		result := &UpdateCrmListEntryError413{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 415:
		result := &UpdateCrmListEntryError415{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	case 503:
		result := &UpdateCrmListEntryError503{StatusCode: transportError.StatusCode, RawBody: transportError.Body}
		if len(transportError.Body) > 0 { _ = json.Unmarshal(transportError.Body, &result.Body) }
		return result
	default:
		return requestError
	}
}

// UpdateCrmListEntry invokes PATCH /v1/crm/lists/{list}/entries/{entry}.
func (client *Client) UpdateCrmListEntry(ctx context.Context, input *UpdateCrmListEntryRequest) (*CrmListEntryResponse, error) {
	if input == nil {
		input = &UpdateCrmListEntryRequest{}
	}
	path := "/v1/crm/lists/{list}/entries/{entry}"
	query := url.Values{}
	headers := http.Header{}
	path = strings.ReplaceAll(path, "{list}", url.PathEscape(fmt.Sprint(input.List)))
	path = strings.ReplaceAll(path, "{entry}", url.PathEscape(fmt.Sprint(input.Entry)))
	body := input.Body
	request, err := client.newRequest(ctx, "PATCH", path, query, headers, body)
	if err != nil {
		return nil, decodeUpdateCrmListEntryError(err)
	}
	var response CrmListEntryResponse
	if err := client.doWithRetry(request, &response); err != nil {
		return nil, decodeUpdateCrmListEntryError(err)
	}
	return &response, nil
}

