// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
)

// InboundService groups Inbound operations.
type InboundService struct { client *Client }

// List invokes ListInbound through the Inbound namespace.
func (service *InboundService) List(ctx context.Context, input *ListInboundRequest) (*InboundListResponse, error) {
	return service.client.ListInbound(ctx, input)
}

// Get invokes GetInbound through the Inbound namespace.
func (service *InboundService) Get(ctx context.Context, input *GetInboundRequest) (*InboundResponse, error) {
	return service.client.GetInbound(ctx, input)
}

