// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
)

// ContactsService groups Contacts operations.
type ContactsService struct { client *Client }

// List invokes ListContacts through the Contacts namespace.
func (service *ContactsService) List(ctx context.Context, input *ListContactsRequest) (*ContactListResponse, error) {
	return service.client.ListContacts(ctx, input)
}

// Create invokes CreateContact through the Contacts namespace.
func (service *ContactsService) Create(ctx context.Context, input *CreateContactRequest) (*ContactResponse, error) {
	return service.client.CreateContact(ctx, input)
}

// Query invokes QueryContacts through the Contacts namespace.
func (service *ContactsService) Query(ctx context.Context, input *QueryContactsRequest) (*ContactQueryResponse, error) {
	return service.client.QueryContacts(ctx, input)
}

// Get invokes GetContact through the Contacts namespace.
func (service *ContactsService) Get(ctx context.Context, input *GetContactRequest) (*ContactResponse, error) {
	return service.client.GetContact(ctx, input)
}

// Update invokes UpdateContact through the Contacts namespace.
func (service *ContactsService) Update(ctx context.Context, input *UpdateContactRequest) (*ContactResponse, error) {
	return service.client.UpdateContact(ctx, input)
}

