// Code generated by Kaji. DO NOT EDIT.

package githubcomrlvtappsdkpackagesgo

import (
	"context"
)

// AuthCheckResourceService groups AuthCheck operations.
type AuthCheckResourceService struct { client *Client }

// AuthCheck invokes AuthCheck through the AuthCheck namespace.
func (service *AuthCheckResourceService) AuthCheck(ctx context.Context) (*AuthCheckResponse, error) {
	return service.client.AuthCheck(ctx)
}

