/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { ErrorResponse } from '../ErrorResponse.js'
import type { InboundListResponse } from '../InboundListResponse.js'

export type ListInboundQuery = {
  limit?: number
}

export type ListInboundStatus200 = InboundListResponse

export type ListInboundStatus401 = ErrorResponse

export type ListInboundStatus422 = ErrorResponse

export type ListInboundStatus503 = ErrorResponse

export type ListInboundOptions = {
  body?: never
  path?: never
  query?: ListInboundQuery
  headers?: never
  cookie?: never
}

export type ListInboundResponses = {
  '200': ListInboundStatus200
  '401': ListInboundStatus401
  '422': ListInboundStatus422
  '503': ListInboundStatus503
}

/**
 * @description Union of all possible responses
 */
export type ListInboundResponse = ListInboundStatus200 | ListInboundStatus401 | ListInboundStatus422 | ListInboundStatus503
