// Generated by Kaji Codegen. Do not edit.


use super::super::super::*;
#[allow(unused_imports)]
use crate::models::*;

impl Client {
    /// Returns the contacts resource client.
    pub fn contacts(&self) -> ContactsClient<'_> {
        ContactsClient { client: self }
    }
}

/// Resource-first operations for contacts.
pub struct ContactsClient<'a> {
    client: &'a Client,
}

impl ContactsClient<'_> {
    /// Invokes GET /v1/email/contacts through this resource.
    pub async fn list(&self, input: ListContactsRequest) -> Result<ContactListResponse, ListContactsError> {
        self.client.list_contacts(input).await
    }

    /// Invokes POST /v1/email/contacts through this resource.
    pub async fn create(&self, body: &CreateContact) -> Result<ContactResponse, CreateContactError> {
        self.client.create_contact(body).await
    }

    /// Invokes POST /v1/email/contacts/query through this resource.
    pub async fn query(&self, body: &ContactQuery) -> Result<ContactQueryResponse, QueryContactsError> {
        self.client.query_contacts(body).await
    }

    /// Invokes GET /v1/email/contacts/{id} through this resource.
    pub async fn get(&self, input: GetContactRequest) -> Result<ContactResponse, GetContactError> {
        self.client.get_contact(input).await
    }

    /// Invokes PATCH /v1/email/contacts/{id} through this resource.
    pub async fn update(&self, input: UpdateContactRequest, body: &UpdateContact) -> Result<ContactResponse, UpdateContactError> {
        self.client.update_contact(input, body).await
    }

}
