# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Resources.Domains.Chunk0000 do
  @moduledoc false

  alias RelevateSdk.{API, Client}

  @spec list_domains(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def list_domains(client, options \\ []), do: API.list_domains(client, options)

  @spec get_domain(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def get_domain(client, options \\ []), do: API.get_domain(client, options)
end
