// Generated by Kaji Codegen. Do not edit.


#[allow(unused_imports)]
use crate::models::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct CreateWebhookResponse {
    pub api_version: String,
    pub data: Webhook,
    pub signing_secret: String,
}
