// Generated by Kaji Codegen. Do not edit.


#[allow(unused_imports)]
use crate::models::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct CreateContact {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Option<serde_json::Value>>,
    pub email: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub first_name: Option<Option<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_name: Option<Option<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub locale: Option<Option<String>>,
}
