// Generated by Kaji Codegen. Do not edit.


#[allow(unused_imports)]
use crate::models::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct CrmNoteMention {
    pub end: i64,
    #[serde(rename = "recordId")]
    pub record_id: String,
    pub start: i64,
}
