// Generated by Kaji Codegen. Do not edit.


#[allow(unused_imports)]
use crate::models::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct EventResponse {
    pub api_version: String,
    pub event_id: String,
    pub received_at: String,
    pub replayed: bool,
}
