// Generated by Kaji Codegen. Do not edit.


#[allow(unused_imports)]
use crate::models::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct InboundMessage {
    pub authentication: serde_json::Value,
    pub created_at: String,
    pub delivery_id: String,
    pub disposition: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub envelope_from: Option<Option<String>>,
    pub envelope_to: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub header_from: Option<Option<String>>,
    pub header_to: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub html_body: Option<Option<String>>,
    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub in_reply_to: Option<Option<String>>,
    pub malware_verdict: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_id: Option<Option<String>>,
    pub received_at: String,
    pub references: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub release_reason: Option<Option<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub released_at: Option<Option<String>>,
    pub route_id: String,
    pub spam_verdict: String,
    pub subject: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text_body: Option<Option<String>>,
}
