// Generated by Kaji Codegen. Do not edit.


#[allow(unused_imports)]
use crate::models::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct RecipientInput {
    pub address: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reference: Option<Option<String>>,
}
