// Generated by Kaji Codegen. Do not edit.


#[allow(unused_imports)]
use crate::models::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct SenderIdentity {
    pub address: String,
    pub created_at: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_name: Option<Option<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain_id: Option<Option<String>>,
    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reply_to: Option<Option<String>>,
    pub status: String,
    pub updated_at: String,
}
