// Generated by Kaji Codegen. Do not edit.


#[allow(unused_imports)]
use crate::models::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct SendResponse {
    pub accepted_at: String,
    pub api_version: String,
    pub reason_code: String,
    pub recipients: Vec<RecipientResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub replayed: Option<Option<bool>>,
    pub send_id: String,
    pub state: String,
}
