// Generated by Kaji Codegen. Do not edit.


#[allow(unused_imports)]
use crate::models::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WebhookDelivery {
    pub attempt_count: i64,
    pub created_at: String,
    pub event_id: String,
    pub event_type: String,
    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_attempt_at: Option<Option<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_error: Option<Option<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_attempt_at: Option<Option<String>>,
    pub payload: serde_json::Value,
    pub state: String,
}
