// Generated by Kaji Codegen. Do not edit.


use super::super::super::*;
#[allow(unused_imports)]
use crate::models::*;

impl Client {
    /// Returns the sender_identities resource client.
    pub fn sender_identities(&self) -> SenderIdentitiesClient<'_> {
        SenderIdentitiesClient { client: self }
    }
}

/// Resource-first operations for sender_identities.
pub struct SenderIdentitiesClient<'a> {
    client: &'a Client,
}

impl SenderIdentitiesClient<'_> {
    /// Invokes GET /v1/email/sender-identities through this resource.
    pub async fn list(&self, input: ListSenderIdentitiesRequest) -> Result<SenderIdentityListResponse, ListSenderIdentitiesError> {
        self.client.list_sender_identities(input).await
    }

    /// Invokes GET /v1/email/sender-identities/{id} through this resource.
    pub async fn get_sender_identity(&self, input: GetSenderIdentityRequest) -> Result<SenderIdentityResponse, GetSenderIdentityError> {
        self.client.get_sender_identity(input).await
    }

}
