// Generated by Kaji Codegen. Do not edit.

import { useMutation as useTanstackMutation, useQuery as useTanstackQuery } from '@tanstack/react-query';
import { listCrmLists } from "../clients/crm/listCrmLists.js";
export const listCrmListsQueryKey = (options: Parameters<typeof listCrmLists>[0]) => ["listCrmLists", options] as const;
export function useListCrmLists(options: Parameters<typeof listCrmLists>[0]) { return useTanstackQuery({ queryKey: listCrmListsQueryKey(options), queryFn: () => listCrmLists(options) }); }

import { createCrmList } from "../clients/crm/createCrmList.js";
export function useCreateCrmList() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof createCrmList>[0]) => createCrmList(options) }); }

import { deleteCrmList } from "../clients/crm/deleteCrmList.js";
export function useDeleteCrmList() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof deleteCrmList>[0]) => deleteCrmList(options) }); }

import { getCrmList } from "../clients/crm/getCrmList.js";
export const getCrmListQueryKey = (options: Parameters<typeof getCrmList>[0]) => ["getCrmList", options] as const;
export function useGetCrmList(options: Parameters<typeof getCrmList>[0]) { return useTanstackQuery({ queryKey: getCrmListQueryKey(options), queryFn: () => getCrmList(options) }); }

import { updateCrmList } from "../clients/crm/updateCrmList.js";
export function useUpdateCrmList() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof updateCrmList>[0]) => updateCrmList(options) }); }

import { listCrmListAttributes } from "../clients/crm/listCrmListAttributes.js";
export const listCrmListAttributesQueryKey = (options: Parameters<typeof listCrmListAttributes>[0]) => ["listCrmListAttributes", options] as const;
export function useListCrmListAttributes(options: Parameters<typeof listCrmListAttributes>[0]) { return useTanstackQuery({ queryKey: listCrmListAttributesQueryKey(options), queryFn: () => listCrmListAttributes(options) }); }

import { createCrmListAttribute } from "../clients/crm/createCrmListAttribute.js";
export function useCreateCrmListAttribute() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof createCrmListAttribute>[0]) => createCrmListAttribute(options) }); }

import { deleteCrmListAttribute } from "../clients/crm/deleteCrmListAttribute.js";
export function useDeleteCrmListAttribute() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof deleteCrmListAttribute>[0]) => deleteCrmListAttribute(options) }); }

import { updateCrmListAttribute } from "../clients/crm/updateCrmListAttribute.js";
export function useUpdateCrmListAttribute() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof updateCrmListAttribute>[0]) => updateCrmListAttribute(options) }); }

import { listCrmListEntries } from "../clients/crm/listCrmListEntries.js";
export const listCrmListEntriesQueryKey = (options: Parameters<typeof listCrmListEntries>[0]) => ["listCrmListEntries", options] as const;
export function useListCrmListEntries(options: Parameters<typeof listCrmListEntries>[0]) { return useTanstackQuery({ queryKey: listCrmListEntriesQueryKey(options), queryFn: () => listCrmListEntries(options) }); }

import { createCrmListEntry } from "../clients/crm/createCrmListEntry.js";
export function useCreateCrmListEntry() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof createCrmListEntry>[0]) => createCrmListEntry(options) }); }

import { deleteCrmListEntry } from "../clients/crm/deleteCrmListEntry.js";
export function useDeleteCrmListEntry() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof deleteCrmListEntry>[0]) => deleteCrmListEntry(options) }); }

import { getCrmListEntry } from "../clients/crm/getCrmListEntry.js";
export const getCrmListEntryQueryKey = (options: Parameters<typeof getCrmListEntry>[0]) => ["getCrmListEntry", options] as const;
export function useGetCrmListEntry(options: Parameters<typeof getCrmListEntry>[0]) { return useTanstackQuery({ queryKey: getCrmListEntryQueryKey(options), queryFn: () => getCrmListEntry(options) }); }

import { updateCrmListEntry } from "../clients/crm/updateCrmListEntry.js";
export function useUpdateCrmListEntry() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof updateCrmListEntry>[0]) => updateCrmListEntry(options) }); }

import { deleteCrmNote } from "../clients/crm/deleteCrmNote.js";
export function useDeleteCrmNote() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof deleteCrmNote>[0]) => deleteCrmNote(options) }); }

import { getCrmNote } from "../clients/crm/getCrmNote.js";
export const getCrmNoteQueryKey = (options: Parameters<typeof getCrmNote>[0]) => ["getCrmNote", options] as const;
export function useGetCrmNote(options: Parameters<typeof getCrmNote>[0]) { return useTanstackQuery({ queryKey: getCrmNoteQueryKey(options), queryFn: () => getCrmNote(options) }); }

import { updateCrmNote } from "../clients/crm/updateCrmNote.js";
export function useUpdateCrmNote() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof updateCrmNote>[0]) => updateCrmNote(options) }); }

import { listCrmObjects } from "../clients/crm/listCrmObjects.js";
export const listCrmObjectsQueryKey = (options: Parameters<typeof listCrmObjects>[0]) => ["listCrmObjects", options] as const;
export function useListCrmObjects(options: Parameters<typeof listCrmObjects>[0]) { return useTanstackQuery({ queryKey: listCrmObjectsQueryKey(options), queryFn: () => listCrmObjects(options) }); }

import { createCrmObject } from "../clients/crm/createCrmObject.js";
export function useCreateCrmObject() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof createCrmObject>[0]) => createCrmObject(options) }); }

import { deleteCrmObject } from "../clients/crm/deleteCrmObject.js";
export function useDeleteCrmObject() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof deleteCrmObject>[0]) => deleteCrmObject(options) }); }

import { getCrmObject } from "../clients/crm/getCrmObject.js";
export const getCrmObjectQueryKey = (options: Parameters<typeof getCrmObject>[0]) => ["getCrmObject", options] as const;
export function useGetCrmObject(options: Parameters<typeof getCrmObject>[0]) { return useTanstackQuery({ queryKey: getCrmObjectQueryKey(options), queryFn: () => getCrmObject(options) }); }

import { updateCrmObject } from "../clients/crm/updateCrmObject.js";
export function useUpdateCrmObject() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof updateCrmObject>[0]) => updateCrmObject(options) }); }

import { listCrmObjectAttributes } from "../clients/crm/listCrmObjectAttributes.js";
export const listCrmObjectAttributesQueryKey = (options: Parameters<typeof listCrmObjectAttributes>[0]) => ["listCrmObjectAttributes", options] as const;
export function useListCrmObjectAttributes(options: Parameters<typeof listCrmObjectAttributes>[0]) { return useTanstackQuery({ queryKey: listCrmObjectAttributesQueryKey(options), queryFn: () => listCrmObjectAttributes(options) }); }

import { createCrmObjectAttribute } from "../clients/crm/createCrmObjectAttribute.js";
export function useCreateCrmObjectAttribute() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof createCrmObjectAttribute>[0]) => createCrmObjectAttribute(options) }); }

import { deleteCrmObjectAttribute } from "../clients/crm/deleteCrmObjectAttribute.js";
export function useDeleteCrmObjectAttribute() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof deleteCrmObjectAttribute>[0]) => deleteCrmObjectAttribute(options) }); }

import { updateCrmObjectAttribute } from "../clients/crm/updateCrmObjectAttribute.js";
export function useUpdateCrmObjectAttribute() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof updateCrmObjectAttribute>[0]) => updateCrmObjectAttribute(options) }); }

import { previewCrmObjectDeletion } from "../clients/crm/previewCrmObjectDeletion.js";
export const previewCrmObjectDeletionQueryKey = (options: Parameters<typeof previewCrmObjectDeletion>[0]) => ["previewCrmObjectDeletion", options] as const;
export function usePreviewCrmObjectDeletion(options: Parameters<typeof previewCrmObjectDeletion>[0]) { return useTanstackQuery({ queryKey: previewCrmObjectDeletionQueryKey(options), queryFn: () => previewCrmObjectDeletion(options) }); }

import { getCrmObjectQuality } from "../clients/crm/getCrmObjectQuality.js";
export const getCrmObjectQualityQueryKey = (options: Parameters<typeof getCrmObjectQuality>[0]) => ["getCrmObjectQuality", options] as const;
export function useGetCrmObjectQuality(options: Parameters<typeof getCrmObjectQuality>[0]) { return useTanstackQuery({ queryKey: getCrmObjectQualityQueryKey(options), queryFn: () => getCrmObjectQuality(options) }); }

import { listCrmRecords } from "../clients/crm/listCrmRecords.js";
export const listCrmRecordsQueryKey = (options: Parameters<typeof listCrmRecords>[0]) => ["listCrmRecords", options] as const;
export function useListCrmRecords(options: Parameters<typeof listCrmRecords>[0]) { return useTanstackQuery({ queryKey: listCrmRecordsQueryKey(options), queryFn: () => listCrmRecords(options) }); }

import { createCrmRecord } from "../clients/crm/createCrmRecord.js";
export function useCreateCrmRecord() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof createCrmRecord>[0]) => createCrmRecord(options) }); }

import { upsertCrmRecord } from "../clients/crm/upsertCrmRecord.js";
export function useUpsertCrmRecord() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof upsertCrmRecord>[0]) => upsertCrmRecord(options) }); }

import { archiveCrmRecord } from "../clients/crm/archiveCrmRecord.js";
export function useArchiveCrmRecord() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof archiveCrmRecord>[0]) => archiveCrmRecord(options) }); }

import { getCrmRecord } from "../clients/crm/getCrmRecord.js";
export const getCrmRecordQueryKey = (options: Parameters<typeof getCrmRecord>[0]) => ["getCrmRecord", options] as const;
export function useGetCrmRecord(options: Parameters<typeof getCrmRecord>[0]) { return useTanstackQuery({ queryKey: getCrmRecordQueryKey(options), queryFn: () => getCrmRecord(options) }); }

import { updateCrmRecord } from "../clients/crm/updateCrmRecord.js";
export function useUpdateCrmRecord() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof updateCrmRecord>[0]) => updateCrmRecord(options) }); }

import { listCrmActivities } from "../clients/crm/listCrmActivities.js";
export const listCrmActivitiesQueryKey = (options: Parameters<typeof listCrmActivities>[0]) => ["listCrmActivities", options] as const;
export function useListCrmActivities(options: Parameters<typeof listCrmActivities>[0]) { return useTanstackQuery({ queryKey: listCrmActivitiesQueryKey(options), queryFn: () => listCrmActivities(options) }); }

import { listCrmNotes } from "../clients/crm/listCrmNotes.js";
export const listCrmNotesQueryKey = (options: Parameters<typeof listCrmNotes>[0]) => ["listCrmNotes", options] as const;
export function useListCrmNotes(options: Parameters<typeof listCrmNotes>[0]) { return useTanstackQuery({ queryKey: listCrmNotesQueryKey(options), queryFn: () => listCrmNotes(options) }); }

import { createCrmNote } from "../clients/crm/createCrmNote.js";
export function useCreateCrmNote() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof createCrmNote>[0]) => createCrmNote(options) }); }

import { listCrmTasks } from "../clients/crm/listCrmTasks.js";
export const listCrmTasksQueryKey = (options: Parameters<typeof listCrmTasks>[0]) => ["listCrmTasks", options] as const;
export function useListCrmTasks(options: Parameters<typeof listCrmTasks>[0]) { return useTanstackQuery({ queryKey: listCrmTasksQueryKey(options), queryFn: () => listCrmTasks(options) }); }

import { createCrmTask } from "../clients/crm/createCrmTask.js";
export function useCreateCrmTask() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof createCrmTask>[0]) => createCrmTask(options) }); }

import { deleteCrmTask } from "../clients/crm/deleteCrmTask.js";
export function useDeleteCrmTask() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof deleteCrmTask>[0]) => deleteCrmTask(options) }); }

import { getCrmTask } from "../clients/crm/getCrmTask.js";
export const getCrmTaskQueryKey = (options: Parameters<typeof getCrmTask>[0]) => ["getCrmTask", options] as const;
export function useGetCrmTask(options: Parameters<typeof getCrmTask>[0]) { return useTanstackQuery({ queryKey: getCrmTaskQueryKey(options), queryFn: () => getCrmTask(options) }); }

import { updateCrmTask } from "../clients/crm/updateCrmTask.js";
export function useUpdateCrmTask() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof updateCrmTask>[0]) => updateCrmTask(options) }); }

import { authCheck } from "../clients/authCheck/authCheck.js";
export const auth_checkQueryKey = (options: Parameters<typeof authCheck>[0]) => ["auth_check", options] as const;
export function useAuth_check(options: Parameters<typeof authCheck>[0]) { return useTanstackQuery({ queryKey: auth_checkQueryKey(options), queryFn: () => authCheck(options) }); }

import { listContacts } from "../clients/contacts/listContacts.js";
export const list_contactsQueryKey = (options: Parameters<typeof listContacts>[0]) => ["list_contacts", options] as const;
export function useList_contacts(options: Parameters<typeof listContacts>[0]) { return useTanstackQuery({ queryKey: list_contactsQueryKey(options), queryFn: () => listContacts(options) }); }

import { createContact } from "../clients/contacts/createContact.js";
export function useCreate_contact() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof createContact>[0]) => createContact(options) }); }

import { queryContacts } from "../clients/contacts/queryContacts.js";
export function useQuery_contacts() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof queryContacts>[0]) => queryContacts(options) }); }

import { getContact } from "../clients/contacts/getContact.js";
export const get_contactQueryKey = (options: Parameters<typeof getContact>[0]) => ["get_contact", options] as const;
export function useGet_contact(options: Parameters<typeof getContact>[0]) { return useTanstackQuery({ queryKey: get_contactQueryKey(options), queryFn: () => getContact(options) }); }

import { updateContact } from "../clients/contacts/updateContact.js";
export function useUpdate_contact() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof updateContact>[0]) => updateContact(options) }); }

import { listDomains } from "../clients/domains/listDomains.js";
export const list_domainsQueryKey = (options: Parameters<typeof listDomains>[0]) => ["list_domains", options] as const;
export function useList_domains(options: Parameters<typeof listDomains>[0]) { return useTanstackQuery({ queryKey: list_domainsQueryKey(options), queryFn: () => listDomains(options) }); }

import { getDomain } from "../clients/domains/getDomain.js";
export const get_domainQueryKey = (options: Parameters<typeof getDomain>[0]) => ["get_domain", options] as const;
export function useGet_domain(options: Parameters<typeof getDomain>[0]) { return useTanstackQuery({ queryKey: get_domainQueryKey(options), queryFn: () => getDomain(options) }); }

import { track } from "../clients/events/track.js";
export function useTrack() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof track>[0]) => track(options) }); }

import { listInbound } from "../clients/inbound/listInbound.js";
export const list_inboundQueryKey = (options: Parameters<typeof listInbound>[0]) => ["list_inbound", options] as const;
export function useList_inbound(options: Parameters<typeof listInbound>[0]) { return useTanstackQuery({ queryKey: list_inboundQueryKey(options), queryFn: () => listInbound(options) }); }

import { getInbound } from "../clients/inbound/getInbound.js";
export const get_inboundQueryKey = (options: Parameters<typeof getInbound>[0]) => ["get_inbound", options] as const;
export function useGet_inbound(options: Parameters<typeof getInbound>[0]) { return useTanstackQuery({ queryKey: get_inboundQueryKey(options), queryFn: () => getInbound(options) }); }

import { listSegments } from "../clients/segments/listSegments.js";
export const list_segmentsQueryKey = (options: Parameters<typeof listSegments>[0]) => ["list_segments", options] as const;
export function useList_segments(options: Parameters<typeof listSegments>[0]) { return useTanstackQuery({ queryKey: list_segmentsQueryKey(options), queryFn: () => listSegments(options) }); }

import { getSegment } from "../clients/segments/getSegment.js";
export const get_segmentQueryKey = (options: Parameters<typeof getSegment>[0]) => ["get_segment", options] as const;
export function useGet_segment(options: Parameters<typeof getSegment>[0]) { return useTanstackQuery({ queryKey: get_segmentQueryKey(options), queryFn: () => getSegment(options) }); }

import { listSenderIdentities } from "../clients/senderIdentities/listSenderIdentities.js";
export const list_sender_identitiesQueryKey = (options: Parameters<typeof listSenderIdentities>[0]) => ["list_sender_identities", options] as const;
export function useList_sender_identities(options: Parameters<typeof listSenderIdentities>[0]) { return useTanstackQuery({ queryKey: list_sender_identitiesQueryKey(options), queryFn: () => listSenderIdentities(options) }); }

import { getSenderIdentity } from "../clients/senderIdentities/getSenderIdentity.js";
export const get_sender_identityQueryKey = (options: Parameters<typeof getSenderIdentity>[0]) => ["get_sender_identity", options] as const;
export function useGet_sender_identity(options: Parameters<typeof getSenderIdentity>[0]) { return useTanstackQuery({ queryKey: get_sender_identityQueryKey(options), queryFn: () => getSenderIdentity(options) }); }

import { create } from "../clients/sends/create.js";
export function useCreate() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof create>[0]) => create(options) }); }

import { query } from "../clients/sends/query.js";
export function useQuery() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof query>[0]) => query(options) }); }

import { cancel } from "../clients/sends/cancel.js";
export function useCancel() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof cancel>[0]) => cancel(options) }); }

import { get } from "../clients/sends/get.js";
export const getOperationQueryKey = (options: Parameters<typeof get>[0]) => ["get", options] as const;
export function useGet(options: Parameters<typeof get>[0]) { return useTanstackQuery({ queryKey: getOperationQueryKey(options), queryFn: () => get(options) }); }

import { listWebhooks } from "../clients/webhooks/listWebhooks.js";
export const list_webhooksQueryKey = (options: Parameters<typeof listWebhooks>[0]) => ["list_webhooks", options] as const;
export function useList_webhooks(options: Parameters<typeof listWebhooks>[0]) { return useTanstackQuery({ queryKey: list_webhooksQueryKey(options), queryFn: () => listWebhooks(options) }); }

import { createWebhook } from "../clients/webhooks/createWebhook.js";
export function useCreate_webhook() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof createWebhook>[0]) => createWebhook(options) }); }

import { deleteWebhook } from "../clients/webhooks/deleteWebhook.js";
export function useDelete_webhook() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof deleteWebhook>[0]) => deleteWebhook(options) }); }

import { updateWebhook } from "../clients/webhooks/updateWebhook.js";
export function useUpdate_webhook() { return useTanstackMutation({ mutationFn: (options: Parameters<typeof updateWebhook>[0]) => updateWebhook(options) }); }

import { listDeliveries } from "../clients/webhooks/listDeliveries.js";
export const list_deliveriesQueryKey = (options: Parameters<typeof listDeliveries>[0]) => ["list_deliveries", options] as const;
export function useList_deliveries(options: Parameters<typeof listDeliveries>[0]) { return useTanstackQuery({ queryKey: list_deliveriesQueryKey(options), queryFn: () => listDeliveries(options) }); }

