/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { ErrorResponse } from '../ErrorResponse.js'
import type { SenderIdentityListResponse } from '../SenderIdentityListResponse.js'

export type ListSenderIdentitiesQuery = {
  limit?: number
}

export type ListSenderIdentitiesStatus200 = SenderIdentityListResponse

export type ListSenderIdentitiesStatus401 = ErrorResponse

export type ListSenderIdentitiesStatus503 = ErrorResponse

export type ListSenderIdentitiesOptions = {
  body?: never
  path?: never
  query?: ListSenderIdentitiesQuery
  headers?: never
  cookie?: never
}

export type ListSenderIdentitiesResponses = {
  '200': ListSenderIdentitiesStatus200
  '401': ListSenderIdentitiesStatus401
  '503': ListSenderIdentitiesStatus503
}

/**
 * @description Union of all possible responses
 */
export type ListSenderIdentitiesResponse = ListSenderIdentitiesStatus200 | ListSenderIdentitiesStatus401 | ListSenderIdentitiesStatus503
