<?php

declare(strict_types=1);

namespace Relevate\Sdk\Models;

use JsonSerializable;

// Generated by Kaji. Do not edit.

final class ContactQuery implements JsonSerializable
{
    public function __construct(
        public readonly ?int $limit = null,
        public readonly ?string $marketingStatus = null,
        public readonly ?int $offset = null,
        public readonly ?string $order = null,
        public readonly ?string $orderBy = null,
        public readonly ?string $search = null,
        public readonly ?string $status = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            limit: array_key_exists('limit', $data) && $source !== null ? (int) $data['limit'] : null,
            marketingStatus: array_key_exists('marketing_status', $data) && $source !== null ? (string) $data['marketing_status'] : null,
            offset: array_key_exists('offset', $data) && $source !== null ? (int) $data['offset'] : null,
            order: array_key_exists('order', $data) && $source !== null ? (string) $data['order'] : null,
            orderBy: array_key_exists('order_by', $data) && $source !== null ? (string) $data['order_by'] : null,
            search: array_key_exists('search', $data) && $source !== null ? (string) $data['search'] : null,
            status: array_key_exists('status', $data) && $source !== null ? (string) $data['status'] : null,
        );
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return array_filter([
            'limit' => $this->limit,
            'marketing_status' => $this->marketingStatus,
            'offset' => $this->offset,
            'order' => $this->order,
            'order_by' => $this->orderBy,
            'search' => $this->search,
            'status' => $this->status,
        ], static fn (mixed $value): bool => $value !== null);
    }
}
