<?php

declare(strict_types=1);

namespace Relevate\Sdk\Models;

use JsonSerializable;

// Generated by Kaji. Do not edit.

final class CrmAttributeCreate implements JsonSerializable
{
    public function __construct(
        public readonly ?string $currencyCode = null,
        public readonly ?string $expression = null,
        public readonly string $key,
        public readonly ?bool $multiple = null,
        public readonly string $name,
        public readonly ?array $options = null,
        public readonly ?bool $required = null,
        public readonly ?string $targetObjectId = null,
        public readonly string $type,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            currencyCode: array_key_exists('currency_code', $data) && $source !== null ? (string) $data['currency_code'] : null,
            expression: array_key_exists('expression', $data) && $source !== null ? (string) $data['expression'] : null,
            key: (string) $data['key'],
            multiple: array_key_exists('multiple', $data) && $source !== null ? (bool) $data['multiple'] : null,
            name: (string) $data['name'],
            options: array_key_exists('options', $data) && $source !== null ? array_map(static fn (mixed $item): mixed => (string) $item, $data['options']) : null,
            required: array_key_exists('required', $data) && $source !== null ? (bool) $data['required'] : null,
            targetObjectId: array_key_exists('target_object_id', $data) && $source !== null ? (string) $data['target_object_id'] : null,
            type: (string) $data['type'],
        );
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return array_filter([
            'currency_code' => $this->currencyCode,
            'expression' => $this->expression,
            'key' => $this->key,
            'multiple' => $this->multiple,
            'name' => $this->name,
            'options' => $this->options,
            'required' => $this->required,
            'target_object_id' => $this->targetObjectId,
            'type' => $this->type,
        ], static fn (mixed $value): bool => $value !== null);
    }
}
