<?php

declare(strict_types=1);

namespace Relevate\Sdk\Models;

use JsonSerializable;

// Generated by Kaji. Do not edit.

final class CrmCreateList implements JsonSerializable
{
    public function __construct(
        public readonly ?string $description = null,
        public readonly string $name,
        public readonly string $objectId,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            description: array_key_exists('description', $data) && $source !== null ? (string) $data['description'] : null,
            name: (string) $data['name'],
            objectId: (string) $data['object_id'],
        );
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return array_filter([
            'description' => $this->description,
            'name' => $this->name,
            'object_id' => $this->objectId,
        ], static fn (mixed $value): bool => $value !== null);
    }
}
