<?php

declare(strict_types=1);

namespace Relevate\Sdk\Models;

use JsonSerializable;

// Generated by Kaji. Do not edit.

final class CrmDeletedNote implements JsonSerializable
{
    public function __construct(
        public readonly string $deletedAt,
        public readonly string $id,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            deletedAt: (string) $data['deleted_at'],
            id: (string) $data['id'],
        );
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return array_filter([
            'deleted_at' => $this->deletedAt,
            'id' => $this->id,
        ], static fn (mixed $value): bool => $value !== null);
    }
}
