<?php

declare(strict_types=1);

namespace Relevate\Sdk\Models;

use JsonSerializable;

// Generated by Kaji. Do not edit.

final class CrmMetadataAttributesResponse implements JsonSerializable
{
    public function __construct(
        public readonly string $apiVersion,
        public readonly array $data,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            apiVersion: (string) $data['api_version'],
            data: array_map(static fn (mixed $item): mixed => CrmMetadataAttribute::fromArray($item), $data['data']),
        );
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return array_filter([
            'api_version' => $this->apiVersion,
            'data' => $this->data,
        ], static fn (mixed $value): bool => $value !== null);
    }
}
