<?php

declare(strict_types=1);

namespace Relevate\Sdk\Models;

use JsonSerializable;

// Generated by Kaji. Do not edit.

final class CrmNoteDocument implements JsonSerializable
{
    public function __construct(
        public readonly array $content,
        public readonly string $type,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            content: array_map(static fn (mixed $item): mixed => $item, $data['content']),
            type: (string) $data['type'],
        );
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return array_filter([
            'content' => $this->content,
            'type' => $this->type,
        ], static fn (mixed $value): bool => $value !== null);
    }
}
