<?php

declare(strict_types=1);

namespace Relevate\Sdk\Models;

use JsonSerializable;

// Generated by Kaji. Do not edit.

final class CrmObjectPatch implements JsonSerializable
{
    public function __construct(
        public readonly ?bool $enabled = null,
        public readonly ?string $icon = null,
        public readonly ?string $name = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            enabled: array_key_exists('enabled', $data) && $source !== null ? (bool) $data['enabled'] : null,
            icon: array_key_exists('icon', $data) && $source !== null ? (string) $data['icon'] : null,
            name: array_key_exists('name', $data) && $source !== null ? (string) $data['name'] : null,
        );
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return array_filter([
            'enabled' => $this->enabled,
            'icon' => $this->icon,
            'name' => $this->name,
        ], static fn (mixed $value): bool => $value !== null);
    }
}
