<?php

declare(strict_types=1);

namespace Relevate\Sdk\Models;

use JsonSerializable;

// Generated by Kaji. Do not edit.

final class CrmRecordPatch implements JsonSerializable
{
    public function __construct(
        public readonly ?bool $archived = null,
        public readonly ?string $displayName = null,
        public readonly ?array $values = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            archived: array_key_exists('archived', $data) && $source !== null ? (bool) $data['archived'] : null,
            displayName: array_key_exists('display_name', $data) && $source !== null ? (string) $data['display_name'] : null,
            values: array_key_exists('values', $data) && $source !== null ? $data['values'] : null,
        );
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return array_filter([
            'archived' => $this->archived,
            'display_name' => $this->displayName,
            'values' => $this->values,
        ], static fn (mixed $value): bool => $value !== null);
    }
}
