<?php

declare(strict_types=1);

namespace Relevate\Sdk\Models;

use JsonSerializable;

// Generated by Kaji. Do not edit.

final class CrmRecordCreate implements JsonSerializable
{
    public function __construct(
        public readonly string $displayName,
        public readonly ?string $externalId = null,
        public readonly ?array $values = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            displayName: (string) $data['display_name'],
            externalId: array_key_exists('external_id', $data) && $source !== null ? (string) $data['external_id'] : null,
            values: array_key_exists('values', $data) && $source !== null ? $data['values'] : null,
        );
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return array_filter([
            'display_name' => $this->displayName,
            'external_id' => $this->externalId,
            'values' => $this->values,
        ], static fn (mixed $value): bool => $value !== null);
    }
}
