<?php

declare(strict_types=1);

namespace Relevate\Sdk\Models;

use JsonSerializable;

// Generated by Kaji. Do not edit.

final class CrmUpdateList implements JsonSerializable
{
    public function __construct(
        public readonly ?string $description = null,
        public readonly ?string $name = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            description: array_key_exists('description', $data) && $source !== null ? (string) $data['description'] : null,
            name: array_key_exists('name', $data) && $source !== null ? (string) $data['name'] : null,
        );
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return array_filter([
            'description' => $this->description,
            'name' => $this->name,
        ], static fn (mixed $value): bool => $value !== null);
    }
}
