<?php

declare(strict_types=1);

namespace Relevate\Sdk\Models;

use JsonSerializable;

// Generated by Kaji. Do not edit.

final class Page implements JsonSerializable
{
    public function __construct(
        public readonly int $limit,
        public readonly ?int $nextOffset = null,
        public readonly int $offset,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            limit: (int) $data['limit'],
            nextOffset: array_key_exists('next_offset', $data) && $source !== null ? (int) $data['next_offset'] : null,
            offset: (int) $data['offset'],
        );
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return array_filter([
            'limit' => $this->limit,
            'next_offset' => $this->nextOffset,
            'offset' => $this->offset,
        ], static fn (mixed $value): bool => $value !== null);
    }
}
