<?php

declare(strict_types=1);

namespace Relevate\Sdk\Models;

use JsonSerializable;

// Generated by Kaji. Do not edit.

final class Segment implements JsonSerializable
{
    public function __construct(
        public readonly string $createdAt,
        public readonly mixed $definition,
        public readonly string $id,
        public readonly string $kind,
        public readonly ?string $lastEvaluatedAt = null,
        public readonly string $name,
        public readonly string $status,
        public readonly string $updatedAt,
        public readonly int $version,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            createdAt: (string) $data['created_at'],
            definition: $data['definition'],
            id: (string) $data['id'],
            kind: (string) $data['kind'],
            lastEvaluatedAt: array_key_exists('last_evaluated_at', $data) && $source !== null ? (string) $data['last_evaluated_at'] : null,
            name: (string) $data['name'],
            status: (string) $data['status'],
            updatedAt: (string) $data['updated_at'],
            version: (int) $data['version'],
        );
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return array_filter([
            'created_at' => $this->createdAt,
            'definition' => $this->definition,
            'id' => $this->id,
            'kind' => $this->kind,
            'last_evaluated_at' => $this->lastEvaluatedAt,
            'name' => $this->name,
            'status' => $this->status,
            'updated_at' => $this->updatedAt,
            'version' => $this->version,
        ], static fn (mixed $value): bool => $value !== null);
    }
}
