<?php

declare(strict_types=1);

namespace Relevate\Sdk\Models;

use JsonSerializable;

// Generated by Kaji. Do not edit.

final class SendResponse implements JsonSerializable
{
    public function __construct(
        public readonly string $acceptedAt,
        public readonly string $apiVersion,
        public readonly string $reasonCode,
        public readonly array $recipients,
        public readonly ?bool $replayed = null,
        public readonly string $sendId,
        public readonly string $state,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            acceptedAt: (string) $data['accepted_at'],
            apiVersion: (string) $data['api_version'],
            reasonCode: (string) $data['reason_code'],
            recipients: array_map(static fn (mixed $item): mixed => RecipientResponse::fromArray($item), $data['recipients']),
            replayed: array_key_exists('replayed', $data) && $source !== null ? (bool) $data['replayed'] : null,
            sendId: (string) $data['send_id'],
            state: (string) $data['state'],
        );
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return array_filter([
            'accepted_at' => $this->acceptedAt,
            'api_version' => $this->apiVersion,
            'reason_code' => $this->reasonCode,
            'recipients' => $this->recipients,
            'replayed' => $this->replayed,
            'send_id' => $this->sendId,
            'state' => $this->state,
        ], static fn (mixed $value): bool => $value !== null);
    }
}
