<?php

declare(strict_types=1);

namespace Relevate\Sdk\Models;

use JsonSerializable;

// Generated by Kaji. Do not edit.

final class SendRequest implements JsonSerializable
{
    public function __construct(
        public readonly ?string $htmlBody = null,
        public readonly string $messageClass,
        public readonly string $purposeId,
        public readonly array $recipients,
        public readonly ?string $reference = null,
        public readonly ?string $replyTo = null,
        public readonly string $requestKey,
        public readonly string $senderIdentityId,
        public readonly string $subject,
        public readonly string $textBody,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            htmlBody: array_key_exists('html_body', $data) && $source !== null ? (string) $data['html_body'] : null,
            messageClass: (string) $data['message_class'],
            purposeId: (string) $data['purpose_id'],
            recipients: array_map(static fn (mixed $item): mixed => RecipientInput::fromArray($item), $data['recipients']),
            reference: array_key_exists('reference', $data) && $source !== null ? (string) $data['reference'] : null,
            replyTo: array_key_exists('reply_to', $data) && $source !== null ? (string) $data['reply_to'] : null,
            requestKey: (string) $data['request_key'],
            senderIdentityId: (string) $data['sender_identity_id'],
            subject: (string) $data['subject'],
            textBody: (string) $data['text_body'],
        );
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return array_filter([
            'html_body' => $this->htmlBody,
            'message_class' => $this->messageClass,
            'purpose_id' => $this->purposeId,
            'recipients' => $this->recipients,
            'reference' => $this->reference,
            'reply_to' => $this->replyTo,
            'request_key' => $this->requestKey,
            'sender_identity_id' => $this->senderIdentityId,
            'subject' => $this->subject,
            'text_body' => $this->textBody,
        ], static fn (mixed $value): bool => $value !== null);
    }
}
