<?php

declare(strict_types=1);

namespace Relevate\Sdk\Models;

use JsonSerializable;

// Generated by Kaji. Do not edit.

final class Webhook implements JsonSerializable
{
    public function __construct(
        public readonly string $createdAt,
        public readonly array $eventTypes,
        public readonly string $id,
        public readonly string $status,
        public readonly string $updatedAt,
        public readonly string $url,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            createdAt: (string) $data['created_at'],
            eventTypes: array_map(static fn (mixed $item): mixed => (string) $item, $data['event_types']),
            id: (string) $data['id'],
            status: (string) $data['status'],
            updatedAt: (string) $data['updated_at'],
            url: (string) $data['url'],
        );
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return array_filter([
            'created_at' => $this->createdAt,
            'event_types' => $this->eventTypes,
            'id' => $this->id,
            'status' => $this->status,
            'updated_at' => $this->updatedAt,
            'url' => $this->url,
        ], static fn (mixed $value): bool => $value !== null);
    }
}
