# Generated by Kaji. Do not edit.
from __future__ import annotations

from .auth_check_239ac9ff5448c146_part_000 import AuthCheckResourcePart000


class AuthCheckResource(AuthCheckResourcePart000):
    """Typed resource namespace exposed by :class:`Client`."""

    pass
