# Generated by Kaji. Do not edit.
from __future__ import annotations

from .contacts_17f458ee83d31930_part_000 import ContactsResourcePart000


class ContactsResource(ContactsResourcePart000):
    """Typed resource namespace exposed by :class:`Client`."""

    pass
