# Generated by Kaji. Do not edit.
from __future__ import annotations

from .events_dd63d0cec6bb7d04_part_000 import EventsResourcePart000


class EventsResource(EventsResourcePart000):
    """Typed resource namespace exposed by :class:`Client`."""

    pass
