# Generated by Kaji. Do not edit.
from __future__ import annotations

from typing import Any, Iterator



class EventsResourcePart000:
    """Bounded typed events resource operations."""

    def __init__(self, client: Any) -> None:
        self._client = client
    def track(self, *, body: TrackEventRequest) -> EventResponse:
        return self._client.track(body=body)

