# Generated by Kaji. Do not edit.
from __future__ import annotations

from .inbound_b1483ee0837d2696_part_000 import InboundResourcePart000


class InboundResource(InboundResourcePart000):
    """Typed resource namespace exposed by :class:`Client`."""

    pass
