# Generated by Kaji. Do not edit.
from __future__ import annotations

from typing import Any, Iterator



class SenderIdentitiesResourcePart000:
    """Bounded typed sender_identities resource operations."""

    def __init__(self, client: Any) -> None:
        self._client = client
    def list(self, *, limit: int | None = None) -> SenderIdentityListResponse:
        return self._client.list_sender_identities(limit=limit)

    def get_sender_identity(self, *, id: str) -> SenderIdentityResponse:
        return self._client.get_sender_identity(id=id)

