# Generated by Kaji. Do not edit.
from __future__ import annotations

from .sender_identities_bf7bc58d6d7b50c9_part_000 import SenderIdentitiesResourcePart000


class SenderIdentitiesResource(SenderIdentitiesResourcePart000):
    """Typed resource namespace exposed by :class:`Client`."""

    pass
