# Generated by Kaji. Do not edit.
from __future__ import annotations

from .sends_b9606f305089fe54_part_000 import SendsResourcePart000


class SendsResource(SendsResourcePart000):
    """Typed resource namespace exposed by :class:`Client`."""

    pass
