/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { ErrorResponse } from '../ErrorResponse.js'
import type { SendResponse } from '../SendResponse.js'

export type CancelPath = {
  send_id: string
}

export type CancelStatus200 = SendResponse

export type CancelStatus401 = ErrorResponse

export type CancelStatus403 = ErrorResponse

export type CancelStatus404 = ErrorResponse

export type CancelStatus409 = ErrorResponse

export type CancelStatus503 = ErrorResponse

export type CancelOptions = {
  body?: never
  path: CancelPath
  query?: never
  headers?: never
  cookie?: never
}

export type CancelResponses = {
  '200': CancelStatus200
  '401': CancelStatus401
  '403': CancelStatus403
  '404': CancelStatus404
  '409': CancelStatus409
  '503': CancelStatus503
}

/**
 * @description Union of all possible responses
 */
export type CancelResponse = CancelStatus200 | CancelStatus401 | CancelStatus403 | CancelStatus404 | CancelStatus409 | CancelStatus503
