/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { ErrorResponse } from '../ErrorResponse.js'
import type { SendResponse } from '../SendResponse.js'

export type GetPath = {
  send_id: string
}

export type GetStatus200 = SendResponse

export type GetStatus401 = ErrorResponse

export type GetStatus403 = ErrorResponse

export type GetStatus404 = ErrorResponse

export type GetStatus503 = ErrorResponse

export type GetOptions = {
  body?: never
  path: GetPath
  query?: never
  headers?: never
  cookie?: never
}

export type GetResponses = {
  '200': GetStatus200
  '401': GetStatus401
  '403': GetStatus403
  '404': GetStatus404
  '503': GetStatus503
}

/**
 * @description Union of all possible responses
 */
export type GetResponse = GetStatus200 | GetStatus401 | GetStatus403 | GetStatus404 | GetStatus503
