# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Resources.Crm.Chunk0000 do
  @moduledoc false

  alias RelevateSdk.{API, Client}

  @spec list_crm_lists(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def list_crm_lists(client, options \\ []), do: API.list_crm_lists(client, options)

  @spec create_crm_list(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def create_crm_list(client, options \\ []), do: API.create_crm_list(client, options)

  @spec delete_crm_list(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def delete_crm_list(client, options \\ []), do: API.delete_crm_list(client, options)

  @spec get_crm_list(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def get_crm_list(client, options \\ []), do: API.get_crm_list(client, options)

  @spec update_crm_list(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def update_crm_list(client, options \\ []), do: API.update_crm_list(client, options)

  @spec list_crm_list_attributes(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def list_crm_list_attributes(client, options \\ []), do: API.list_crm_list_attributes(client, options)

  @spec create_crm_list_attribute(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def create_crm_list_attribute(client, options \\ []), do: API.create_crm_list_attribute(client, options)

  @spec delete_crm_list_attribute(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def delete_crm_list_attribute(client, options \\ []), do: API.delete_crm_list_attribute(client, options)

  @spec update_crm_list_attribute(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def update_crm_list_attribute(client, options \\ []), do: API.update_crm_list_attribute(client, options)

  @spec list_crm_list_entries(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def list_crm_list_entries(client, options \\ []), do: API.list_crm_list_entries(client, options)

  @spec create_crm_list_entry(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def create_crm_list_entry(client, options \\ []), do: API.create_crm_list_entry(client, options)

  @spec delete_crm_list_entry(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def delete_crm_list_entry(client, options \\ []), do: API.delete_crm_list_entry(client, options)

  @spec get_crm_list_entry(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def get_crm_list_entry(client, options \\ []), do: API.get_crm_list_entry(client, options)

  @spec update_crm_list_entry(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def update_crm_list_entry(client, options \\ []), do: API.update_crm_list_entry(client, options)

  @spec delete_crm_note(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def delete_crm_note(client, options \\ []), do: API.delete_crm_note(client, options)

  @spec get_crm_note(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def get_crm_note(client, options \\ []), do: API.get_crm_note(client, options)

  @spec update_crm_note(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def update_crm_note(client, options \\ []), do: API.update_crm_note(client, options)

  @spec list_crm_objects(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def list_crm_objects(client, options \\ []), do: API.list_crm_objects(client, options)

  @spec create_crm_object(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def create_crm_object(client, options \\ []), do: API.create_crm_object(client, options)

  @spec delete_crm_object(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def delete_crm_object(client, options \\ []), do: API.delete_crm_object(client, options)

  @spec get_crm_object(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def get_crm_object(client, options \\ []), do: API.get_crm_object(client, options)

  @spec update_crm_object(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def update_crm_object(client, options \\ []), do: API.update_crm_object(client, options)

  @spec list_crm_object_attributes(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def list_crm_object_attributes(client, options \\ []), do: API.list_crm_object_attributes(client, options)

  @spec create_crm_object_attribute(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def create_crm_object_attribute(client, options \\ []), do: API.create_crm_object_attribute(client, options)

  @spec delete_crm_object_attribute(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def delete_crm_object_attribute(client, options \\ []), do: API.delete_crm_object_attribute(client, options)
end
