/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { ErrorResponse } from '../ErrorResponse.js'
import type { HookUpdate } from '../HookUpdate.js'
import type { WebhookResponse } from '../WebhookResponse.js'

export type UpdateWebhookPath = {
  webhook_id: string
}

export type UpdateWebhookStatus200 = WebhookResponse

export type UpdateWebhookStatus401 = ErrorResponse

export type UpdateWebhookStatus404 = ErrorResponse

export type UpdateWebhookStatus422 = ErrorResponse

export type UpdateWebhookStatus503 = ErrorResponse

export type UpdateWebhookBody = HookUpdate

export type UpdateWebhookOptions = {
  body: UpdateWebhookBody
  path: UpdateWebhookPath
  query?: never
  headers?: never
  cookie?: never
}

export type UpdateWebhookResponses = {
  '200': UpdateWebhookStatus200
  '401': UpdateWebhookStatus401
  '404': UpdateWebhookStatus404
  '422': UpdateWebhookStatus422
  '503': UpdateWebhookStatus503
}

/**
 * @description Union of all possible responses
 */
export type UpdateWebhookResponse = UpdateWebhookStatus200 | UpdateWebhookStatus401 | UpdateWebhookStatus404 | UpdateWebhookStatus422 | UpdateWebhookStatus503
