# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Resources.AuthCheck do
  @moduledoc "Resource-namespaced operations for AuthCheck."


  alias RelevateSdk.Resources.AuthCheck.Chunk0000
  def auth_check(client, options \\ []), do: Chunk0000.auth_check(client, options)
end
