# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Resources.Contacts do
  @moduledoc "Resource-namespaced operations for Contacts."


  alias RelevateSdk.Resources.Contacts.Chunk0000
  def list_contacts(client, options \\ []), do: Chunk0000.list_contacts(client, options)
  def create_contact(client, options \\ []), do: Chunk0000.create_contact(client, options)
  def query_contacts(client, options \\ []), do: Chunk0000.query_contacts(client, options)
  def get_contact(client, options \\ []), do: Chunk0000.get_contact(client, options)
  def update_contact(client, options \\ []), do: Chunk0000.update_contact(client, options)
end
