# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Resources.Events do
  @moduledoc "Resource-namespaced operations for Events."


  alias RelevateSdk.Resources.Events.Chunk0000
  def track(client, options \\ []), do: Chunk0000.track(client, options)
end
