# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Resources.SenderIdentities do
  @moduledoc "Resource-namespaced operations for SenderIdentities."


  alias RelevateSdk.Resources.SenderIdentities.Chunk0000
  def list_sender_identities(client, options \\ []), do: Chunk0000.list_sender_identities(client, options)
  def get_sender_identity(client, options \\ []), do: Chunk0000.get_sender_identity(client, options)
end
