/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmApiError } from '../CrmApiError.js'
import type { CrmRecordResponse } from '../CrmRecordResponse.js'

export type ArchiveCrmRecordPath = {
  record_id: string
}

export type ArchiveCrmRecordStatus200 = CrmRecordResponse

export type ArchiveCrmRecordStatus400 = CrmApiError

export type ArchiveCrmRecordStatus401 = CrmApiError

export type ArchiveCrmRecordStatus403 = CrmApiError

export type ArchiveCrmRecordStatus404 = CrmApiError

export type ArchiveCrmRecordStatus409 = CrmApiError

export type ArchiveCrmRecordStatus413 = CrmApiError

export type ArchiveCrmRecordStatus415 = CrmApiError

export type ArchiveCrmRecordStatus503 = CrmApiError

export type ArchiveCrmRecordOptions = {
  body?: never
  path: ArchiveCrmRecordPath
  query?: never
  headers?: never
  cookie?: never
}

export type ArchiveCrmRecordResponses = {
  '200': ArchiveCrmRecordStatus200
  '400': ArchiveCrmRecordStatus400
  '401': ArchiveCrmRecordStatus401
  '403': ArchiveCrmRecordStatus403
  '404': ArchiveCrmRecordStatus404
  '409': ArchiveCrmRecordStatus409
  '413': ArchiveCrmRecordStatus413
  '415': ArchiveCrmRecordStatus415
  '503': ArchiveCrmRecordStatus503
}

/**
 * @description Union of all possible responses
 */
export type ArchiveCrmRecordResponse = ArchiveCrmRecordStatus200 | ArchiveCrmRecordStatus400 | ArchiveCrmRecordStatus401 | ArchiveCrmRecordStatus403 | ArchiveCrmRecordStatus404 | ArchiveCrmRecordStatus409 | ArchiveCrmRecordStatus413 | ArchiveCrmRecordStatus415 | ArchiveCrmRecordStatus503
