/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmApiError } from '../CrmApiError.js'
import type { CrmRecordCreate } from '../CrmRecordCreate.js'
import type { CrmRecordResponse } from '../CrmRecordResponse.js'

export type CreateCrmRecordPath = {
  object: string
}

export type CreateCrmRecordStatus201 = CrmRecordResponse

export type CreateCrmRecordStatus400 = CrmApiError

export type CreateCrmRecordStatus401 = CrmApiError

export type CreateCrmRecordStatus403 = CrmApiError

export type CreateCrmRecordStatus404 = CrmApiError

export type CreateCrmRecordStatus409 = CrmApiError

export type CreateCrmRecordStatus413 = CrmApiError

export type CreateCrmRecordStatus415 = CrmApiError

export type CreateCrmRecordStatus503 = CrmApiError

export type CreateCrmRecordBody = CrmRecordCreate

export type CreateCrmRecordOptions = {
  body: CreateCrmRecordBody
  path: CreateCrmRecordPath
  query?: never
  headers?: never
  cookie?: never
}

export type CreateCrmRecordResponses = {
  '201': CreateCrmRecordStatus201
  '400': CreateCrmRecordStatus400
  '401': CreateCrmRecordStatus401
  '403': CreateCrmRecordStatus403
  '404': CreateCrmRecordStatus404
  '409': CreateCrmRecordStatus409
  '413': CreateCrmRecordStatus413
  '415': CreateCrmRecordStatus415
  '503': CreateCrmRecordStatus503
}

/**
 * @description Union of all possible responses
 */
export type CreateCrmRecordResponse = CreateCrmRecordStatus201 | CreateCrmRecordStatus400 | CreateCrmRecordStatus401 | CreateCrmRecordStatus403 | CreateCrmRecordStatus404 | CreateCrmRecordStatus409 | CreateCrmRecordStatus413 | CreateCrmRecordStatus415 | CreateCrmRecordStatus503
