/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmApiError } from '../CrmApiError.js'
import type { CrmTask } from '../CrmTask.js'
import type { CrmTaskCreate } from '../CrmTaskCreate.js'

export type CreateCrmTaskPath = {
  record_id: string
}

export type CreateCrmTaskStatus201 = {
  api_version: string
  data: CrmTask
}

export type CreateCrmTaskStatus400 = CrmApiError

export type CreateCrmTaskStatus401 = CrmApiError

export type CreateCrmTaskStatus403 = CrmApiError

export type CreateCrmTaskStatus404 = CrmApiError

export type CreateCrmTaskStatus409 = CrmApiError

export type CreateCrmTaskStatus413 = CrmApiError

export type CreateCrmTaskStatus415 = CrmApiError

export type CreateCrmTaskStatus503 = CrmApiError

export type CreateCrmTaskBody = CrmTaskCreate

export type CreateCrmTaskOptions = {
  body: CreateCrmTaskBody
  path: CreateCrmTaskPath
  query?: never
  headers?: never
  cookie?: never
}

export type CreateCrmTaskResponses = {
  '201': CreateCrmTaskStatus201
  '400': CreateCrmTaskStatus400
  '401': CreateCrmTaskStatus401
  '403': CreateCrmTaskStatus403
  '404': CreateCrmTaskStatus404
  '409': CreateCrmTaskStatus409
  '413': CreateCrmTaskStatus413
  '415': CreateCrmTaskStatus415
  '503': CreateCrmTaskStatus503
}

/**
 * @description Union of all possible responses
 */
export type CreateCrmTaskResponse = CreateCrmTaskStatus201 | CreateCrmTaskStatus400 | CreateCrmTaskStatus401 | CreateCrmTaskStatus403 | CreateCrmTaskStatus404 | CreateCrmTaskStatus409 | CreateCrmTaskStatus413 | CreateCrmTaskStatus415 | CreateCrmTaskStatus503
