/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmApiError } from '../CrmApiError.js'
import type { CrmMetadataObjectResponse } from '../CrmMetadataObjectResponse.js'
import type { CrmObjectCreate } from '../CrmObjectCreate.js'

export type CreateCrmObjectStatus201 = CrmMetadataObjectResponse

export type CreateCrmObjectStatus400 = CrmApiError

export type CreateCrmObjectStatus401 = CrmApiError

export type CreateCrmObjectStatus403 = CrmApiError

export type CreateCrmObjectStatus404 = CrmApiError

export type CreateCrmObjectStatus409 = CrmApiError

export type CreateCrmObjectStatus413 = CrmApiError

export type CreateCrmObjectStatus415 = CrmApiError

export type CreateCrmObjectStatus503 = CrmApiError

export type CreateCrmObjectBody = CrmObjectCreate

export type CreateCrmObjectOptions = {
  body: CreateCrmObjectBody
  path?: never
  query?: never
  headers?: never
  cookie?: never
}

export type CreateCrmObjectResponses = {
  '201': CreateCrmObjectStatus201
  '400': CreateCrmObjectStatus400
  '401': CreateCrmObjectStatus401
  '403': CreateCrmObjectStatus403
  '404': CreateCrmObjectStatus404
  '409': CreateCrmObjectStatus409
  '413': CreateCrmObjectStatus413
  '415': CreateCrmObjectStatus415
  '503': CreateCrmObjectStatus503
}

/**
 * @description Union of all possible responses
 */
export type CreateCrmObjectResponse = CreateCrmObjectStatus201 | CreateCrmObjectStatus400 | CreateCrmObjectStatus401 | CreateCrmObjectStatus403 | CreateCrmObjectStatus404 | CreateCrmObjectStatus409 | CreateCrmObjectStatus413 | CreateCrmObjectStatus415 | CreateCrmObjectStatus503
