/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmApiError } from '../CrmApiError.js'
import type { CrmCreateListEntry } from '../CrmCreateListEntry.js'
import type { CrmListEntryResponse } from '../CrmListEntryResponse.js'

export type CreateCrmListEntryPath = {
  list: string
}

export type CreateCrmListEntryStatus201 = CrmListEntryResponse

export type CreateCrmListEntryStatus400 = CrmApiError

export type CreateCrmListEntryStatus401 = CrmApiError

export type CreateCrmListEntryStatus403 = CrmApiError

export type CreateCrmListEntryStatus404 = CrmApiError

export type CreateCrmListEntryStatus409 = CrmApiError

export type CreateCrmListEntryStatus413 = CrmApiError

export type CreateCrmListEntryStatus415 = CrmApiError

export type CreateCrmListEntryStatus503 = CrmApiError

export type CreateCrmListEntryBody = CrmCreateListEntry

export type CreateCrmListEntryOptions = {
  body: CreateCrmListEntryBody
  path: CreateCrmListEntryPath
  query?: never
  headers?: never
  cookie?: never
}

export type CreateCrmListEntryResponses = {
  '201': CreateCrmListEntryStatus201
  '400': CreateCrmListEntryStatus400
  '401': CreateCrmListEntryStatus401
  '403': CreateCrmListEntryStatus403
  '404': CreateCrmListEntryStatus404
  '409': CreateCrmListEntryStatus409
  '413': CreateCrmListEntryStatus413
  '415': CreateCrmListEntryStatus415
  '503': CreateCrmListEntryStatus503
}

/**
 * @description Union of all possible responses
 */
export type CreateCrmListEntryResponse = CreateCrmListEntryStatus201 | CreateCrmListEntryStatus400 | CreateCrmListEntryStatus401 | CreateCrmListEntryStatus403 | CreateCrmListEntryStatus404 | CreateCrmListEntryStatus409 | CreateCrmListEntryStatus413 | CreateCrmListEntryStatus415 | CreateCrmListEntryStatus503
