/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmApiError } from '../CrmApiError.js'
import type { CrmMetadataDeleted } from '../CrmMetadataDeleted.js'
import type { CrmObjectDelete } from '../CrmObjectDelete.js'

export type DeleteCrmObjectPath = {
  object: string
}

export type DeleteCrmObjectStatus200 = CrmMetadataDeleted

export type DeleteCrmObjectStatus400 = CrmApiError

export type DeleteCrmObjectStatus401 = CrmApiError

export type DeleteCrmObjectStatus403 = CrmApiError

export type DeleteCrmObjectStatus404 = CrmApiError

export type DeleteCrmObjectStatus409 = CrmApiError

export type DeleteCrmObjectStatus413 = CrmApiError

export type DeleteCrmObjectStatus415 = CrmApiError

export type DeleteCrmObjectStatus503 = CrmApiError

export type DeleteCrmObjectBody = CrmObjectDelete

export type DeleteCrmObjectOptions = {
  body: DeleteCrmObjectBody
  path: DeleteCrmObjectPath
  query?: never
  headers?: never
  cookie?: never
}

export type DeleteCrmObjectResponses = {
  '200': DeleteCrmObjectStatus200
  '400': DeleteCrmObjectStatus400
  '401': DeleteCrmObjectStatus401
  '403': DeleteCrmObjectStatus403
  '404': DeleteCrmObjectStatus404
  '409': DeleteCrmObjectStatus409
  '413': DeleteCrmObjectStatus413
  '415': DeleteCrmObjectStatus415
  '503': DeleteCrmObjectStatus503
}

/**
 * @description Union of all possible responses
 */
export type DeleteCrmObjectResponse = DeleteCrmObjectStatus200 | DeleteCrmObjectStatus400 | DeleteCrmObjectStatus401 | DeleteCrmObjectStatus403 | DeleteCrmObjectStatus404 | DeleteCrmObjectStatus409 | DeleteCrmObjectStatus413 | DeleteCrmObjectStatus415 | DeleteCrmObjectStatus503
