/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmApiError } from '../CrmApiError.js'
import type { CrmListDeletionResponse } from '../CrmListDeletionResponse.js'

export type DeleteCrmListPath = {
  list: string
}

export type DeleteCrmListStatus200 = CrmListDeletionResponse

export type DeleteCrmListStatus400 = CrmApiError

export type DeleteCrmListStatus401 = CrmApiError

export type DeleteCrmListStatus403 = CrmApiError

export type DeleteCrmListStatus404 = CrmApiError

export type DeleteCrmListStatus409 = CrmApiError

export type DeleteCrmListStatus413 = CrmApiError

export type DeleteCrmListStatus415 = CrmApiError

export type DeleteCrmListStatus503 = CrmApiError

export type DeleteCrmListOptions = {
  body?: never
  path: DeleteCrmListPath
  query?: never
  headers?: never
  cookie?: never
}

export type DeleteCrmListResponses = {
  '200': DeleteCrmListStatus200
  '400': DeleteCrmListStatus400
  '401': DeleteCrmListStatus401
  '403': DeleteCrmListStatus403
  '404': DeleteCrmListStatus404
  '409': DeleteCrmListStatus409
  '413': DeleteCrmListStatus413
  '415': DeleteCrmListStatus415
  '503': DeleteCrmListStatus503
}

/**
 * @description Union of all possible responses
 */
export type DeleteCrmListResponse = DeleteCrmListStatus200 | DeleteCrmListStatus400 | DeleteCrmListStatus401 | DeleteCrmListStatus403 | DeleteCrmListStatus404 | DeleteCrmListStatus409 | DeleteCrmListStatus413 | DeleteCrmListStatus415 | DeleteCrmListStatus503
