/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmApiError } from '../CrmApiError.js'
import type { CrmDeletedNote } from '../CrmDeletedNote.js'

export type DeleteCrmNotePath = {
  note_id: string
}

export type DeleteCrmNoteStatus200 = {
  api_version: string
  data: CrmDeletedNote
}

export type DeleteCrmNoteStatus400 = CrmApiError

export type DeleteCrmNoteStatus401 = CrmApiError

export type DeleteCrmNoteStatus403 = CrmApiError

export type DeleteCrmNoteStatus404 = CrmApiError

export type DeleteCrmNoteStatus409 = CrmApiError

export type DeleteCrmNoteStatus413 = CrmApiError

export type DeleteCrmNoteStatus415 = CrmApiError

export type DeleteCrmNoteStatus503 = CrmApiError

export type DeleteCrmNoteOptions = {
  body?: never
  path: DeleteCrmNotePath
  query?: never
  headers?: never
  cookie?: never
}

export type DeleteCrmNoteResponses = {
  '200': DeleteCrmNoteStatus200
  '400': DeleteCrmNoteStatus400
  '401': DeleteCrmNoteStatus401
  '403': DeleteCrmNoteStatus403
  '404': DeleteCrmNoteStatus404
  '409': DeleteCrmNoteStatus409
  '413': DeleteCrmNoteStatus413
  '415': DeleteCrmNoteStatus415
  '503': DeleteCrmNoteStatus503
}

/**
 * @description Union of all possible responses
 */
export type DeleteCrmNoteResponse = DeleteCrmNoteStatus200 | DeleteCrmNoteStatus400 | DeleteCrmNoteStatus401 | DeleteCrmNoteStatus403 | DeleteCrmNoteStatus404 | DeleteCrmNoteStatus409 | DeleteCrmNoteStatus413 | DeleteCrmNoteStatus415 | DeleteCrmNoteStatus503
