/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmApiError } from '../CrmApiError.js'
import type { CrmNote } from '../CrmNote.js'

export type GetCrmNotePath = {
  note_id: string
}

export type GetCrmNoteStatus200 = {
  api_version: string
  data: CrmNote
}

export type GetCrmNoteStatus400 = CrmApiError

export type GetCrmNoteStatus401 = CrmApiError

export type GetCrmNoteStatus403 = CrmApiError

export type GetCrmNoteStatus404 = CrmApiError

export type GetCrmNoteStatus409 = CrmApiError

export type GetCrmNoteStatus413 = CrmApiError

export type GetCrmNoteStatus415 = CrmApiError

export type GetCrmNoteStatus503 = CrmApiError

export type GetCrmNoteOptions = {
  body?: never
  path: GetCrmNotePath
  query?: never
  headers?: never
  cookie?: never
}

export type GetCrmNoteResponses = {
  '200': GetCrmNoteStatus200
  '400': GetCrmNoteStatus400
  '401': GetCrmNoteStatus401
  '403': GetCrmNoteStatus403
  '404': GetCrmNoteStatus404
  '409': GetCrmNoteStatus409
  '413': GetCrmNoteStatus413
  '415': GetCrmNoteStatus415
  '503': GetCrmNoteStatus503
}

/**
 * @description Union of all possible responses
 */
export type GetCrmNoteResponse = GetCrmNoteStatus200 | GetCrmNoteStatus400 | GetCrmNoteStatus401 | GetCrmNoteStatus403 | GetCrmNoteStatus404 | GetCrmNoteStatus409 | GetCrmNoteStatus413 | GetCrmNoteStatus415 | GetCrmNoteStatus503
