/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmApiError } from '../CrmApiError.js'
import type { CrmObjectDiscovery } from '../CrmObjectDiscovery.js'

export type ListCrmObjectsQuery = {
  limit?: number
  after?: string
  include_disabled?: boolean
}

export type ListCrmObjectsStatus200 = {
  api_version?: string
  data?: CrmObjectDiscovery[]
  page?: object
}

export type ListCrmObjectsStatus400 = CrmApiError

export type ListCrmObjectsStatus401 = CrmApiError

export type ListCrmObjectsStatus403 = CrmApiError

export type ListCrmObjectsStatus404 = CrmApiError

export type ListCrmObjectsStatus409 = CrmApiError

export type ListCrmObjectsStatus413 = CrmApiError

export type ListCrmObjectsStatus415 = CrmApiError

export type ListCrmObjectsStatus503 = CrmApiError

export type ListCrmObjectsOptions = {
  body?: never
  path?: never
  query?: ListCrmObjectsQuery
  headers?: never
  cookie?: never
}

export type ListCrmObjectsResponses = {
  '200': ListCrmObjectsStatus200
  '400': ListCrmObjectsStatus400
  '401': ListCrmObjectsStatus401
  '403': ListCrmObjectsStatus403
  '404': ListCrmObjectsStatus404
  '409': ListCrmObjectsStatus409
  '413': ListCrmObjectsStatus413
  '415': ListCrmObjectsStatus415
  '503': ListCrmObjectsStatus503
}

/**
 * @description Union of all possible responses
 */
export type ListCrmObjectsResponse = ListCrmObjectsStatus200 | ListCrmObjectsStatus400 | ListCrmObjectsStatus401 | ListCrmObjectsStatus403 | ListCrmObjectsStatus404 | ListCrmObjectsStatus409 | ListCrmObjectsStatus413 | ListCrmObjectsStatus415 | ListCrmObjectsStatus503
