/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmApiError } from '../CrmApiError.js'
import type { CrmRecord } from '../CrmRecord.js'

export type ListCrmRecordsPath = {
  object: string
}

export type ListCrmRecordsQuery = {
  limit?: number
  after?: string
  external_id?: string
  include_archived?: boolean
}

export type ListCrmRecordsStatus200 = {
  api_version?: string
  data?: CrmRecord[]
  page?: {
  limit?: number
  next_cursor?: string | null
}
}

export type ListCrmRecordsStatus400 = CrmApiError

export type ListCrmRecordsStatus401 = CrmApiError

export type ListCrmRecordsStatus403 = CrmApiError

export type ListCrmRecordsStatus404 = CrmApiError

export type ListCrmRecordsStatus409 = CrmApiError

export type ListCrmRecordsStatus413 = CrmApiError

export type ListCrmRecordsStatus415 = CrmApiError

export type ListCrmRecordsStatus503 = CrmApiError

export type ListCrmRecordsOptions = {
  body?: never
  path: ListCrmRecordsPath
  query?: ListCrmRecordsQuery
  headers?: never
  cookie?: never
}

export type ListCrmRecordsResponses = {
  '200': ListCrmRecordsStatus200
  '400': ListCrmRecordsStatus400
  '401': ListCrmRecordsStatus401
  '403': ListCrmRecordsStatus403
  '404': ListCrmRecordsStatus404
  '409': ListCrmRecordsStatus409
  '413': ListCrmRecordsStatus413
  '415': ListCrmRecordsStatus415
  '503': ListCrmRecordsStatus503
}

/**
 * @description Union of all possible responses
 */
export type ListCrmRecordsResponse = ListCrmRecordsStatus200 | ListCrmRecordsStatus400 | ListCrmRecordsStatus401 | ListCrmRecordsStatus403 | ListCrmRecordsStatus404 | ListCrmRecordsStatus409 | ListCrmRecordsStatus413 | ListCrmRecordsStatus415 | ListCrmRecordsStatus503
