/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmApiError } from '../CrmApiError.js'
import type { CrmMetadataAttributesResponse } from '../CrmMetadataAttributesResponse.js'

export type ListCrmObjectAttributesPath = {
  object: string
}

export type ListCrmObjectAttributesStatus200 = CrmMetadataAttributesResponse

export type ListCrmObjectAttributesStatus400 = CrmApiError

export type ListCrmObjectAttributesStatus401 = CrmApiError

export type ListCrmObjectAttributesStatus403 = CrmApiError

export type ListCrmObjectAttributesStatus404 = CrmApiError

export type ListCrmObjectAttributesStatus409 = CrmApiError

export type ListCrmObjectAttributesStatus413 = CrmApiError

export type ListCrmObjectAttributesStatus415 = CrmApiError

export type ListCrmObjectAttributesStatus503 = CrmApiError

export type ListCrmObjectAttributesOptions = {
  body?: never
  path: ListCrmObjectAttributesPath
  query?: never
  headers?: never
  cookie?: never
}

export type ListCrmObjectAttributesResponses = {
  '200': ListCrmObjectAttributesStatus200
  '400': ListCrmObjectAttributesStatus400
  '401': ListCrmObjectAttributesStatus401
  '403': ListCrmObjectAttributesStatus403
  '404': ListCrmObjectAttributesStatus404
  '409': ListCrmObjectAttributesStatus409
  '413': ListCrmObjectAttributesStatus413
  '415': ListCrmObjectAttributesStatus415
  '503': ListCrmObjectAttributesStatus503
}

/**
 * @description Union of all possible responses
 */
export type ListCrmObjectAttributesResponse = ListCrmObjectAttributesStatus200 | ListCrmObjectAttributesStatus400 | ListCrmObjectAttributesStatus401 | ListCrmObjectAttributesStatus403 | ListCrmObjectAttributesStatus404 | ListCrmObjectAttributesStatus409 | ListCrmObjectAttributesStatus413 | ListCrmObjectAttributesStatus415 | ListCrmObjectAttributesStatus503
