/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmApiError } from '../CrmApiError.js'
import type { CrmContentPage } from '../CrmContentPage.js'
import type { CrmTask } from '../CrmTask.js'

export type ListCrmTasksPath = {
  record_id: string
}

export type ListCrmTasksQuery = {
  limit?: number
  after?: string
}

export type ListCrmTasksStatus200 = {
  api_version: string
  data: CrmTask[]
  page: CrmContentPage
}

export type ListCrmTasksStatus400 = CrmApiError

export type ListCrmTasksStatus401 = CrmApiError

export type ListCrmTasksStatus403 = CrmApiError

export type ListCrmTasksStatus404 = CrmApiError

export type ListCrmTasksStatus409 = CrmApiError

export type ListCrmTasksStatus413 = CrmApiError

export type ListCrmTasksStatus415 = CrmApiError

export type ListCrmTasksStatus503 = CrmApiError

export type ListCrmTasksOptions = {
  body?: never
  path: ListCrmTasksPath
  query?: ListCrmTasksQuery
  headers?: never
  cookie?: never
}

export type ListCrmTasksResponses = {
  '200': ListCrmTasksStatus200
  '400': ListCrmTasksStatus400
  '401': ListCrmTasksStatus401
  '403': ListCrmTasksStatus403
  '404': ListCrmTasksStatus404
  '409': ListCrmTasksStatus409
  '413': ListCrmTasksStatus413
  '415': ListCrmTasksStatus415
  '503': ListCrmTasksStatus503
}

/**
 * @description Union of all possible responses
 */
export type ListCrmTasksResponse = ListCrmTasksStatus200 | ListCrmTasksStatus400 | ListCrmTasksStatus401 | ListCrmTasksStatus403 | ListCrmTasksStatus404 | ListCrmTasksStatus409 | ListCrmTasksStatus413 | ListCrmTasksStatus415 | ListCrmTasksStatus503
