/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmApiError } from '../CrmApiError.js'
import type { CrmListEntryResponse } from '../CrmListEntryResponse.js'
import type { CrmUpdateListEntry } from '../CrmUpdateListEntry.js'

export type UpdateCrmListEntryPath = {
  list: string
  entry: string
}

export type UpdateCrmListEntryStatus200 = CrmListEntryResponse

export type UpdateCrmListEntryStatus400 = CrmApiError

export type UpdateCrmListEntryStatus401 = CrmApiError

export type UpdateCrmListEntryStatus403 = CrmApiError

export type UpdateCrmListEntryStatus404 = CrmApiError

export type UpdateCrmListEntryStatus409 = CrmApiError

export type UpdateCrmListEntryStatus413 = CrmApiError

export type UpdateCrmListEntryStatus415 = CrmApiError

export type UpdateCrmListEntryStatus503 = CrmApiError

export type UpdateCrmListEntryBody = CrmUpdateListEntry

export type UpdateCrmListEntryOptions = {
  body: UpdateCrmListEntryBody
  path: UpdateCrmListEntryPath
  query?: never
  headers?: never
  cookie?: never
}

export type UpdateCrmListEntryResponses = {
  '200': UpdateCrmListEntryStatus200
  '400': UpdateCrmListEntryStatus400
  '401': UpdateCrmListEntryStatus401
  '403': UpdateCrmListEntryStatus403
  '404': UpdateCrmListEntryStatus404
  '409': UpdateCrmListEntryStatus409
  '413': UpdateCrmListEntryStatus413
  '415': UpdateCrmListEntryStatus415
  '503': UpdateCrmListEntryStatus503
}

/**
 * @description Union of all possible responses
 */
export type UpdateCrmListEntryResponse = UpdateCrmListEntryStatus200 | UpdateCrmListEntryStatus400 | UpdateCrmListEntryStatus401 | UpdateCrmListEntryStatus403 | UpdateCrmListEntryStatus404 | UpdateCrmListEntryStatus409 | UpdateCrmListEntryStatus413 | UpdateCrmListEntryStatus415 | UpdateCrmListEntryStatus503
