/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmApiError } from '../CrmApiError.js'
import type { CrmNote } from '../CrmNote.js'
import type { CrmNoteWrite } from '../CrmNoteWrite.js'

export type UpdateCrmNotePath = {
  note_id: string
}

export type UpdateCrmNoteStatus200 = {
  api_version: string
  data: CrmNote
}

export type UpdateCrmNoteStatus400 = CrmApiError

export type UpdateCrmNoteStatus401 = CrmApiError

export type UpdateCrmNoteStatus403 = CrmApiError

export type UpdateCrmNoteStatus404 = CrmApiError

export type UpdateCrmNoteStatus409 = CrmApiError

export type UpdateCrmNoteStatus413 = CrmApiError

export type UpdateCrmNoteStatus415 = CrmApiError

export type UpdateCrmNoteStatus503 = CrmApiError

export type UpdateCrmNoteBody = CrmNoteWrite

export type UpdateCrmNoteOptions = {
  body: UpdateCrmNoteBody
  path: UpdateCrmNotePath
  query?: never
  headers?: never
  cookie?: never
}

export type UpdateCrmNoteResponses = {
  '200': UpdateCrmNoteStatus200
  '400': UpdateCrmNoteStatus400
  '401': UpdateCrmNoteStatus401
  '403': UpdateCrmNoteStatus403
  '404': UpdateCrmNoteStatus404
  '409': UpdateCrmNoteStatus409
  '413': UpdateCrmNoteStatus413
  '415': UpdateCrmNoteStatus415
  '503': UpdateCrmNoteStatus503
}

/**
 * @description Union of all possible responses
 */
export type UpdateCrmNoteResponse = UpdateCrmNoteStatus200 | UpdateCrmNoteStatus400 | UpdateCrmNoteStatus401 | UpdateCrmNoteStatus403 | UpdateCrmNoteStatus404 | UpdateCrmNoteStatus409 | UpdateCrmNoteStatus413 | UpdateCrmNoteStatus415 | UpdateCrmNoteStatus503
