package app.relevate.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;
import java.util.Map;

// Generated by Kaji. Do not edit.

@JsonIgnoreProperties(ignoreUnknown = true)
public record ContactQuery(
        @JsonProperty("limit") Long limit,
        @JsonProperty("marketing_status") String marketingStatus,
        @JsonProperty("offset") Long offset,
        @JsonProperty("order") String order,
        @JsonProperty("order_by") String orderBy,
        @JsonProperty("search") String search,
        @JsonProperty("status") String status
) {}
