package app.relevate.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;
import java.util.Map;

// Generated by Kaji. Do not edit.

@JsonIgnoreProperties(ignoreUnknown = true)
public record CrmAttributeCreate(
        @JsonProperty("currency_code") String currencyCode,
        @JsonProperty("expression") String expression,
        @JsonProperty("key") String key,
        @JsonProperty("multiple") Boolean multiple,
        @JsonProperty("name") String name,
        @JsonProperty("options") List<String> options,
        @JsonProperty("required") Boolean required,
        @JsonProperty("target_object_id") String targetObjectId,
        @JsonProperty("type") String type
) {}
