package app.relevate.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;
import java.util.Map;

// Generated by Kaji. Do not edit.

@JsonIgnoreProperties(ignoreUnknown = true)
public record CrmActivity(
        @JsonProperty("actor_id") String actorId,
        @JsonProperty("created_at") String createdAt,
        @JsonProperty("id") String id,
        @JsonProperty("metadata") JsonNode metadata,
        @JsonProperty("record_id") String recordId,
        @JsonProperty("summary") String summary,
        @JsonProperty("type") String type
) {}
