package app.relevate.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;
import java.util.Map;

// Generated by Kaji. Do not edit.

@JsonIgnoreProperties(ignoreUnknown = true)
public record CrmListsPage(
        @JsonProperty("api_version") String apiVersion,
        @JsonProperty("data") List<CrmList> data,
        @JsonProperty("page") JsonNode page
) {}
