package app.relevate.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;
import java.util.Map;

// Generated by Kaji. Do not edit.

@JsonIgnoreProperties(ignoreUnknown = true)
public record CrmNote(
        @JsonProperty("author_id") String authorId,
        @JsonProperty("body") String body,
        @JsonProperty("content") JsonNode content,
        @JsonProperty("created_at") String createdAt,
        @JsonProperty("deleted_at") String deletedAt,
        @JsonProperty("id") String id,
        @JsonProperty("mention_records") List<JsonNode> mentionRecords,
        @JsonProperty("mentions") List<CrmNoteMention> mentions,
        @JsonProperty("record_id") String recordId,
        @JsonProperty("title") String title,
        @JsonProperty("updated_at") String updatedAt
) {}
