package app.relevate.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;
import java.util.Map;

// Generated by Kaji. Do not edit.

@JsonIgnoreProperties(ignoreUnknown = true)
public record CrmObjectDiscovery(
        @JsonProperty("created_at") String createdAt,
        @JsonProperty("enabled") Boolean enabled,
        @JsonProperty("icon") String icon,
        @JsonProperty("id") String id,
        @JsonProperty("is_system") Boolean isSystem,
        @JsonProperty("name") String name,
        @JsonProperty("slug") String slug,
        @JsonProperty("updated_at") String updatedAt
) {}
