package app.relevate.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;
import java.util.Map;

// Generated by Kaji. Do not edit.

@JsonIgnoreProperties(ignoreUnknown = true)
public record CrmRecord(
        @JsonProperty("archived_at") String archivedAt,
        @JsonProperty("created_at") String createdAt,
        @JsonProperty("display_name") String displayName,
        @JsonProperty("external_id") String externalId,
        @JsonProperty("id") String id,
        @JsonProperty("object_id") String objectId,
        @JsonProperty("updated_at") String updatedAt,
        @JsonProperty("values") JsonNode values
) {}
