package app.relevate.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;
import java.util.Map;

// Generated by Kaji. Do not edit.

@JsonIgnoreProperties(ignoreUnknown = true)
public record CrmRecordPatch(
        @JsonProperty("archived") Boolean archived,
        @JsonProperty("display_name") String displayName,
        @JsonProperty("values") JsonNode values
) {}
