package app.relevate.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;
import java.util.Map;

// Generated by Kaji. Do not edit.

@JsonIgnoreProperties(ignoreUnknown = true)
public record SendRequest(
        @JsonProperty("html_body") String htmlBody,
        @JsonProperty("message_class") String messageClass,
        @JsonProperty("purpose_id") String purposeId,
        @JsonProperty("recipients") List<RecipientInput> recipients,
        @JsonProperty("reference") String reference,
        @JsonProperty("reply_to") String replyTo,
        @JsonProperty("request_key") String requestKey,
        @JsonProperty("sender_identity_id") String senderIdentityId,
        @JsonProperty("subject") String subject,
        @JsonProperty("text_body") String textBody
) {}
