package app.relevate.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;
import java.util.Map;

// Generated by Kaji. Do not edit.

@JsonIgnoreProperties(ignoreUnknown = true)
public record SenderIdentity(
        @JsonProperty("address") String address,
        @JsonProperty("created_at") String createdAt,
        @JsonProperty("display_name") String displayName,
        @JsonProperty("domain_id") String domainId,
        @JsonProperty("id") String id,
        @JsonProperty("reply_to") String replyTo,
        @JsonProperty("status") String status,
        @JsonProperty("updated_at") String updatedAt
) {}
