# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Resources.Inbound.Chunk0000 do
  @moduledoc false

  alias RelevateSdk.{API, Client}

  @spec list_inbound(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def list_inbound(client, options \\ []), do: API.list_inbound(client, options)

  @spec get_inbound(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def get_inbound(client, options \\ []), do: API.get_inbound(client, options)
end
