# Generated by Kaji. Do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

@dataclass
class ContactQueryResponse:
    api_version: str
    data: list[Contact]
    page: Page

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "ContactQueryResponse":
        return cls(
            api_version=value["api_version"],
            data=value["data"],
            page=value["page"],
        )
