# Generated by Kaji. Do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

@dataclass
class CrmCreateList:
    name: str
    object_id: str
    description: str | None = None

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "CrmCreateList":
        return cls(
            description=value.get("description"),
            name=value["name"],
            object_id=value["object_id"],
        )
