# Generated by Kaji. Do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

@dataclass
class CrmDeletedTask:
    id: str

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "CrmDeletedTask":
        return cls(
            id=value["id"],
        )
