# Generated by Kaji. Do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

@dataclass
class CrmList:
    created_at: str
    description: str
    id: str
    name: str
    object_id: str
    updated_at: str

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "CrmList":
        return cls(
            created_at=value["created_at"],
            description=value["description"],
            id=value["id"],
            name=value["name"],
            object_id=value["object_id"],
            updated_at=value["updated_at"],
        )
