# Generated by Kaji. Do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

@dataclass
class CrmListEntriesPage:
    api_version: str
    data: list[CrmListEntry]
    page: dict[str, Any]

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "CrmListEntriesPage":
        return cls(
            api_version=value["api_version"],
            data=value["data"],
            page=value["page"],
        )
