# Generated by Kaji. Do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

@dataclass
class CrmMetadataDeletedData:
    deleted: bool

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "CrmMetadataDeletedData":
        return cls(
            deleted=value["deleted"],
        )
