# Generated by Kaji. Do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

@dataclass
class CrmMetadataAttribute:
    id: str
    is_system: bool
    key: str
    multiple: bool
    name: str
    options: list[str]
    required: bool
    type: str
    created_at: str | None = None
    currency_code: str | None | None = None
    expression: str | None | None = None
    list_id: str | None | None = None
    object_id: str | None | None = None
    organization_id: str | None = None
    target_object_id: str | None | None = None
    updated_at: str | None = None

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "CrmMetadataAttribute":
        return cls(
            created_at=value.get("created_at"),
            currency_code=value.get("currency_code"),
            expression=value.get("expression"),
            id=value["id"],
            is_system=value["is_system"],
            key=value["key"],
            list_id=value.get("list_id"),
            multiple=value["multiple"],
            name=value["name"],
            object_id=value.get("object_id"),
            options=value["options"],
            organization_id=value.get("organization_id"),
            required=value["required"],
            target_object_id=value.get("target_object_id"),
            type=value["type"],
            updated_at=value.get("updated_at"),
        )
