# Generated by Kaji. Do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

@dataclass
class CrmMetadataDeleted:
    api_version: str
    data: CrmMetadataDeletedData

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "CrmMetadataDeleted":
        return cls(
            api_version=value["api_version"],
            data=value["data"],
        )
