# Generated by Kaji. Do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

@dataclass
class CrmNote:
    body: str
    created_at: str
    id: str
    mentions: list[CrmNoteMention]
    record_id: str
    title: str
    updated_at: str
    author_id: str | None | None = None
    content: CrmNoteDocument | None | None = None
    deleted_at: str | None | None = None
    mention_records: list[dict[str, Any]] | None = None

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "CrmNote":
        return cls(
            author_id=value.get("author_id"),
            body=value["body"],
            content=value.get("content"),
            created_at=value["created_at"],
            deleted_at=value.get("deleted_at"),
            id=value["id"],
            mention_records=value.get("mention_records"),
            mentions=value["mentions"],
            record_id=value["record_id"],
            title=value["title"],
            updated_at=value["updated_at"],
        )
