# Generated by Kaji. Do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

@dataclass
class CrmNoteDocument:
    content: list[dict[str, Any]]
    type: str

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "CrmNoteDocument":
        return cls(
            content=value["content"],
            type=value["type"],
        )
