# Generated by Kaji. Do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

@dataclass
class CrmObjectDelete:
    confirmation_name: str

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "CrmObjectDelete":
        return cls(
            confirmation_name=value["confirmation_name"],
        )
