# Generated by Kaji. Do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

@dataclass
class CrmObjectDiscovery:
    enabled: bool
    id: str
    is_system: bool
    name: str
    slug: str
    created_at: str | None = None
    icon: str | None | None = None
    updated_at: str | None = None

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "CrmObjectDiscovery":
        return cls(
            created_at=value.get("created_at"),
            enabled=value["enabled"],
            icon=value.get("icon"),
            id=value["id"],
            is_system=value["is_system"],
            name=value["name"],
            slug=value["slug"],
            updated_at=value.get("updated_at"),
        )
