# Generated by Kaji. Do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

@dataclass
class CrmTaskPatch:
    description: str | None = None
    due_at: str | None = None
    due_timezone: str | None = None
    owner_id: str | None | None = None
    status: str | None = None
    title: str | None = None

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "CrmTaskPatch":
        return cls(
            description=value.get("description"),
            due_at=value.get("due_at"),
            due_timezone=value.get("due_timezone"),
            owner_id=value.get("owner_id"),
            status=value.get("status"),
            title=value.get("title"),
        )
