# Generated by Kaji. Do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

@dataclass
class Domain:
    created_at: str
    dkim_selector: str
    dmarc_mode: str
    id: str
    name: str
    normalized_name: str
    receiving_enabled: bool
    status: str
    updated_at: str
    last_checked_at: str | None | None = None
    ownership_verified_at: str | None | None = None
    receiving_verified_at: str | None | None = None

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "Domain":
        return cls(
            created_at=value["created_at"],
            dkim_selector=value["dkim_selector"],
            dmarc_mode=value["dmarc_mode"],
            id=value["id"],
            last_checked_at=value.get("last_checked_at"),
            name=value["name"],
            normalized_name=value["normalized_name"],
            ownership_verified_at=value.get("ownership_verified_at"),
            receiving_enabled=value["receiving_enabled"],
            receiving_verified_at=value.get("receiving_verified_at"),
            status=value["status"],
            updated_at=value["updated_at"],
        )
