# Generated by Kaji. Do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

@dataclass
class EventResponse:
    api_version: str
    event_id: str
    received_at: str
    replayed: bool

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "EventResponse":
        return cls(
            api_version=value["api_version"],
            event_id=value["event_id"],
            received_at=value["received_at"],
            replayed=value["replayed"],
        )
