# Generated by Kaji. Do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

@dataclass
class HookUpdate:
    event_types: list[str] | None | None = None
    status: str | None | None = None
    url: str | None | None = None

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "HookUpdate":
        return cls(
            event_types=value.get("event_types"),
            status=value.get("status"),
            url=value.get("url"),
        )
