# Generated by Kaji. Do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

@dataclass
class InboundMessage:
    authentication: Any
    created_at: str
    delivery_id: str
    disposition: str
    envelope_to: str
    header_to: list[str]
    id: str
    malware_verdict: str
    received_at: str
    references: list[str]
    route_id: str
    spam_verdict: str
    subject: str
    envelope_from: str | None | None = None
    header_from: str | None | None = None
    html_body: str | None | None = None
    in_reply_to: str | None | None = None
    message_id: str | None | None = None
    release_reason: str | None | None = None
    released_at: str | None | None = None
    text_body: str | None | None = None

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "InboundMessage":
        return cls(
            authentication=value["authentication"],
            created_at=value["created_at"],
            delivery_id=value["delivery_id"],
            disposition=value["disposition"],
            envelope_from=value.get("envelope_from"),
            envelope_to=value["envelope_to"],
            header_from=value.get("header_from"),
            header_to=value["header_to"],
            html_body=value.get("html_body"),
            id=value["id"],
            in_reply_to=value.get("in_reply_to"),
            malware_verdict=value["malware_verdict"],
            message_id=value.get("message_id"),
            received_at=value["received_at"],
            references=value["references"],
            release_reason=value.get("release_reason"),
            released_at=value.get("released_at"),
            route_id=value["route_id"],
            spam_verdict=value["spam_verdict"],
            subject=value["subject"],
            text_body=value.get("text_body"),
        )
