# Generated by Kaji. Do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

@dataclass
class SenderIdentity:
    address: str
    created_at: str
    id: str
    status: str
    updated_at: str
    display_name: str | None | None = None
    domain_id: str | None | None = None
    reply_to: str | None | None = None

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "SenderIdentity":
        return cls(
            address=value["address"],
            created_at=value["created_at"],
            display_name=value.get("display_name"),
            domain_id=value.get("domain_id"),
            id=value["id"],
            reply_to=value.get("reply_to"),
            status=value["status"],
            updated_at=value["updated_at"],
        )
