# Generated by Kaji. Do not edit.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

@dataclass
class UpdateContact:
    attributes: dict[str, Any] | None | None = None
    first_name: str | None | None = None
    last_name: str | None | None = None
    locale: str | None | None = None

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "UpdateContact":
        return cls(
            attributes=value.get("attributes"),
            first_name=value.get("first_name"),
            last_name=value.get("last_name"),
            locale=value.get("locale"),
        )
