/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { DomainResponse } from '../DomainResponse.js'
import type { ErrorResponse } from '../ErrorResponse.js'

export type GetDomainPath = {
  id: string
}

export type GetDomainStatus200 = DomainResponse

export type GetDomainStatus401 = ErrorResponse

export type GetDomainStatus404 = ErrorResponse

export type GetDomainStatus503 = ErrorResponse

export type GetDomainOptions = {
  body?: never
  path: GetDomainPath
  query?: never
  headers?: never
  cookie?: never
}

export type GetDomainResponses = {
  '200': GetDomainStatus200
  '401': GetDomainStatus401
  '404': GetDomainStatus404
  '503': GetDomainStatus503
}

/**
 * @description Union of all possible responses
 */
export type GetDomainResponse = GetDomainStatus200 | GetDomainStatus401 | GetDomainStatus404 | GetDomainStatus503
