// <auto-generated />
// Generated by Kaji. Do not edit.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kaji.RelevateSdk;

public sealed record Contact
{
    [JsonPropertyName("attributes")]
    public JsonElement Attributes { get; init; }
    [JsonPropertyName("blocked_at")]
    public DateTimeOffset? BlockedAt { get; init; }
    [JsonPropertyName("blocked_reason")]
    public string? BlockedReason { get; init; }
    [JsonPropertyName("consent_source")]
    public string? ConsentSource { get; init; }
    [JsonPropertyName("consented_at")]
    public DateTimeOffset? ConsentedAt { get; init; }
    [JsonPropertyName("created_at")]
    public required DateTimeOffset CreatedAt { get; init; }
    [JsonPropertyName("email")]
    public required string Email { get; init; }
    [JsonPropertyName("first_name")]
    public string? FirstName { get; init; }
    [JsonPropertyName("id")]
    public required string Id { get; init; }
    [JsonPropertyName("last_name")]
    public string? LastName { get; init; }
    [JsonPropertyName("locale")]
    public string? Locale { get; init; }
    [JsonPropertyName("marketing_status")]
    public required string MarketingStatus { get; init; }
    [JsonPropertyName("normalized_email")]
    public required string NormalizedEmail { get; init; }
    [JsonPropertyName("origin")]
    public required string Origin { get; init; }
    [JsonPropertyName("status")]
    public required string Status { get; init; }
    [JsonPropertyName("updated_at")]
    public required DateTimeOffset UpdatedAt { get; init; }
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? AdditionalProperties { get; init; }
}
