// <auto-generated />
// Generated by Kaji. Do not edit.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kaji.RelevateSdk;

public sealed record CreateWebhookResponse
{
    [JsonPropertyName("api_version")]
    public required string ApiVersion { get; init; }
    [JsonPropertyName("data")]
    public required Webhook Data { get; init; }
    [JsonPropertyName("signing_secret")]
    public required string SigningSecret { get; init; }
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? AdditionalProperties { get; init; }
}
