// <auto-generated />
// Generated by Kaji. Do not edit.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kaji.RelevateSdk;

public sealed record CrmCreateList
{
    [JsonPropertyName("description")]
    public string? Description { get; init; }
    [JsonPropertyName("name")]
    public required string Name { get; init; }
    [JsonPropertyName("object_id")]
    public required string ObjectId { get; init; }
}
