// <auto-generated />
// Generated by Kaji. Do not edit.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kaji.RelevateSdk;

public sealed record CrmListsPage
{
    [JsonPropertyName("api_version")]
    public required string ApiVersion { get; init; }
    [JsonPropertyName("data")]
    public required List<CrmList> Data { get; init; }
    [JsonPropertyName("page")]
    public required JsonElement Page { get; init; }
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? AdditionalProperties { get; init; }
}
