// <auto-generated />
// Generated by Kaji. Do not edit.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kaji.RelevateSdk;

public sealed record CrmMetadataAttribute
{
    [JsonPropertyName("created_at")]
    public DateTimeOffset? CreatedAt { get; init; }
    [JsonPropertyName("currency_code")]
    public string? CurrencyCode { get; init; }
    [JsonPropertyName("expression")]
    public string? Expression { get; init; }
    [JsonPropertyName("id")]
    public required string Id { get; init; }
    [JsonPropertyName("is_system")]
    public bool IsSystem { get; init; }
    [JsonPropertyName("key")]
    public required string Key { get; init; }
    [JsonPropertyName("list_id")]
    public string? ListId { get; init; }
    [JsonPropertyName("multiple")]
    public bool Multiple { get; init; }
    [JsonPropertyName("name")]
    public required string Name { get; init; }
    [JsonPropertyName("object_id")]
    public string? ObjectId { get; init; }
    [JsonPropertyName("options")]
    public required List<string> Options { get; init; }
    [JsonPropertyName("organization_id")]
    public string? OrganizationId { get; init; }
    [JsonPropertyName("required")]
    public bool Required { get; init; }
    [JsonPropertyName("target_object_id")]
    public string? TargetObjectId { get; init; }
    [JsonPropertyName("type")]
    public required string Type { get; init; }
    [JsonPropertyName("updated_at")]
    public DateTimeOffset? UpdatedAt { get; init; }
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? AdditionalProperties { get; init; }
}
