// <auto-generated />
// Generated by Kaji. Do not edit.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kaji.RelevateSdk;

public sealed record CrmObjectDeletionPreviewData
{
    [JsonPropertyName("blocking_relationships")]
    public required List<JsonElement> BlockingRelationships { get; init; }
    [JsonPropertyName("list_count")]
    public long ListCount { get; init; }
    [JsonPropertyName("object")]
    public required CrmMetadataObject ObjectValue { get; init; }
    [JsonPropertyName("record_count")]
    public long RecordCount { get; init; }
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? AdditionalProperties { get; init; }
}
