// <auto-generated />
// Generated by Kaji. Do not edit.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kaji.RelevateSdk;

public sealed record CrmQualityRecord
{
    [JsonPropertyName("display_name")]
    public required string DisplayName { get; init; }
    [JsonPropertyName("duplicate_candidate_count")]
    public long DuplicateCandidateCount { get; init; }
    [JsonPropertyName("duplicate_candidates")]
    public required List<JsonElement> DuplicateCandidates { get; init; }
    [JsonPropertyName("issues")]
    public required List<CrmQualityIssue> Issues { get; init; }
    [JsonPropertyName("record_id")]
    public required string RecordId { get; init; }
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? AdditionalProperties { get; init; }
}
