// <auto-generated />
// Generated by Kaji. Do not edit.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kaji.RelevateSdk;

public sealed record CrmRecordPatch
{
    [JsonPropertyName("archived")]
    public bool? Archived { get; init; }
    [JsonPropertyName("display_name")]
    public string? DisplayName { get; init; }
    [JsonPropertyName("values")]
    public JsonElement? Values { get; init; }
}
