// <auto-generated />
// Generated by Kaji. Do not edit.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kaji.RelevateSdk;

public sealed record CrmRecordCreate
{
    [JsonPropertyName("display_name")]
    public required string DisplayName { get; init; }
    [JsonPropertyName("external_id")]
    public string? ExternalId { get; init; }
    [JsonPropertyName("values")]
    public JsonElement? Values { get; init; }
}
