// <auto-generated />
// Generated by Kaji. Do not edit.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kaji.RelevateSdk;

public sealed record ErrorResponse
{
    [JsonPropertyName("api_version")]
    public required string ApiVersion { get; init; }
    [JsonPropertyName("error")]
    public required ApiError Error { get; init; }
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? AdditionalProperties { get; init; }
}
