// <auto-generated />
// Generated by Kaji. Do not edit.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kaji.RelevateSdk;

public sealed record EventResponse
{
    [JsonPropertyName("api_version")]
    public required string ApiVersion { get; init; }
    [JsonPropertyName("event_id")]
    public required string EventId { get; init; }
    [JsonPropertyName("received_at")]
    public required DateTimeOffset ReceivedAt { get; init; }
    [JsonPropertyName("replayed")]
    public bool Replayed { get; init; }
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? AdditionalProperties { get; init; }
}
