// <auto-generated />
// Generated by Kaji. Do not edit.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kaji.RelevateSdk;

public sealed record HookUpdate
{
    [JsonPropertyName("event_types")]
    public List<string>? EventTypes { get; init; }
    [JsonPropertyName("status")]
    public string? Status { get; init; }
    [JsonPropertyName("url")]
    public string? Url { get; init; }
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? AdditionalProperties { get; init; }
}
