// <auto-generated />
// Generated by Kaji. Do not edit.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kaji.RelevateSdk;

public sealed record HookCreate
{
    [JsonPropertyName("event_types")]
    public required List<string> EventTypes { get; init; }
    [JsonPropertyName("url")]
    public required string Url { get; init; }
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? AdditionalProperties { get; init; }
}
