// <auto-generated />
// Generated by Kaji. Do not edit.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kaji.RelevateSdk;

public sealed record SendResponse
{
    [JsonPropertyName("accepted_at")]
    public required DateTimeOffset AcceptedAt { get; init; }
    [JsonPropertyName("api_version")]
    public required string ApiVersion { get; init; }
    [JsonPropertyName("reason_code")]
    public required string ReasonCode { get; init; }
    [JsonPropertyName("recipients")]
    public required List<RecipientResponse> Recipients { get; init; }
    [JsonPropertyName("replayed")]
    public bool? Replayed { get; init; }
    [JsonPropertyName("send_id")]
    public required string SendId { get; init; }
    [JsonPropertyName("state")]
    public required string State { get; init; }
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? AdditionalProperties { get; init; }
}
