<?php

declare(strict_types=1);

namespace Relevate\Sdk;

use Relevate\Sdk\Exceptions\ApiException;
use Psr\Http\Message\StreamInterface;
use Relevate\Sdk\Models\AuthCheckResponse;
use Relevate\Sdk\Models\ContactListResponse;
use Relevate\Sdk\Models\ContactQuery;
use Relevate\Sdk\Models\ContactQueryResponse;
use Relevate\Sdk\Models\ContactResponse;
use Relevate\Sdk\Models\CreateContact;
use Relevate\Sdk\Models\CreateWebhookResponse;
use Relevate\Sdk\Models\CrmActivity;
use Relevate\Sdk\Models\CrmApiError;
use Relevate\Sdk\Models\CrmAttributeCreate;
use Relevate\Sdk\Models\CrmAttributeDiscovery;
use Relevate\Sdk\Models\CrmAttributePatch;
use Relevate\Sdk\Models\CrmContentPage;
use Relevate\Sdk\Models\CrmCreateList;
use Relevate\Sdk\Models\CrmCreateListEntry;
use Relevate\Sdk\Models\CrmDeletedNote;
use Relevate\Sdk\Models\CrmDeletedTask;
use Relevate\Sdk\Models\CrmListDeletionResponse;
use Relevate\Sdk\Models\CrmListEntriesPage;
use Relevate\Sdk\Models\CrmListEntryResponse;
use Relevate\Sdk\Models\CrmListResponse;
use Relevate\Sdk\Models\CrmListsPage;
use Relevate\Sdk\Models\CrmMetadataAttributeResponse;
use Relevate\Sdk\Models\CrmMetadataAttributesResponse;
use Relevate\Sdk\Models\CrmMetadataDeleted;
use Relevate\Sdk\Models\CrmMetadataObjectResponse;
use Relevate\Sdk\Models\CrmNote;
use Relevate\Sdk\Models\CrmNoteWrite;
use Relevate\Sdk\Models\CrmObjectCreate;
use Relevate\Sdk\Models\CrmObjectDelete;
use Relevate\Sdk\Models\CrmObjectDeletionPreview;
use Relevate\Sdk\Models\CrmObjectDiscovery;
use Relevate\Sdk\Models\CrmObjectPatch;
use Relevate\Sdk\Models\CrmQualityResponse;
use Relevate\Sdk\Models\CrmRecord;
use Relevate\Sdk\Models\CrmRecordCreate;
use Relevate\Sdk\Models\CrmRecordPatch;
use Relevate\Sdk\Models\CrmRecordResponse;
use Relevate\Sdk\Models\CrmTask;
use Relevate\Sdk\Models\CrmTaskCreate;
use Relevate\Sdk\Models\CrmTaskPatch;
use Relevate\Sdk\Models\CrmUpdateList;
use Relevate\Sdk\Models\CrmUpdateListEntry;
use Relevate\Sdk\Models\CrmUpsert;
use Relevate\Sdk\Models\DomainListResponse;
use Relevate\Sdk\Models\DomainResponse;
use Relevate\Sdk\Models\ErrorResponse;
use Relevate\Sdk\Models\EventResponse;
use Relevate\Sdk\Models\HookCreate;
use Relevate\Sdk\Models\HookUpdate;
use Relevate\Sdk\Models\InboundListResponse;
use Relevate\Sdk\Models\InboundResponse;
use Relevate\Sdk\Models\SegmentListResponse;
use Relevate\Sdk\Models\SegmentResponse;
use Relevate\Sdk\Models\SendQuery;
use Relevate\Sdk\Models\SendRequest;
use Relevate\Sdk\Models\SendResponse;
use Relevate\Sdk\Models\SenderIdentityListResponse;
use Relevate\Sdk\Models\SenderIdentityResponse;
use Relevate\Sdk\Models\TrackEventRequest;
use Relevate\Sdk\Models\UpdateContact;
use Relevate\Sdk\Models\WebhookDeliveryListResponse;
use Relevate\Sdk\Models\WebhookListResponse;
use Relevate\Sdk\Models\WebhookResponse;

// Generated by Kaji. Do not edit.

/** Bounded generated operation slice; composed into Client. */
trait ClientOperations000
{
    public function listCrmLists(?int $limit = null, ?string $after = null, ?string $objectId = null): CrmListsPage
    {
        $path = '/v1/crm/lists';
        $contents = $this->request('GET', $path, ['limit' => $limit, 'after' => $after, 'object_id' => $objectId], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmListsPage::fromArray($data);
    }

    public function createCrmList(CrmCreateList $body): CrmListResponse
    {
        $path = '/v1/crm/lists';
        $contents = $this->request('POST', $path, [], ['Accept' => 'application/json'], $body, "json", false, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmListResponse::fromArray($data);
    }

    public function deleteCrmList(string $list): CrmListDeletionResponse
    {
        $path = '/v1/crm/lists/{list}';
        $path = str_replace('{list}', rawurlencode((string) $list), $path);
        $contents = $this->request('DELETE', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmListDeletionResponse::fromArray($data);
    }

    public function getCrmList(string $list): CrmListResponse
    {
        $path = '/v1/crm/lists/{list}';
        $path = str_replace('{list}', rawurlencode((string) $list), $path);
        $contents = $this->request('GET', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmListResponse::fromArray($data);
    }

    public function updateCrmList(string $list, CrmUpdateList $body): CrmListResponse
    {
        $path = '/v1/crm/lists/{list}';
        $path = str_replace('{list}', rawurlencode((string) $list), $path);
        $contents = $this->request('PATCH', $path, [], ['Accept' => 'application/json'], $body, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmListResponse::fromArray($data);
    }

    public function listCrmListAttributes(string $list): CrmMetadataAttributesResponse
    {
        $path = '/v1/crm/lists/{list}/attributes';
        $path = str_replace('{list}', rawurlencode((string) $list), $path);
        $contents = $this->request('GET', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmMetadataAttributesResponse::fromArray($data);
    }

    public function createCrmListAttribute(string $list, CrmAttributeCreate $body): CrmMetadataAttributeResponse
    {
        $path = '/v1/crm/lists/{list}/attributes';
        $path = str_replace('{list}', rawurlencode((string) $list), $path);
        $contents = $this->request('POST', $path, [], ['Accept' => 'application/json'], $body, "json", false, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmMetadataAttributeResponse::fromArray($data);
    }

    public function deleteCrmListAttribute(string $list, string $attribute): CrmMetadataDeleted
    {
        $path = '/v1/crm/lists/{list}/attributes/{attribute}';
        $path = str_replace('{list}', rawurlencode((string) $list), $path);
        $path = str_replace('{attribute}', rawurlencode((string) $attribute), $path);
        $contents = $this->request('DELETE', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmMetadataDeleted::fromArray($data);
    }

    public function updateCrmListAttribute(string $list, string $attribute, CrmAttributePatch $body): CrmMetadataAttributeResponse
    {
        $path = '/v1/crm/lists/{list}/attributes/{attribute}';
        $path = str_replace('{list}', rawurlencode((string) $list), $path);
        $path = str_replace('{attribute}', rawurlencode((string) $attribute), $path);
        $contents = $this->request('PATCH', $path, [], ['Accept' => 'application/json'], $body, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmMetadataAttributeResponse::fromArray($data);
    }

    public function listCrmListEntries(string $list, ?int $limit = null, ?string $after = null): CrmListEntriesPage
    {
        $path = '/v1/crm/lists/{list}/entries';
        $path = str_replace('{list}', rawurlencode((string) $list), $path);
        $contents = $this->request('GET', $path, ['limit' => $limit, 'after' => $after], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmListEntriesPage::fromArray($data);
    }

    public function createCrmListEntry(string $list, CrmCreateListEntry $body): CrmListEntryResponse
    {
        $path = '/v1/crm/lists/{list}/entries';
        $path = str_replace('{list}', rawurlencode((string) $list), $path);
        $contents = $this->request('POST', $path, [], ['Accept' => 'application/json'], $body, "json", false, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmListEntryResponse::fromArray($data);
    }

    public function deleteCrmListEntry(string $list, string $entry): CrmListDeletionResponse
    {
        $path = '/v1/crm/lists/{list}/entries/{entry}';
        $path = str_replace('{list}', rawurlencode((string) $list), $path);
        $path = str_replace('{entry}', rawurlencode((string) $entry), $path);
        $contents = $this->request('DELETE', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmListDeletionResponse::fromArray($data);
    }

    public function getCrmListEntry(string $list, string $entry): CrmListEntryResponse
    {
        $path = '/v1/crm/lists/{list}/entries/{entry}';
        $path = str_replace('{list}', rawurlencode((string) $list), $path);
        $path = str_replace('{entry}', rawurlencode((string) $entry), $path);
        $contents = $this->request('GET', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmListEntryResponse::fromArray($data);
    }

    public function updateCrmListEntry(string $list, string $entry, CrmUpdateListEntry $body): CrmListEntryResponse
    {
        $path = '/v1/crm/lists/{list}/entries/{entry}';
        $path = str_replace('{list}', rawurlencode((string) $list), $path);
        $path = str_replace('{entry}', rawurlencode((string) $entry), $path);
        $contents = $this->request('PATCH', $path, [], ['Accept' => 'application/json'], $body, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmListEntryResponse::fromArray($data);
    }

    public function deleteCrmNote(string $noteId): array
    {
        $path = '/v1/crm/notes/{note_id}';
        $path = str_replace('{note_id}', rawurlencode((string) $noteId), $path);
        $contents = $this->request('DELETE', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return $data;
    }

    public function getCrmNote(string $noteId): array
    {
        $path = '/v1/crm/notes/{note_id}';
        $path = str_replace('{note_id}', rawurlencode((string) $noteId), $path);
        $contents = $this->request('GET', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return $data;
    }

    public function updateCrmNote(string $noteId, CrmNoteWrite $body): array
    {
        $path = '/v1/crm/notes/{note_id}';
        $path = str_replace('{note_id}', rawurlencode((string) $noteId), $path);
        $contents = $this->request('PATCH', $path, [], ['Accept' => 'application/json'], $body, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return $data;
    }

    public function listCrmObjects(?int $limit = null, ?string $after = null, ?bool $includeDisabled = null): array
    {
        $path = '/v1/crm/objects';
        $contents = $this->request('GET', $path, ['limit' => $limit, 'after' => $after, 'include_disabled' => $includeDisabled], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return $data;
    }

    public function createCrmObject(CrmObjectCreate $body): CrmMetadataObjectResponse
    {
        $path = '/v1/crm/objects';
        $contents = $this->request('POST', $path, [], ['Accept' => 'application/json'], $body, "json", false, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmMetadataObjectResponse::fromArray($data);
    }

    public function deleteCrmObject(string $object, CrmObjectDelete $body): CrmMetadataDeleted
    {
        $path = '/v1/crm/objects/{object}';
        $path = str_replace('{object}', rawurlencode((string) $object), $path);
        $contents = $this->request('DELETE', $path, [], ['Accept' => 'application/json'], $body, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmMetadataDeleted::fromArray($data);
    }

    public function getCrmObject(string $object): array
    {
        $path = '/v1/crm/objects/{object}';
        $path = str_replace('{object}', rawurlencode((string) $object), $path);
        $contents = $this->request('GET', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return $data;
    }

    public function updateCrmObject(string $object, CrmObjectPatch $body): CrmMetadataObjectResponse
    {
        $path = '/v1/crm/objects/{object}';
        $path = str_replace('{object}', rawurlencode((string) $object), $path);
        $contents = $this->request('PATCH', $path, [], ['Accept' => 'application/json'], $body, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmMetadataObjectResponse::fromArray($data);
    }

    public function listCrmObjectAttributes(string $object): CrmMetadataAttributesResponse
    {
        $path = '/v1/crm/objects/{object}/attributes';
        $path = str_replace('{object}', rawurlencode((string) $object), $path);
        $contents = $this->request('GET', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmMetadataAttributesResponse::fromArray($data);
    }

    public function createCrmObjectAttribute(string $object, CrmAttributeCreate $body): CrmMetadataAttributeResponse
    {
        $path = '/v1/crm/objects/{object}/attributes';
        $path = str_replace('{object}', rawurlencode((string) $object), $path);
        $contents = $this->request('POST', $path, [], ['Accept' => 'application/json'], $body, "json", false, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmMetadataAttributeResponse::fromArray($data);
    }

    public function deleteCrmObjectAttribute(string $object, string $attribute): CrmMetadataDeleted
    {
        $path = '/v1/crm/objects/{object}/attributes/{attribute}';
        $path = str_replace('{object}', rawurlencode((string) $object), $path);
        $path = str_replace('{attribute}', rawurlencode((string) $attribute), $path);
        $contents = $this->request('DELETE', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmMetadataDeleted::fromArray($data);
    }

    public function updateCrmObjectAttribute(string $object, string $attribute, CrmAttributePatch $body): CrmMetadataAttributeResponse
    {
        $path = '/v1/crm/objects/{object}/attributes/{attribute}';
        $path = str_replace('{object}', rawurlencode((string) $object), $path);
        $path = str_replace('{attribute}', rawurlencode((string) $attribute), $path);
        $contents = $this->request('PATCH', $path, [], ['Accept' => 'application/json'], $body, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmMetadataAttributeResponse::fromArray($data);
    }

    public function previewCrmObjectDeletion(string $object): CrmObjectDeletionPreview
    {
        $path = '/v1/crm/objects/{object}/deletion-preview';
        $path = str_replace('{object}', rawurlencode((string) $object), $path);
        $contents = $this->request('GET', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmObjectDeletionPreview::fromArray($data);
    }

    public function getCrmObjectQuality(string $object, ?int $limit = null, ?string $after = null, ?bool $includeArchived = null): CrmQualityResponse
    {
        $path = '/v1/crm/objects/{object}/quality';
        $path = str_replace('{object}', rawurlencode((string) $object), $path);
        $contents = $this->request('GET', $path, ['limit' => $limit, 'after' => $after, 'include_archived' => $includeArchived], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmQualityResponse::fromArray($data);
    }

    public function listCrmRecords(string $object, ?int $limit = null, ?string $after = null, ?string $externalId = null, ?bool $includeArchived = null): array
    {
        $path = '/v1/crm/objects/{object}/records';
        $path = str_replace('{object}', rawurlencode((string) $object), $path);
        $contents = $this->request('GET', $path, ['limit' => $limit, 'after' => $after, 'external_id' => $externalId, 'include_archived' => $includeArchived], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return $data;
    }

    public function createCrmRecord(string $object, CrmRecordCreate $body): CrmRecordResponse
    {
        $path = '/v1/crm/objects/{object}/records';
        $path = str_replace('{object}', rawurlencode((string) $object), $path);
        $contents = $this->request('POST', $path, [], ['Accept' => 'application/json'], $body, "json", false, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmRecordResponse::fromArray($data);
    }

    public function upsertCrmRecord(string $object, CrmUpsert $body): CrmRecordResponse
    {
        $path = '/v1/crm/objects/{object}/records/upsert';
        $path = str_replace('{object}', rawurlencode((string) $object), $path);
        $contents = $this->request('POST', $path, [], ['Accept' => 'application/json'], $body, "json", false, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmRecordResponse::fromArray($data);
    }

    public function archiveCrmRecord(string $recordId): CrmRecordResponse
    {
        $path = '/v1/crm/records/{record_id}';
        $path = str_replace('{record_id}', rawurlencode((string) $recordId), $path);
        $contents = $this->request('DELETE', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmRecordResponse::fromArray($data);
    }

    public function getCrmRecord(string $recordId): CrmRecordResponse
    {
        $path = '/v1/crm/records/{record_id}';
        $path = str_replace('{record_id}', rawurlencode((string) $recordId), $path);
        $contents = $this->request('GET', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmRecordResponse::fromArray($data);
    }

    public function updateCrmRecord(string $recordId, CrmRecordPatch $body): CrmRecordResponse
    {
        $path = '/v1/crm/records/{record_id}';
        $path = str_replace('{record_id}', rawurlencode((string) $recordId), $path);
        $contents = $this->request('PATCH', $path, [], ['Accept' => 'application/json'], $body, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CrmRecordResponse::fromArray($data);
    }

    public function listCrmActivities(string $recordId, ?int $limit = null, ?string $after = null): array
    {
        $path = '/v1/crm/records/{record_id}/activities';
        $path = str_replace('{record_id}', rawurlencode((string) $recordId), $path);
        $contents = $this->request('GET', $path, ['limit' => $limit, 'after' => $after], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return $data;
    }

    public function listCrmNotes(string $recordId, ?int $limit = null, ?string $after = null): array
    {
        $path = '/v1/crm/records/{record_id}/notes';
        $path = str_replace('{record_id}', rawurlencode((string) $recordId), $path);
        $contents = $this->request('GET', $path, ['limit' => $limit, 'after' => $after], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return $data;
    }

    public function createCrmNote(string $recordId, CrmNoteWrite $body): array
    {
        $path = '/v1/crm/records/{record_id}/notes';
        $path = str_replace('{record_id}', rawurlencode((string) $recordId), $path);
        $contents = $this->request('POST', $path, [], ['Accept' => 'application/json'], $body, "json", false, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return $data;
    }

    public function listCrmTasks(string $recordId, ?int $limit = null, ?string $after = null): array
    {
        $path = '/v1/crm/records/{record_id}/tasks';
        $path = str_replace('{record_id}', rawurlencode((string) $recordId), $path);
        $contents = $this->request('GET', $path, ['limit' => $limit, 'after' => $after], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return $data;
    }

    public function createCrmTask(string $recordId, CrmTaskCreate $body): array
    {
        $path = '/v1/crm/records/{record_id}/tasks';
        $path = str_replace('{record_id}', rawurlencode((string) $recordId), $path);
        $contents = $this->request('POST', $path, [], ['Accept' => 'application/json'], $body, "json", false, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return $data;
    }

    public function deleteCrmTask(string $taskId): array
    {
        $path = '/v1/crm/tasks/{task_id}';
        $path = str_replace('{task_id}', rawurlencode((string) $taskId), $path);
        $contents = $this->request('DELETE', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return $data;
    }

    public function getCrmTask(string $taskId): array
    {
        $path = '/v1/crm/tasks/{task_id}';
        $path = str_replace('{task_id}', rawurlencode((string) $taskId), $path);
        $contents = $this->request('GET', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return $data;
    }

    public function updateCrmTask(string $taskId, CrmTaskPatch $body): array
    {
        $path = '/v1/crm/tasks/{task_id}';
        $path = str_replace('{task_id}', rawurlencode((string) $taskId), $path);
        $contents = $this->request('PATCH', $path, [], ['Accept' => 'application/json'], $body, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return $data;
    }

    public function authCheck(): AuthCheckResponse
    {
        $path = '/v1/email/auth-check';
        $contents = $this->request('GET', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return AuthCheckResponse::fromArray($data);
    }

    public function listContacts(?int $limit = null): ContactListResponse
    {
        $path = '/v1/email/contacts';
        $contents = $this->request('GET', $path, ['limit' => $limit], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return ContactListResponse::fromArray($data);
    }

    public function createContact(CreateContact $body): ContactResponse
    {
        $path = '/v1/email/contacts';
        $contents = $this->request('POST', $path, [], ['Accept' => 'application/json'], $body, "json", false, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return ContactResponse::fromArray($data);
    }

    public function queryContacts(ContactQuery $body): ContactQueryResponse
    {
        $path = '/v1/email/contacts/query';
        $contents = $this->request('POST', $path, [], ['Accept' => 'application/json'], $body, "json", false, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return ContactQueryResponse::fromArray($data);
    }

    public function getContact(string $id): ContactResponse
    {
        $path = '/v1/email/contacts/{id}';
        $path = str_replace('{id}', rawurlencode((string) $id), $path);
        $contents = $this->request('GET', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return ContactResponse::fromArray($data);
    }

    public function updateContact(string $id, UpdateContact $body): ContactResponse
    {
        $path = '/v1/email/contacts/{id}';
        $path = str_replace('{id}', rawurlencode((string) $id), $path);
        $contents = $this->request('PATCH', $path, [], ['Accept' => 'application/json'], $body, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return ContactResponse::fromArray($data);
    }

    public function listDomains(?int $limit = null): DomainListResponse
    {
        $path = '/v1/email/domains';
        $contents = $this->request('GET', $path, ['limit' => $limit], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return DomainListResponse::fromArray($data);
    }

    public function getDomain(string $id): DomainResponse
    {
        $path = '/v1/email/domains/{id}';
        $path = str_replace('{id}', rawurlencode((string) $id), $path);
        $contents = $this->request('GET', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return DomainResponse::fromArray($data);
    }

    public function track(TrackEventRequest $body): EventResponse
    {
        $path = '/v1/email/events';
        $contents = $this->request('POST', $path, [], ['Accept' => 'application/json'], $body, "json", false, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return EventResponse::fromArray($data);
    }

    public function listInbound(?int $limit = null): InboundListResponse
    {
        $path = '/v1/email/inbound';
        $contents = $this->request('GET', $path, ['limit' => $limit], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return InboundListResponse::fromArray($data);
    }

    public function getInbound(string $messageId): InboundResponse
    {
        $path = '/v1/email/inbound/{message_id}';
        $path = str_replace('{message_id}', rawurlencode((string) $messageId), $path);
        $contents = $this->request('GET', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return InboundResponse::fromArray($data);
    }

    public function listSegments(?int $limit = null): SegmentListResponse
    {
        $path = '/v1/email/segments';
        $contents = $this->request('GET', $path, ['limit' => $limit], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return SegmentListResponse::fromArray($data);
    }

    public function getSegment(string $id): SegmentResponse
    {
        $path = '/v1/email/segments/{id}';
        $path = str_replace('{id}', rawurlencode((string) $id), $path);
        $contents = $this->request('GET', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return SegmentResponse::fromArray($data);
    }

    public function listSenderIdentities(?int $limit = null): SenderIdentityListResponse
    {
        $path = '/v1/email/sender-identities';
        $contents = $this->request('GET', $path, ['limit' => $limit], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return SenderIdentityListResponse::fromArray($data);
    }

    public function getSenderIdentity(string $id): SenderIdentityResponse
    {
        $path = '/v1/email/sender-identities/{id}';
        $path = str_replace('{id}', rawurlencode((string) $id), $path);
        $contents = $this->request('GET', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return SenderIdentityResponse::fromArray($data);
    }

    public function create(SendRequest $body): SendResponse
    {
        $path = '/v1/email/sends';
        $contents = $this->request('POST', $path, [], ['Accept' => 'application/json'], $body, "json", false, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return SendResponse::fromArray($data);
    }

    public function query(SendQuery $body): void
    {
        $path = '/v1/email/sends/query';
        $contents = $this->request('POST', $path, [], ['Accept' => 'application/json'], $body, "json", false, null);
        return;
    }

    public function cancel(string $sendId): SendResponse
    {
        $path = '/v1/email/sends/{send_id}';
        $path = str_replace('{send_id}', rawurlencode((string) $sendId), $path);
        $contents = $this->request('DELETE', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return SendResponse::fromArray($data);
    }

    public function get(string $sendId): SendResponse
    {
        $path = '/v1/email/sends/{send_id}';
        $path = str_replace('{send_id}', rawurlencode((string) $sendId), $path);
        $contents = $this->request('GET', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return SendResponse::fromArray($data);
    }

    public function listWebhooks(): WebhookListResponse
    {
        $path = '/v1/email/webhooks';
        $contents = $this->request('GET', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return WebhookListResponse::fromArray($data);
    }

    public function createWebhook(HookCreate $body): CreateWebhookResponse
    {
        $path = '/v1/email/webhooks';
        $contents = $this->request('POST', $path, [], ['Accept' => 'application/json'], $body, "json", false, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return CreateWebhookResponse::fromArray($data);
    }

    public function deleteWebhook(string $webhookId): void
    {
        $path = '/v1/email/webhooks/{webhook_id}';
        $path = str_replace('{webhook_id}', rawurlencode((string) $webhookId), $path);
        $contents = $this->request('DELETE', $path, [], ['Accept' => 'application/json'], null, "json", true, null);
        return;
    }

    public function updateWebhook(string $webhookId, HookUpdate $body): WebhookResponse
    {
        $path = '/v1/email/webhooks/{webhook_id}';
        $path = str_replace('{webhook_id}', rawurlencode((string) $webhookId), $path);
        $contents = $this->request('PATCH', $path, [], ['Accept' => 'application/json'], $body, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return WebhookResponse::fromArray($data);
    }

    public function listDeliveries(string $webhookId, ?int $limit = null): WebhookDeliveryListResponse
    {
        $path = '/v1/email/webhooks/{webhook_id}/deliveries';
        $path = str_replace('{webhook_id}', rawurlencode((string) $webhookId), $path);
        $contents = $this->request('GET', $path, ['limit' => $limit], ['Accept' => 'application/json'], null, "json", true, null);
        if ($contents === '') {
            throw new \UnexpectedValueException('API response body was empty');
        }
        $data = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        return WebhookDeliveryListResponse::fromArray($data);
    }

}
