package app.relevate.sdk;

import app.relevate.sdk.internal.resources.AuthCheckResourcePart000;

// Generated by Kaji. Do not edit.

/** Typed namespace for AuthCheck operations. */
public final class AuthCheckResource extends AuthCheckResourcePart000 {
    AuthCheckResource(Client client) { super(client); }
}
