package app.relevate.sdk;

import java.net.http.HttpClient;
import java.time.Duration;
import java.util.Map;

// Generated by Kaji. Do not edit.

/** Immutable configuration for a generated API client. */
public record ClientConfig(
        String baseUrl,
        String apiKey,
        String apiKeyHeader,
        String apiKeyPrefix,
        Map<String, String> defaultHeaders,
        HttpClient httpClient,
        Duration timeout,
        RetryConfig retry,
        ClientHooks hooks
) {
    public ClientConfig(String baseUrl, String apiKey) {
        this(baseUrl, apiKey, "Authorization", "Bearer", Map.of(), null, Duration.ofSeconds(30), null, null);
    }

    public ClientConfig {
        if (baseUrl == null || baseUrl.isBlank()) {
            throw new IllegalArgumentException("baseUrl is required");
        }
        apiKeyHeader = apiKeyHeader == null || apiKeyHeader.isBlank() ? "Authorization" : apiKeyHeader;
        apiKeyPrefix = apiKeyPrefix == null ? "" : apiKeyPrefix;
        defaultHeaders = defaultHeaders == null ? Map.of() : Map.copyOf(defaultHeaders);
        timeout = timeout == null ? Duration.ofSeconds(30) : timeout;
        retry = retry == null ? RetryConfig.defaults() : retry;
    }
}
