package app.relevate.sdk;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import app.relevate.sdk.model.*;

// Generated by Kaji. Do not edit.

/** Thread-safe API client. Reuse one instance for the lifetime of an application. */
public class ClientBase {
    protected final String baseUrl;
    protected final String apiKey;
    protected final String apiKeyHeader;
    protected final String apiKeyPrefix;
    protected final Map<String, String> defaultHeaders;
    protected final HttpClient httpClient;
    protected final Duration timeout;
    protected final RetryConfig retry;
    protected final ClientHooks hooks;
    protected final ObjectMapper mapper;

    protected ClientBase(ClientConfig config) {
        Objects.requireNonNull(config, "config");
        this.baseUrl = stripTrailingSlash(config.baseUrl());
        this.apiKey = config.apiKey();
        this.apiKeyHeader = config.apiKeyHeader();
        this.apiKeyPrefix = config.apiKeyPrefix();
        this.defaultHeaders = config.defaultHeaders();
        this.timeout = config.timeout();
        this.retry = config.retry();
        this.hooks = config.hooks();
        this.httpClient = config.httpClient() != null ? config.httpClient() : HttpClient.newBuilder().connectTimeout(timeout).build();
        this.mapper = new ObjectMapper().registerModule(new JavaTimeModule());
    }

    protected String request(String method, String path, List<QueryParameter> query, Map<String, String> headers, java.lang.Object body) {
        var url = baseUrl + path + queryString(query);
        var builder = HttpRequest.newBuilder(URI.create(url)).timeout(timeout).header("Accept", "application/json");
        defaultHeaders.forEach(builder::header);
        headers.forEach(builder::header);
        if (apiKey != null && !apiKey.isBlank()) {
            var credential = apiKeyPrefix == null || apiKeyPrefix.isBlank() ? apiKey : apiKeyPrefix + " " + apiKey;
            builder.header(apiKeyHeader, credential);
        }
        try {
            if (body == null) {
                builder.method(method, HttpRequest.BodyPublishers.noBody());
            } else {
                builder.header("Content-Type", "application/json");
                builder.method(method, HttpRequest.BodyPublishers.ofString(mapper.writeValueAsString(body)));
            }
            var response = httpClient.send(builder.build(), HttpResponse.BodyHandlers.ofString());
            if (response.statusCode() < 200 || response.statusCode() >= 300) {
                throw new ApiException(response.statusCode(), response.body(), response.headers().firstValue("Retry-After").orElse(null));
            }
            if (hooks != null) hooks.afterResponse(response.statusCode());
            return response.body();
        } catch (JsonProcessingException error) {
            throw new IllegalArgumentException("Kaji could not serialize the request body", error);
        } catch (IOException error) {
            throw new IllegalStateException("Kaji could not execute the request", error);
        } catch (InterruptedException error) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("Kaji request was interrupted", error);
        }
    }

    protected <T> T decode(String response, Class<T> type) {
        try {
            return mapper.readValue(response, type);
        } catch (JsonProcessingException error) {
            throw new IllegalStateException("Kaji could not decode the API response", error);
        }
    }

    protected static String stripTrailingSlash(String value) {
        return value.endsWith("/") ? value.substring(0, value.length() - 1) : value;
    }

    protected static String pathValue(java.lang.Object value) {
        return URLEncoder.encode(String.valueOf(value), StandardCharsets.UTF_8).replace("+", "%20");
    }

    protected static String queryString(List<QueryParameter> query) {
        var parts = new ArrayList<String>();
        for (var parameter : query) {
            if (parameter.value() == null) continue;
            if (parameter.value() instanceof Iterable<?> values) {
                for (var value : values) if (value != null) parts.add(encodeQuery(parameter.name(), value));
            } else {
                parts.add(encodeQuery(parameter.name(), parameter.value()));
            }
        }
        return parts.isEmpty() ? "" : "?" + String.join("&", parts);
    }

    protected static String encodeQuery(String name, java.lang.Object value) {
        return URLEncoder.encode(name, StandardCharsets.UTF_8) + "=" + URLEncoder.encode(String.valueOf(value), StandardCharsets.UTF_8);
    }

    public record QueryParameter(String name, java.lang.Object value) {}

    /** Follow a generated pagination link only on this client's API origin. */
    protected String requestPaginationUrlWithRetry(String method, String continuation, Map<String, String> headers, java.lang.Object body) {
        var url = resolvePaginationUrl(continuation);
        var maxAttempts = retryAllowed(method, headers) ? retry.maxAttempts() : 1;
        RuntimeException lastError = null;
        for (var attempt = 0; attempt < maxAttempts; attempt++) {
            try {
                if (hooks != null) hooks.beforeRequest(method, URI.create(url));
                var builder = HttpRequest.newBuilder(URI.create(url)).timeout(timeout).header("Accept", "application/json");
                defaultHeaders.forEach(builder::header); headers.forEach(builder::header);
                if (apiKey != null && !apiKey.isBlank()) { var credential = apiKeyPrefix == null || apiKeyPrefix.isBlank() ? apiKey : apiKeyPrefix + " " + apiKey; builder.header(apiKeyHeader, credential); }
                if (body == null) builder.method(method, HttpRequest.BodyPublishers.noBody());
                else if (body instanceof byte[] bytes) { builder.header("Content-Type", "application/octet-stream"); builder.method(method, HttpRequest.BodyPublishers.ofByteArray(bytes)); }
                else { builder.header("Content-Type", "application/json"); builder.method(method, HttpRequest.BodyPublishers.ofString(mapper.writeValueAsString(body))); }
                var response = httpClient.send(builder.build(), HttpResponse.BodyHandlers.ofString());
                if (response.statusCode() < 200 || response.statusCode() >= 300) throw new ApiException(response.statusCode(), response.body(), response.headers().firstValue("Retry-After").orElse(null));
                if (hooks != null) hooks.afterResponse(response.statusCode());
                return response.body();
            } catch (JsonProcessingException error) { throw new IllegalArgumentException("Kaji could not serialize the request body", error);
            } catch (ApiException error) {
                lastError = error;
                if (attempt + 1 >= maxAttempts || !retryableStatus(error.statusCode())) { if (hooks != null) hooks.onError(error); throw error; }
                retryDelay(attempt, error.retryAfter());
            } catch (IOException error) {
                lastError = new IllegalStateException("Kaji could not execute the request", error);
                if (attempt + 1 >= maxAttempts) { if (hooks != null) hooks.onError(lastError); throw lastError; }
                retryDelay(attempt, null);
            } catch (InterruptedException error) { Thread.currentThread().interrupt(); throw new IllegalStateException("Kaji request was interrupted", error); }
        }
        if (hooks != null) hooks.onError(lastError);
        throw lastError == null ? new IllegalStateException("Kaji retry loop completed without a response") : lastError;
    }

    protected String resolvePaginationUrl(String continuation) {
        var base = URI.create(baseUrl);
        var next = base.resolve(URI.create(continuation)).normalize();
        if (!Objects.equals(base.getScheme(), next.getScheme()) || !Objects.equals(base.getHost(), next.getHost()) || effectivePort(base) != effectivePort(next)) {
            throw new IllegalArgumentException("Kaji pagination URL must remain on the configured API origin");
        }
        return next.toString();
    }

    protected static int effectivePort(URI uri) {
        if (uri.getPort() >= 0) return uri.getPort();
        return "https".equalsIgnoreCase(uri.getScheme()) ? 443 : 80;
    }

    /** Downloads a non-JSON representation as bytes. */
    protected byte[] requestBinary(String method, String path, List<QueryParameter> query, Map<String, String> headers, java.lang.Object body) {
        var url = baseUrl + path + queryString(query);
        var builder = HttpRequest.newBuilder(URI.create(url)).timeout(timeout).header("Accept", "*/*");
        defaultHeaders.forEach(builder::header); headers.forEach(builder::header);
        if (apiKey != null && !apiKey.isBlank()) { var credential = apiKeyPrefix == null || apiKeyPrefix.isBlank() ? apiKey : apiKeyPrefix + " " + apiKey; builder.header(apiKeyHeader, credential); }
        try {
            if (body == null) builder.method(method, HttpRequest.BodyPublishers.noBody());
            else if (body instanceof byte[] bytes) { builder.header("Content-Type", "application/octet-stream"); builder.method(method, HttpRequest.BodyPublishers.ofByteArray(bytes)); }
            else { builder.header("Content-Type", "application/json"); builder.method(method, HttpRequest.BodyPublishers.ofString(mapper.writeValueAsString(body))); }
            var response = httpClient.send(builder.build(), HttpResponse.BodyHandlers.ofByteArray());
            if (response.statusCode() < 200 || response.statusCode() >= 300) throw new ApiException(response.statusCode(), new String(response.body(), StandardCharsets.UTF_8), response.headers().firstValue("Retry-After").orElse(null));
            if (hooks != null) hooks.afterResponse(response.statusCode());
            return response.body();
        } catch (JsonProcessingException error) { throw new IllegalArgumentException("Kaji could not serialize the request body", error);
        } catch (IOException error) { throw new IllegalStateException("Kaji could not execute the request", error);
        } catch (InterruptedException error) { Thread.currentThread().interrupt(); throw new IllegalStateException("Kaji request was interrupted", error); }
    }

    /** Returns data lines from a text/event-stream endpoint. Close the stream when finished. */
    protected java.util.stream.Stream<String> requestEventStream(String method, String path, List<QueryParameter> query, Map<String, String> headers, java.lang.Object body) {
        var url = baseUrl + path + queryString(query);
        var builder = HttpRequest.newBuilder(URI.create(url)).timeout(timeout).header("Accept", "text/event-stream");
        defaultHeaders.forEach(builder::header); headers.forEach(builder::header);
        if (apiKey != null && !apiKey.isBlank()) { var credential = apiKeyPrefix == null || apiKeyPrefix.isBlank() ? apiKey : apiKeyPrefix + " " + apiKey; builder.header(apiKeyHeader, credential); }
        try {
            if (body == null) builder.method(method, HttpRequest.BodyPublishers.noBody());
            else if (body instanceof byte[] bytes) { builder.header("Content-Type", "application/octet-stream"); builder.method(method, HttpRequest.BodyPublishers.ofByteArray(bytes)); }
            else { builder.header("Content-Type", "application/json"); builder.method(method, HttpRequest.BodyPublishers.ofString(mapper.writeValueAsString(body))); }
            var response = httpClient.send(builder.build(), HttpResponse.BodyHandlers.ofLines());
            if (response.statusCode() < 200 || response.statusCode() >= 300) { try (var lines = response.body()) { throw new ApiException(response.statusCode(), lines.reduce("", (a, b) -> a + "\n" + b), response.headers().firstValue("Retry-After").orElse(null)); } }
            if (hooks != null) hooks.afterResponse(response.statusCode());
            return response.body().filter(line -> !line.isEmpty() && !line.startsWith(":")).map(line -> line.startsWith("data:") ? line.substring(5).stripLeading() : line);
        } catch (JsonProcessingException error) { throw new IllegalArgumentException("Kaji could not serialize the request body", error);
        } catch (IOException error) { throw new IllegalStateException("Kaji could not execute the event stream", error);
        } catch (InterruptedException error) { Thread.currentThread().interrupt(); throw new IllegalStateException("Kaji request was interrupted", error); }
    }

    protected String requestWithRetry(String method, String path, List<QueryParameter> query, Map<String, String> headers, java.lang.Object body) {
        var maxAttempts = retryAllowed(method, headers) ? retry.maxAttempts() : 1;
        RuntimeException lastError = null;
        for (var attempt = 0; attempt < maxAttempts; attempt++) {
            try {
                if (hooks != null) hooks.beforeRequest(method, URI.create(baseUrl + path + queryString(query)));
                var response = request(method, path, query, headers, body);
                return response;
            } catch (ApiException error) {
                lastError = error;
                if (attempt + 1 >= maxAttempts || !retryableStatus(error.statusCode())) {
                    if (hooks != null) hooks.onError(error);
                    throw error;
                }
                retryDelay(attempt, error.retryAfter());
            } catch (IllegalStateException error) {
                lastError = error;
                if (attempt + 1 >= maxAttempts || !(error.getCause() instanceof IOException)) {
                    if (hooks != null) hooks.onError(error);
                    throw error;
                }
                retryDelay(attempt, null);
            }
        }
        if (hooks != null) hooks.onError(lastError);
        throw lastError == null ? new IllegalStateException("Kaji retry loop completed without a response") : lastError;
    }

    protected boolean retryAllowed(String method, Map<String, String> headers) {
        var normalized = method.toUpperCase(Locale.ROOT);
        return normalized.equals("GET") || normalized.equals("PUT") || normalized.equals("PATCH") || normalized.equals("DELETE")
            || (normalized.equals("POST") && headers.keySet().stream().anyMatch(name -> name.equalsIgnoreCase("Idempotency-Key")));
    }

    protected static boolean retryableStatus(int status) {
        return status == 408 || status == 429 || status == 500 || status == 502 || status == 503 || status == 504;
    }

    protected void retryDelay(int attempt, String retryAfter) {
        long delay = retryAfterDelay(retryAfter);
        if (delay < 0) {
            var exponential = retry.initialDelay().toMillis() * (1L << Math.min(attempt, 30));
            delay = Math.min(exponential, retry.maxDelay().toMillis());
        }
        try {
            if (delay > 0) Thread.sleep(delay);
        } catch (InterruptedException error) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("Kaji retry was interrupted", error);
        }
    }

    protected static long retryAfterDelay(String value) {
        if (value == null || value.isBlank()) return -1;
        try {
            return Math.max(0, (long) (Double.parseDouble(value.trim()) * 1000));
        } catch (NumberFormatException ignored) {
            return -1;
        }
    }
}
