package app.relevate.sdk;

import app.relevate.sdk.internal.resources.ContactsResourcePart000;

// Generated by Kaji. Do not edit.

/** Typed namespace for Contacts operations. */
public final class ContactsResource extends ContactsResourcePart000 {
    ContactsResource(Client client) { super(client); }
}
