package app.relevate.sdk;

import app.relevate.sdk.internal.resources.CrmResourcePart000;

// Generated by Kaji. Do not edit.

/** Typed namespace for Crm operations. */
public final class CrmResource extends CrmResourcePart000 {
    CrmResource(Client client) { super(client); }
}
