package app.relevate.sdk;

import app.relevate.sdk.internal.resources.EventsResourcePart000;

// Generated by Kaji. Do not edit.

/** Typed namespace for Events operations. */
public final class EventsResource extends EventsResourcePart000 {
    EventsResource(Client client) { super(client); }
}
