package app.relevate.sdk;

import app.relevate.sdk.internal.resources.InboundResourcePart000;

// Generated by Kaji. Do not edit.

/** Typed namespace for Inbound operations. */
public final class InboundResource extends InboundResourcePart000 {
    InboundResource(Client client) { super(client); }
}
