package app.relevate.sdk;

import app.relevate.sdk.internal.resources.SenderIdentitiesResourcePart000;

// Generated by Kaji. Do not edit.

/** Typed namespace for SenderIdentities operations. */
public final class SenderIdentitiesResource extends SenderIdentitiesResourcePart000 {
    SenderIdentitiesResource(Client client) { super(client); }
}
