/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { Contact } from './Contact.js'

export type ContactListResponse = {
  api_version: string
  data: Contact[]
}
