/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

export type CreateContact = {
  attributes?: {
  [key: string]: unknown
} | null
  email: string
  first_name?: string | null
  last_name?: string | null
  locale?: string | null
}
