/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

export type CrmAttributeCreate = {
  currency_code?: string | null
  expression?: string | null
  key: string
  multiple?: boolean
  name: string
  options?: string[]
  required?: boolean
  target_object_id?: string | null
  type: 'text' | 'number' | 'currency' | 'phone' | 'rating' | 'location' | 'multi_select' | 'status' | 'relationship' | 'formula' | 'boolean' | 'date' | 'timestamp' | 'select' | 'record' | 'user'
}
