/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

export type CrmList = {
  created_at: string
  description: string
  id: string
  name: string
  object_id: string
  updated_at: string
}
