/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmMetadataDeletedData } from './CrmMetadataDeletedData.js'

export type CrmMetadataDeleted = {
  api_version: string
  data: CrmMetadataDeletedData
}
