/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmMetadataAttribute } from './CrmMetadataAttribute.js'

export type CrmMetadataAttributeResponse = {
  api_version: string
  data: CrmMetadataAttribute
}
