/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmNoteDocument } from './CrmNoteDocument.js'
import type { CrmNoteMention } from './CrmNoteMention.js'

export type CrmNoteWrite = {
  body?: string
  content?: CrmNoteDocument | null
  mentions?: CrmNoteMention[]
  title?: string
}
