/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmQualityIssue } from './CrmQualityIssue.js'

export type CrmQualityRecord = {
  display_name: string
  duplicate_candidate_count: number
  duplicate_candidates: {
  display_name: string
  record_id: string
}[]
  issues: CrmQualityIssue[]
  record_id: string
}
