/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { CrmQualityRecord } from './CrmQualityRecord.js'

export type CrmQualityResponse = {
  api_version: string
  data: {
  notice: string
  object_id: string
  records: CrmQualityRecord[]
  scanned_records: number
  summary: {
  broken_references: number
  duplicate_candidates: number
  invalid_values: number
  missing_required: number
  records_with_issues: number
}
}
  page: {
  limit?: number
  next_cursor?: string | null
}
}
