/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

export type CrmRecord = {
  archived_at?: string | null
  created_at?: string
  display_name: string
  external_id?: string | null
  id: string
  object_id: string
  updated_at?: string
  values: {
  [key: string]: unknown
}
}
