/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

export type CrmTask = {
  completed_at?: string | null
  created_at: string
  description: string
  due_at: string
  due_timezone: string
  id: string
  owner_id?: string | null
  record_id: string
  status: 'open' | 'completed'
  title: string
  updated_at: string
}
