/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

export type Segment = {
  created_at: string
  definition: unknown
  id: string
  kind: string
  last_evaluated_at?: string | null
  name: string
  status: string
  updated_at: string
  version: number
}
