/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { Webhook } from './Webhook.js'

export type WebhookListResponse = {
  api_version: string
  data: Webhook[]
}
