# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Resources.Sends.Chunk0000 do
  @moduledoc false

  alias RelevateSdk.{API, Client}

  @spec create(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def create(client, options \\ []), do: API.create(client, options)

  @spec query(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def query(client, options \\ []), do: API.query(client, options)

  @spec cancel(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def cancel(client, options \\ []), do: API.cancel(client, options)

  @spec get(Client.t(), keyword()) :: {:ok, term()} | {:error, term()}
  def get(client, options \\ []), do: API.get(client, options)
end
