// <auto-generated />
// Generated by Kaji. Do not edit.

using System.Globalization;
using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kaji.RelevateSdk;

/// <summary>Configures a <see cref="KajiClient"/> instance.</summary>
public sealed record KajiClientOptions
{
    /// <summary>Absolute API base URL, for example <c>https://api.example.com</c>.</summary>
    public required string BaseUrl { get; init; }

    public string? ApiKey { get; init; }

    public string ApiKeyHeader { get; init; } = "Authorization";

    /// <summary>Prefix sent before the API key, such as <c>Bearer</c>.</summary>
    public string? ApiKeyPrefix { get; init; } = "Bearer";

    /// <summary>Null selects Kaji's safe three-attempt policy; set MaxAttempts to 1 to disable retries.</summary>
    public KajiRetryOptions? Retry { get; init; }

    public IKajiClientHooks? Hooks { get; init; }
}

/// <summary>Configures retries for idempotent requests.</summary>
public sealed record KajiRetryOptions
{
    public int MaxAttempts { get; init; } = 3;
    public TimeSpan InitialDelay { get; init; } = TimeSpan.FromMilliseconds(250);
    public TimeSpan MaxDelay { get; init; } = TimeSpan.FromSeconds(8);
}

/// <summary>Optional lifecycle callbacks for package telemetry and policy.</summary>
public interface IKajiClientHooks
{
    void BeforeRequest(HttpRequestMessage request) { }
    void AfterResponse(HttpResponseMessage response) { }
    void OnError(Exception error) { }
}

/// <summary>Typed asynchronous client for Relevate.</summary>
public sealed partial class KajiClient
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };

    private readonly HttpClient _httpClient;
    private readonly Uri _baseUri;
    private readonly string? _apiKey;
    private readonly string _apiKeyHeader;
    private readonly string? _apiKeyPrefix;
    private readonly KajiRetryOptions _retry;
    private readonly IKajiClientHooks? _hooks;

    public KajiClient(HttpClient httpClient, KajiClientOptions options)
    {
        _httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
        ArgumentNullException.ThrowIfNull(options);
        _baseUri = new Uri(options.BaseUrl.TrimEnd('/') + "/", UriKind.Absolute);
        _apiKey = options.ApiKey;
        _apiKeyHeader = options.ApiKeyHeader;
        _apiKeyPrefix = options.ApiKeyPrefix;
        _retry = options.Retry ?? new KajiRetryOptions();
        if (_retry.MaxAttempts < 1) throw new ArgumentOutOfRangeException(nameof(options.Retry), "MaxAttempts must be at least 1.");
        _hooks = options.Hooks;
        AuthCheck = new AuthCheckResource(this);
        Contacts = new ContactsResource(this);
        Crm = new CrmResource(this);
        Domains = new DomainsResource(this);
        Events = new EventsResource(this);
        Inbound = new InboundResource(this);
        Segments = new SegmentsResource(this);
        SenderIdentities = new SenderIdentitiesResource(this);
        Sends = new SendsResource(this);
        Webhooks = new WebhooksResource(this);
    }

    /// <summary>Operations in the AuthCheck resource.</summary>
    public AuthCheckResource AuthCheck { get; }
    /// <summary>Operations in the Contacts resource.</summary>
    public ContactsResource Contacts { get; }
    /// <summary>Operations in the Crm resource.</summary>
    public CrmResource Crm { get; }
    /// <summary>Operations in the Domains resource.</summary>
    public DomainsResource Domains { get; }
    /// <summary>Operations in the Events resource.</summary>
    public EventsResource Events { get; }
    /// <summary>Operations in the Inbound resource.</summary>
    public InboundResource Inbound { get; }
    /// <summary>Operations in the Segments resource.</summary>
    public SegmentsResource Segments { get; }
    /// <summary>Operations in the SenderIdentities resource.</summary>
    public SenderIdentitiesResource SenderIdentities { get; }
    /// <summary>Operations in the Sends resource.</summary>
    public SendsResource Sends { get; }
    /// <summary>Operations in the Webhooks resource.</summary>
    public WebhooksResource Webhooks { get; }

    private HttpRequestMessage CreateRequest(HttpMethod method, string path, List<KeyValuePair<string, string?>>? query = null)
    {
        var uri = new Uri(_baseUri, path.TrimStart('/'));
        if (query is { Count: > 0 })
        {
            var encoded = string.Join("&", query
                .Where(item => item.Value is not null)
                .Select(item => $"{Uri.EscapeDataString(item.Key)}={Uri.EscapeDataString(item.Value!)}"));
            if (!string.IsNullOrEmpty(encoded))
            {
                var builder = new UriBuilder(uri) { Query = encoded };
                uri = builder.Uri;
            }
        }

        var request = new HttpRequestMessage(method, uri);
        request.Headers.Accept.ParseAdd("application/json");
        if (!string.IsNullOrWhiteSpace(_apiKey))
        {
            var credential = string.IsNullOrWhiteSpace(_apiKeyPrefix)
                ? _apiKey
                : $"{_apiKeyPrefix} {_apiKey}";
            request.Headers.TryAddWithoutValidation(_apiKeyHeader, credential);
        }
        return request;
    }

    private async Task<T> SendAsync<T>(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        using var _request = request;
        using var response = await _httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        var contents = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
        if (!response.IsSuccessStatusCode)
        {
            throw new ApiException((int)response.StatusCode, contents);
        }
        if (string.IsNullOrWhiteSpace(contents))
        {
            return default!;
        }
        return JsonSerializer.Deserialize<T>(contents, JsonOptions)
            ?? throw new JsonException("Kaji received an empty JSON response.");
    }

    private async Task SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        using var _request = request;
        using var response = await _httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        var contents = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
        if (!response.IsSuccessStatusCode)
        {
            throw new ApiException((int)response.StatusCode, contents);
        }
    }

    private static string ParameterString<T>(T value)
    {
        return value switch
        {
            null => string.Empty,
            bool boolean => boolean ? "true" : "false",
            IFormattable formattable => formattable.ToString(null, CultureInfo.InvariantCulture) ?? string.Empty,
            _ => value.ToString() ?? string.Empty,
        };
    }

    // The template request is cloned for every attempt: HttpRequestMessage instances
    // are single-use, and replaying an unsafe POST would be incorrect.
    private async Task<T> SendWithRetryAsync<T>(HttpRequestMessage template, CancellationToken cancellationToken)
    {
        using (template)
        {
            var maxAttempts = IsRetryAllowed(template) ? Math.Max(1, _retry.MaxAttempts) : 1;
            Exception? transportError = null;
            for (var attempt = 0; attempt < maxAttempts; attempt++)
            {
                using var request = await CloneRequestAsync(template, cancellationToken).ConfigureAwait(false);
                try
                {
                    _hooks?.BeforeRequest(request);
                    using var response = await _httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    if (attempt + 1 < maxAttempts && IsRetryable(response.StatusCode))
                    {
                        await DelayForRetryAsync(attempt, response.Headers.RetryAfter, cancellationToken).ConfigureAwait(false);
                        continue;
                    }
                    var contents = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                    if (!response.IsSuccessStatusCode)
                    {
                        throw new ApiException((int)response.StatusCode, contents);
                    }
                    _hooks?.AfterResponse(response);
                    if (string.IsNullOrWhiteSpace(contents)) return default!;
                    return JsonSerializer.Deserialize<T>(contents, JsonOptions)
                        ?? throw new JsonException("Kaji received an empty JSON response.");
                }
                catch (HttpRequestException error) when (attempt + 1 < maxAttempts)
                {
                    transportError = error;
                    await DelayForRetryAsync(attempt, null, cancellationToken).ConfigureAwait(false);
                }
                catch (Exception error)
                {
                    _hooks?.OnError(error);
                    throw;
                }
            }
            _hooks?.OnError(transportError ?? new HttpRequestException("Kaji retry loop completed without a response."));
            throw transportError ?? new HttpRequestException("Kaji retry loop completed without a response.");
        }
    }

    private async Task SendWithRetryAsync(HttpRequestMessage template, CancellationToken cancellationToken)
    {
        await SendWithRetryAsync<JsonElement>(template, cancellationToken).ConfigureAwait(false);
    }

    private static bool IsRetryAllowed(HttpRequestMessage request)
    {
        return request.Method == HttpMethod.Get || request.Method == HttpMethod.Put || request.Method == HttpMethod.Patch || request.Method == HttpMethod.Delete
            || (request.Method == HttpMethod.Post && request.Headers.Contains("Idempotency-Key"));
    }

    private static bool IsRetryable(HttpStatusCode status)
    {
        return status is HttpStatusCode.RequestTimeout or (HttpStatusCode)429 or HttpStatusCode.InternalServerError or HttpStatusCode.BadGateway or HttpStatusCode.ServiceUnavailable or HttpStatusCode.GatewayTimeout;
    }

    private async Task DelayForRetryAsync(int attempt, RetryConditionHeaderValue? retryAfter, CancellationToken cancellationToken)
    {
        var delay = retryAfter?.Delta ?? (retryAfter?.Date is { } date ? date - DateTimeOffset.UtcNow : TimeSpan.Zero);
        if (delay <= TimeSpan.Zero)
        {
            var multiplier = Math.Pow(2, attempt);
            delay = TimeSpan.FromMilliseconds(_retry.InitialDelay.TotalMilliseconds * multiplier);
        }
        delay = delay > _retry.MaxDelay ? _retry.MaxDelay : delay;
        if (delay > TimeSpan.Zero) await Task.Delay(delay, cancellationToken).ConfigureAwait(false);
    }

    private static async Task<HttpRequestMessage> CloneRequestAsync(HttpRequestMessage source, CancellationToken cancellationToken)
    {
        var clone = new HttpRequestMessage(source.Method, source.RequestUri);
        foreach (var header in source.Headers) clone.Headers.TryAddWithoutValidation(header.Key, header.Value);
        if (source.Content is not null)
        {
            var bytes = await source.Content.ReadAsByteArrayAsync(cancellationToken).ConfigureAwait(false);
            clone.Content = new ByteArrayContent(bytes);
            foreach (var header in source.Content.Headers) clone.Content.Headers.TryAddWithoutValidation(header.Key, header.Value);
        }
        return clone;
    }

    /// <summary>Downloads a non-JSON representation without attempting JSON deserialization.</summary>
    private async Task<byte[]> SendBytesAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        using var _request = request;
        using var response = await _httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        var bytes = await response.Content.ReadAsByteArrayAsync(cancellationToken).ConfigureAwait(false);
        if (!response.IsSuccessStatusCode)
        {
            var error = new ApiException((int)response.StatusCode, Encoding.UTF8.GetString(bytes));
            _hooks?.OnError(error);
            throw error;
        }
        _hooks?.AfterResponse(response);
        return bytes;
    }

    /// <summary>Yields payloads from an OpenAPI text/event-stream response. The underlying response is disposed when enumeration ends.</summary>
    private async IAsyncEnumerable<string> StreamSseAsync(HttpRequestMessage request, [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken)
    {
        using var _request = request;
        using var response = await _httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        if (!response.IsSuccessStatusCode)
        {
            var body = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
            var error = new ApiException((int)response.StatusCode, body);
            _hooks?.OnError(error);
            throw error;
        }
        _hooks?.AfterResponse(response);
        await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken).ConfigureAwait(false);
        using var reader = new StreamReader(stream);
        while (!reader.EndOfStream)
        {
            var line = await reader.ReadLineAsync(cancellationToken).ConfigureAwait(false);
            if (string.IsNullOrEmpty(line) || line.StartsWith(":", StringComparison.Ordinal)) continue;
            yield return line.StartsWith("data:", StringComparison.Ordinal) ? line[5..].TrimStart() : line;
        }
    }

    private static T? TryDeserializeError<T>(string contents)
    {
        if (string.IsNullOrWhiteSpace(contents)) return default;
        try { return JsonSerializer.Deserialize<T>(contents, JsonOptions); }
        catch (JsonException) { return default; }
    }

    // Limited JSONPath evaluator for declared cursor output paths. It accepts only $.field.nestedField; unsupported expressions stop the pager rather than guessing.
    private static string? KajiJsonPath(JsonElement value, string path)
    {
        if (!path.StartsWith('$')) return null;
        var current = value;
        foreach (var segment in path[1..].Split('.', StringSplitOptions.RemoveEmptyEntries))
        {
            if (current.ValueKind != JsonValueKind.Object || !current.TryGetProperty(segment, out current)) return null;
        }
        return current.ValueKind == JsonValueKind.String ? current.GetString() : null;
    }
}
