# Generated by Kaji. Do not edit.

defmodule RelevateSdk.API.Operations0001 do
  @moduledoc false

  alias RelevateSdk.Client

  @type update_crm_object_attribute_option :: {:object, String.t()} | {:attribute, String.t()} | {:body, RelevateSdk.Models.CrmAttributePatch.t()}
  @spec update_crm_object_attribute(Client.t(), [update_crm_object_attribute_option()]) :: {:ok, RelevateSdk.Models.CrmMetadataAttributeResponse.t()} | {:error, term()}
  def update_crm_object_attribute(client, options \\ []) when is_list(options) do
    with {:ok, object} <- Client.required(options, :object),
         {:ok, attribute} <- Client.required(options, :attribute),
         {:ok, body} <- Client.required(options, :body) do
      path = "/v1/crm/objects/{object}/attributes/{attribute}"
      path = String.replace(path, "{object}", URI.encode(to_string(object), &URI.char_unreserved?/1))
      path = String.replace(path, "{attribute}", URI.encode(to_string(attribute), &URI.char_unreserved?/1))
      query = []
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :patch, path, query, headers, body, :json, :json, %{400 => RelevateSdk.Errors.UpdateCrmObjectAttributeStatus400Error, 401 => RelevateSdk.Errors.UpdateCrmObjectAttributeStatus401Error, 403 => RelevateSdk.Errors.UpdateCrmObjectAttributeStatus403Error, 404 => RelevateSdk.Errors.UpdateCrmObjectAttributeStatus404Error, 409 => RelevateSdk.Errors.UpdateCrmObjectAttributeStatus409Error, 413 => RelevateSdk.Errors.UpdateCrmObjectAttributeStatus413Error, 415 => RelevateSdk.Errors.UpdateCrmObjectAttributeStatus415Error, 503 => RelevateSdk.Errors.UpdateCrmObjectAttributeStatus503Error}) do
        {:ok, response} -> {:ok, case response do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmMetadataAttributeResponse.from_map(map); other -> other end}
        {:error, %RelevateSdk.Errors.UpdateCrmObjectAttributeStatus400Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmObjectAttributeStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmObjectAttributeStatus403Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmObjectAttributeStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmObjectAttributeStatus409Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmObjectAttributeStatus413Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmObjectAttributeStatus415Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmObjectAttributeStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type preview_crm_object_deletion_option :: {:object, String.t()}
  @spec preview_crm_object_deletion(Client.t(), [preview_crm_object_deletion_option()]) :: {:ok, RelevateSdk.Models.CrmObjectDeletionPreview.t()} | {:error, term()}
  def preview_crm_object_deletion(client, options \\ []) when is_list(options) do
    with {:ok, object} <- Client.required(options, :object) do
      path = "/v1/crm/objects/{object}/deletion-preview"
      path = String.replace(path, "{object}", URI.encode(to_string(object), &URI.char_unreserved?/1))
      query = []
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :get, path, query, headers, nil, :json, :json, %{400 => RelevateSdk.Errors.PreviewCrmObjectDeletionStatus400Error, 401 => RelevateSdk.Errors.PreviewCrmObjectDeletionStatus401Error, 403 => RelevateSdk.Errors.PreviewCrmObjectDeletionStatus403Error, 404 => RelevateSdk.Errors.PreviewCrmObjectDeletionStatus404Error, 409 => RelevateSdk.Errors.PreviewCrmObjectDeletionStatus409Error, 413 => RelevateSdk.Errors.PreviewCrmObjectDeletionStatus413Error, 415 => RelevateSdk.Errors.PreviewCrmObjectDeletionStatus415Error, 503 => RelevateSdk.Errors.PreviewCrmObjectDeletionStatus503Error}) do
        {:ok, response} -> {:ok, case response do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmObjectDeletionPreview.from_map(map); other -> other end}
        {:error, %RelevateSdk.Errors.PreviewCrmObjectDeletionStatus400Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.PreviewCrmObjectDeletionStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.PreviewCrmObjectDeletionStatus403Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.PreviewCrmObjectDeletionStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.PreviewCrmObjectDeletionStatus409Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.PreviewCrmObjectDeletionStatus413Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.PreviewCrmObjectDeletionStatus415Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.PreviewCrmObjectDeletionStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type get_crm_object_quality_option :: {:object, String.t()} | {:limit, integer()} | {:after_, String.t()} | {:include_archived, boolean()}
  @spec get_crm_object_quality(Client.t(), [get_crm_object_quality_option()]) :: {:ok, RelevateSdk.Models.CrmQualityResponse.t()} | {:error, term()}
  def get_crm_object_quality(client, options \\ []) when is_list(options) do
    with {:ok, object} <- Client.required(options, :object) do
      path = "/v1/crm/objects/{object}/quality"
      path = String.replace(path, "{object}", URI.encode(to_string(object), &URI.char_unreserved?/1))
      query = [{"limit", Keyword.get(options, :limit)}, {"after", Keyword.get(options, :after_)}, {"include_archived", Keyword.get(options, :include_archived)}]
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :get, path, query, headers, nil, :json, :json, %{400 => RelevateSdk.Errors.GetCrmObjectQualityStatus400Error, 401 => RelevateSdk.Errors.GetCrmObjectQualityStatus401Error, 403 => RelevateSdk.Errors.GetCrmObjectQualityStatus403Error, 404 => RelevateSdk.Errors.GetCrmObjectQualityStatus404Error, 409 => RelevateSdk.Errors.GetCrmObjectQualityStatus409Error, 413 => RelevateSdk.Errors.GetCrmObjectQualityStatus413Error, 415 => RelevateSdk.Errors.GetCrmObjectQualityStatus415Error, 503 => RelevateSdk.Errors.GetCrmObjectQualityStatus503Error}) do
        {:ok, response} -> {:ok, case response do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmQualityResponse.from_map(map); other -> other end}
        {:error, %RelevateSdk.Errors.GetCrmObjectQualityStatus400Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmObjectQualityStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmObjectQualityStatus403Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmObjectQualityStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmObjectQualityStatus409Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmObjectQualityStatus413Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmObjectQualityStatus415Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmObjectQualityStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type list_crm_records_option :: {:object, String.t()} | {:limit, integer()} | {:after_, String.t()} | {:external_id, String.t()} | {:include_archived, boolean()}
  @spec list_crm_records(Client.t(), [list_crm_records_option()]) :: {:ok, map()} | {:error, term()}
  def list_crm_records(client, options \\ []) when is_list(options) do
    with {:ok, object} <- Client.required(options, :object) do
      path = "/v1/crm/objects/{object}/records"
      path = String.replace(path, "{object}", URI.encode(to_string(object), &URI.char_unreserved?/1))
      query = [{"limit", Keyword.get(options, :limit)}, {"after", Keyword.get(options, :after_)}, {"external_id", Keyword.get(options, :external_id)}, {"include_archived", Keyword.get(options, :include_archived)}]
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :get, path, query, headers, nil, :json, :json, %{400 => RelevateSdk.Errors.ListCrmRecordsStatus400Error, 401 => RelevateSdk.Errors.ListCrmRecordsStatus401Error, 403 => RelevateSdk.Errors.ListCrmRecordsStatus403Error, 404 => RelevateSdk.Errors.ListCrmRecordsStatus404Error, 409 => RelevateSdk.Errors.ListCrmRecordsStatus409Error, 413 => RelevateSdk.Errors.ListCrmRecordsStatus413Error, 415 => RelevateSdk.Errors.ListCrmRecordsStatus415Error, 503 => RelevateSdk.Errors.ListCrmRecordsStatus503Error}) do
        {:ok, response} -> {:ok, response}
        {:error, %RelevateSdk.Errors.ListCrmRecordsStatus400Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmRecordsStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmRecordsStatus403Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmRecordsStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmRecordsStatus409Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmRecordsStatus413Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmRecordsStatus415Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmRecordsStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type create_crm_record_option :: {:object, String.t()} | {:body, RelevateSdk.Models.CrmRecordCreate.t()}
  @spec create_crm_record(Client.t(), [create_crm_record_option()]) :: {:ok, RelevateSdk.Models.CrmRecordResponse.t()} | {:error, term()}
  def create_crm_record(client, options \\ []) when is_list(options) do
    with {:ok, object} <- Client.required(options, :object),
         {:ok, body} <- Client.required(options, :body) do
      path = "/v1/crm/objects/{object}/records"
      path = String.replace(path, "{object}", URI.encode(to_string(object), &URI.char_unreserved?/1))
      query = []
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :post, path, query, headers, body, :json, :json, %{400 => RelevateSdk.Errors.CreateCrmRecordStatus400Error, 401 => RelevateSdk.Errors.CreateCrmRecordStatus401Error, 403 => RelevateSdk.Errors.CreateCrmRecordStatus403Error, 404 => RelevateSdk.Errors.CreateCrmRecordStatus404Error, 409 => RelevateSdk.Errors.CreateCrmRecordStatus409Error, 413 => RelevateSdk.Errors.CreateCrmRecordStatus413Error, 415 => RelevateSdk.Errors.CreateCrmRecordStatus415Error, 503 => RelevateSdk.Errors.CreateCrmRecordStatus503Error}) do
        {:ok, response} -> {:ok, case response do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmRecordResponse.from_map(map); other -> other end}
        {:error, %RelevateSdk.Errors.CreateCrmRecordStatus400Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmRecordStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmRecordStatus403Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmRecordStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmRecordStatus409Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmRecordStatus413Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmRecordStatus415Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmRecordStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type upsert_crm_record_option :: {:object, String.t()} | {:body, RelevateSdk.Models.CrmUpsert.t()}
  @spec upsert_crm_record(Client.t(), [upsert_crm_record_option()]) :: {:ok, RelevateSdk.Models.CrmRecordResponse.t()} | {:error, term()}
  def upsert_crm_record(client, options \\ []) when is_list(options) do
    with {:ok, object} <- Client.required(options, :object),
         {:ok, body} <- Client.required(options, :body) do
      path = "/v1/crm/objects/{object}/records/upsert"
      path = String.replace(path, "{object}", URI.encode(to_string(object), &URI.char_unreserved?/1))
      query = []
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :post, path, query, headers, body, :json, :json, %{400 => RelevateSdk.Errors.UpsertCrmRecordStatus400Error, 401 => RelevateSdk.Errors.UpsertCrmRecordStatus401Error, 403 => RelevateSdk.Errors.UpsertCrmRecordStatus403Error, 404 => RelevateSdk.Errors.UpsertCrmRecordStatus404Error, 409 => RelevateSdk.Errors.UpsertCrmRecordStatus409Error, 413 => RelevateSdk.Errors.UpsertCrmRecordStatus413Error, 415 => RelevateSdk.Errors.UpsertCrmRecordStatus415Error, 503 => RelevateSdk.Errors.UpsertCrmRecordStatus503Error}) do
        {:ok, response} -> {:ok, case response do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmRecordResponse.from_map(map); other -> other end}
        {:error, %RelevateSdk.Errors.UpsertCrmRecordStatus400Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpsertCrmRecordStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpsertCrmRecordStatus403Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpsertCrmRecordStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpsertCrmRecordStatus409Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpsertCrmRecordStatus413Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpsertCrmRecordStatus415Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpsertCrmRecordStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type archive_crm_record_option :: {:record_id, String.t()}
  @spec archive_crm_record(Client.t(), [archive_crm_record_option()]) :: {:ok, RelevateSdk.Models.CrmRecordResponse.t()} | {:error, term()}
  def archive_crm_record(client, options \\ []) when is_list(options) do
    with {:ok, record_id} <- Client.required(options, :record_id) do
      path = "/v1/crm/records/{record_id}"
      path = String.replace(path, "{record_id}", URI.encode(to_string(record_id), &URI.char_unreserved?/1))
      query = []
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :delete, path, query, headers, nil, :json, :json, %{400 => RelevateSdk.Errors.ArchiveCrmRecordStatus400Error, 401 => RelevateSdk.Errors.ArchiveCrmRecordStatus401Error, 403 => RelevateSdk.Errors.ArchiveCrmRecordStatus403Error, 404 => RelevateSdk.Errors.ArchiveCrmRecordStatus404Error, 409 => RelevateSdk.Errors.ArchiveCrmRecordStatus409Error, 413 => RelevateSdk.Errors.ArchiveCrmRecordStatus413Error, 415 => RelevateSdk.Errors.ArchiveCrmRecordStatus415Error, 503 => RelevateSdk.Errors.ArchiveCrmRecordStatus503Error}) do
        {:ok, response} -> {:ok, case response do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmRecordResponse.from_map(map); other -> other end}
        {:error, %RelevateSdk.Errors.ArchiveCrmRecordStatus400Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ArchiveCrmRecordStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ArchiveCrmRecordStatus403Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ArchiveCrmRecordStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ArchiveCrmRecordStatus409Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ArchiveCrmRecordStatus413Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ArchiveCrmRecordStatus415Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ArchiveCrmRecordStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type get_crm_record_option :: {:record_id, String.t()}
  @spec get_crm_record(Client.t(), [get_crm_record_option()]) :: {:ok, RelevateSdk.Models.CrmRecordResponse.t()} | {:error, term()}
  def get_crm_record(client, options \\ []) when is_list(options) do
    with {:ok, record_id} <- Client.required(options, :record_id) do
      path = "/v1/crm/records/{record_id}"
      path = String.replace(path, "{record_id}", URI.encode(to_string(record_id), &URI.char_unreserved?/1))
      query = []
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :get, path, query, headers, nil, :json, :json, %{400 => RelevateSdk.Errors.GetCrmRecordStatus400Error, 401 => RelevateSdk.Errors.GetCrmRecordStatus401Error, 403 => RelevateSdk.Errors.GetCrmRecordStatus403Error, 404 => RelevateSdk.Errors.GetCrmRecordStatus404Error, 409 => RelevateSdk.Errors.GetCrmRecordStatus409Error, 413 => RelevateSdk.Errors.GetCrmRecordStatus413Error, 415 => RelevateSdk.Errors.GetCrmRecordStatus415Error, 503 => RelevateSdk.Errors.GetCrmRecordStatus503Error}) do
        {:ok, response} -> {:ok, case response do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmRecordResponse.from_map(map); other -> other end}
        {:error, %RelevateSdk.Errors.GetCrmRecordStatus400Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmRecordStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmRecordStatus403Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmRecordStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmRecordStatus409Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmRecordStatus413Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmRecordStatus415Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmRecordStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type update_crm_record_option :: {:record_id, String.t()} | {:body, RelevateSdk.Models.CrmRecordPatch.t()}
  @spec update_crm_record(Client.t(), [update_crm_record_option()]) :: {:ok, RelevateSdk.Models.CrmRecordResponse.t()} | {:error, term()}
  def update_crm_record(client, options \\ []) when is_list(options) do
    with {:ok, record_id} <- Client.required(options, :record_id),
         {:ok, body} <- Client.required(options, :body) do
      path = "/v1/crm/records/{record_id}"
      path = String.replace(path, "{record_id}", URI.encode(to_string(record_id), &URI.char_unreserved?/1))
      query = []
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :patch, path, query, headers, body, :json, :json, %{400 => RelevateSdk.Errors.UpdateCrmRecordStatus400Error, 401 => RelevateSdk.Errors.UpdateCrmRecordStatus401Error, 403 => RelevateSdk.Errors.UpdateCrmRecordStatus403Error, 404 => RelevateSdk.Errors.UpdateCrmRecordStatus404Error, 409 => RelevateSdk.Errors.UpdateCrmRecordStatus409Error, 413 => RelevateSdk.Errors.UpdateCrmRecordStatus413Error, 415 => RelevateSdk.Errors.UpdateCrmRecordStatus415Error, 503 => RelevateSdk.Errors.UpdateCrmRecordStatus503Error}) do
        {:ok, response} -> {:ok, case response do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmRecordResponse.from_map(map); other -> other end}
        {:error, %RelevateSdk.Errors.UpdateCrmRecordStatus400Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmRecordStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmRecordStatus403Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmRecordStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmRecordStatus409Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmRecordStatus413Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmRecordStatus415Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmRecordStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type list_crm_activities_option :: {:record_id, String.t()} | {:limit, integer()} | {:after_, String.t()}
  @spec list_crm_activities(Client.t(), [list_crm_activities_option()]) :: {:ok, map()} | {:error, term()}
  def list_crm_activities(client, options \\ []) when is_list(options) do
    with {:ok, record_id} <- Client.required(options, :record_id) do
      path = "/v1/crm/records/{record_id}/activities"
      path = String.replace(path, "{record_id}", URI.encode(to_string(record_id), &URI.char_unreserved?/1))
      query = [{"limit", Keyword.get(options, :limit)}, {"after", Keyword.get(options, :after_)}]
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :get, path, query, headers, nil, :json, :json, %{400 => RelevateSdk.Errors.ListCrmActivitiesStatus400Error, 401 => RelevateSdk.Errors.ListCrmActivitiesStatus401Error, 403 => RelevateSdk.Errors.ListCrmActivitiesStatus403Error, 404 => RelevateSdk.Errors.ListCrmActivitiesStatus404Error, 409 => RelevateSdk.Errors.ListCrmActivitiesStatus409Error, 413 => RelevateSdk.Errors.ListCrmActivitiesStatus413Error, 415 => RelevateSdk.Errors.ListCrmActivitiesStatus415Error, 503 => RelevateSdk.Errors.ListCrmActivitiesStatus503Error}) do
        {:ok, response} -> {:ok, response}
        {:error, %RelevateSdk.Errors.ListCrmActivitiesStatus400Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmActivitiesStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmActivitiesStatus403Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmActivitiesStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmActivitiesStatus409Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmActivitiesStatus413Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmActivitiesStatus415Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmActivitiesStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type list_crm_notes_option :: {:record_id, String.t()} | {:limit, integer()} | {:after_, String.t()}
  @spec list_crm_notes(Client.t(), [list_crm_notes_option()]) :: {:ok, map()} | {:error, term()}
  def list_crm_notes(client, options \\ []) when is_list(options) do
    with {:ok, record_id} <- Client.required(options, :record_id) do
      path = "/v1/crm/records/{record_id}/notes"
      path = String.replace(path, "{record_id}", URI.encode(to_string(record_id), &URI.char_unreserved?/1))
      query = [{"limit", Keyword.get(options, :limit)}, {"after", Keyword.get(options, :after_)}]
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :get, path, query, headers, nil, :json, :json, %{400 => RelevateSdk.Errors.ListCrmNotesStatus400Error, 401 => RelevateSdk.Errors.ListCrmNotesStatus401Error, 403 => RelevateSdk.Errors.ListCrmNotesStatus403Error, 404 => RelevateSdk.Errors.ListCrmNotesStatus404Error, 409 => RelevateSdk.Errors.ListCrmNotesStatus409Error, 413 => RelevateSdk.Errors.ListCrmNotesStatus413Error, 415 => RelevateSdk.Errors.ListCrmNotesStatus415Error, 503 => RelevateSdk.Errors.ListCrmNotesStatus503Error}) do
        {:ok, response} -> {:ok, response}
        {:error, %RelevateSdk.Errors.ListCrmNotesStatus400Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmNotesStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmNotesStatus403Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmNotesStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmNotesStatus409Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmNotesStatus413Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmNotesStatus415Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmNotesStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type create_crm_note_option :: {:record_id, String.t()} | {:body, RelevateSdk.Models.CrmNoteWrite.t()}
  @spec create_crm_note(Client.t(), [create_crm_note_option()]) :: {:ok, map()} | {:error, term()}
  def create_crm_note(client, options \\ []) when is_list(options) do
    with {:ok, record_id} <- Client.required(options, :record_id),
         {:ok, body} <- Client.required(options, :body) do
      path = "/v1/crm/records/{record_id}/notes"
      path = String.replace(path, "{record_id}", URI.encode(to_string(record_id), &URI.char_unreserved?/1))
      query = []
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :post, path, query, headers, body, :json, :json, %{400 => RelevateSdk.Errors.CreateCrmNoteStatus400Error, 401 => RelevateSdk.Errors.CreateCrmNoteStatus401Error, 403 => RelevateSdk.Errors.CreateCrmNoteStatus403Error, 404 => RelevateSdk.Errors.CreateCrmNoteStatus404Error, 409 => RelevateSdk.Errors.CreateCrmNoteStatus409Error, 413 => RelevateSdk.Errors.CreateCrmNoteStatus413Error, 415 => RelevateSdk.Errors.CreateCrmNoteStatus415Error, 503 => RelevateSdk.Errors.CreateCrmNoteStatus503Error}) do
        {:ok, response} -> {:ok, response}
        {:error, %RelevateSdk.Errors.CreateCrmNoteStatus400Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmNoteStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmNoteStatus403Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmNoteStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmNoteStatus409Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmNoteStatus413Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmNoteStatus415Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmNoteStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type list_crm_tasks_option :: {:record_id, String.t()} | {:limit, integer()} | {:after_, String.t()}
  @spec list_crm_tasks(Client.t(), [list_crm_tasks_option()]) :: {:ok, map()} | {:error, term()}
  def list_crm_tasks(client, options \\ []) when is_list(options) do
    with {:ok, record_id} <- Client.required(options, :record_id) do
      path = "/v1/crm/records/{record_id}/tasks"
      path = String.replace(path, "{record_id}", URI.encode(to_string(record_id), &URI.char_unreserved?/1))
      query = [{"limit", Keyword.get(options, :limit)}, {"after", Keyword.get(options, :after_)}]
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :get, path, query, headers, nil, :json, :json, %{400 => RelevateSdk.Errors.ListCrmTasksStatus400Error, 401 => RelevateSdk.Errors.ListCrmTasksStatus401Error, 403 => RelevateSdk.Errors.ListCrmTasksStatus403Error, 404 => RelevateSdk.Errors.ListCrmTasksStatus404Error, 409 => RelevateSdk.Errors.ListCrmTasksStatus409Error, 413 => RelevateSdk.Errors.ListCrmTasksStatus413Error, 415 => RelevateSdk.Errors.ListCrmTasksStatus415Error, 503 => RelevateSdk.Errors.ListCrmTasksStatus503Error}) do
        {:ok, response} -> {:ok, response}
        {:error, %RelevateSdk.Errors.ListCrmTasksStatus400Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmTasksStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmTasksStatus403Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmTasksStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmTasksStatus409Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmTasksStatus413Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmTasksStatus415Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.ListCrmTasksStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type create_crm_task_option :: {:record_id, String.t()} | {:body, RelevateSdk.Models.CrmTaskCreate.t()}
  @spec create_crm_task(Client.t(), [create_crm_task_option()]) :: {:ok, map()} | {:error, term()}
  def create_crm_task(client, options \\ []) when is_list(options) do
    with {:ok, record_id} <- Client.required(options, :record_id),
         {:ok, body} <- Client.required(options, :body) do
      path = "/v1/crm/records/{record_id}/tasks"
      path = String.replace(path, "{record_id}", URI.encode(to_string(record_id), &URI.char_unreserved?/1))
      query = []
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :post, path, query, headers, body, :json, :json, %{400 => RelevateSdk.Errors.CreateCrmTaskStatus400Error, 401 => RelevateSdk.Errors.CreateCrmTaskStatus401Error, 403 => RelevateSdk.Errors.CreateCrmTaskStatus403Error, 404 => RelevateSdk.Errors.CreateCrmTaskStatus404Error, 409 => RelevateSdk.Errors.CreateCrmTaskStatus409Error, 413 => RelevateSdk.Errors.CreateCrmTaskStatus413Error, 415 => RelevateSdk.Errors.CreateCrmTaskStatus415Error, 503 => RelevateSdk.Errors.CreateCrmTaskStatus503Error}) do
        {:ok, response} -> {:ok, response}
        {:error, %RelevateSdk.Errors.CreateCrmTaskStatus400Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmTaskStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmTaskStatus403Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmTaskStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmTaskStatus409Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmTaskStatus413Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmTaskStatus415Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateCrmTaskStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type delete_crm_task_option :: {:task_id, String.t()}
  @spec delete_crm_task(Client.t(), [delete_crm_task_option()]) :: {:ok, map()} | {:error, term()}
  def delete_crm_task(client, options \\ []) when is_list(options) do
    with {:ok, task_id} <- Client.required(options, :task_id) do
      path = "/v1/crm/tasks/{task_id}"
      path = String.replace(path, "{task_id}", URI.encode(to_string(task_id), &URI.char_unreserved?/1))
      query = []
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :delete, path, query, headers, nil, :json, :json, %{400 => RelevateSdk.Errors.DeleteCrmTaskStatus400Error, 401 => RelevateSdk.Errors.DeleteCrmTaskStatus401Error, 403 => RelevateSdk.Errors.DeleteCrmTaskStatus403Error, 404 => RelevateSdk.Errors.DeleteCrmTaskStatus404Error, 409 => RelevateSdk.Errors.DeleteCrmTaskStatus409Error, 413 => RelevateSdk.Errors.DeleteCrmTaskStatus413Error, 415 => RelevateSdk.Errors.DeleteCrmTaskStatus415Error, 503 => RelevateSdk.Errors.DeleteCrmTaskStatus503Error}) do
        {:ok, response} -> {:ok, response}
        {:error, %RelevateSdk.Errors.DeleteCrmTaskStatus400Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.DeleteCrmTaskStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.DeleteCrmTaskStatus403Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.DeleteCrmTaskStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.DeleteCrmTaskStatus409Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.DeleteCrmTaskStatus413Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.DeleteCrmTaskStatus415Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.DeleteCrmTaskStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type get_crm_task_option :: {:task_id, String.t()}
  @spec get_crm_task(Client.t(), [get_crm_task_option()]) :: {:ok, map()} | {:error, term()}
  def get_crm_task(client, options \\ []) when is_list(options) do
    with {:ok, task_id} <- Client.required(options, :task_id) do
      path = "/v1/crm/tasks/{task_id}"
      path = String.replace(path, "{task_id}", URI.encode(to_string(task_id), &URI.char_unreserved?/1))
      query = []
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :get, path, query, headers, nil, :json, :json, %{400 => RelevateSdk.Errors.GetCrmTaskStatus400Error, 401 => RelevateSdk.Errors.GetCrmTaskStatus401Error, 403 => RelevateSdk.Errors.GetCrmTaskStatus403Error, 404 => RelevateSdk.Errors.GetCrmTaskStatus404Error, 409 => RelevateSdk.Errors.GetCrmTaskStatus409Error, 413 => RelevateSdk.Errors.GetCrmTaskStatus413Error, 415 => RelevateSdk.Errors.GetCrmTaskStatus415Error, 503 => RelevateSdk.Errors.GetCrmTaskStatus503Error}) do
        {:ok, response} -> {:ok, response}
        {:error, %RelevateSdk.Errors.GetCrmTaskStatus400Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmTaskStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmTaskStatus403Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmTaskStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmTaskStatus409Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmTaskStatus413Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmTaskStatus415Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetCrmTaskStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type update_crm_task_option :: {:task_id, String.t()} | {:body, RelevateSdk.Models.CrmTaskPatch.t()}
  @spec update_crm_task(Client.t(), [update_crm_task_option()]) :: {:ok, map()} | {:error, term()}
  def update_crm_task(client, options \\ []) when is_list(options) do
    with {:ok, task_id} <- Client.required(options, :task_id),
         {:ok, body} <- Client.required(options, :body) do
      path = "/v1/crm/tasks/{task_id}"
      path = String.replace(path, "{task_id}", URI.encode(to_string(task_id), &URI.char_unreserved?/1))
      query = []
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :patch, path, query, headers, body, :json, :json, %{400 => RelevateSdk.Errors.UpdateCrmTaskStatus400Error, 401 => RelevateSdk.Errors.UpdateCrmTaskStatus401Error, 403 => RelevateSdk.Errors.UpdateCrmTaskStatus403Error, 404 => RelevateSdk.Errors.UpdateCrmTaskStatus404Error, 409 => RelevateSdk.Errors.UpdateCrmTaskStatus409Error, 413 => RelevateSdk.Errors.UpdateCrmTaskStatus413Error, 415 => RelevateSdk.Errors.UpdateCrmTaskStatus415Error, 503 => RelevateSdk.Errors.UpdateCrmTaskStatus503Error}) do
        {:ok, response} -> {:ok, response}
        {:error, %RelevateSdk.Errors.UpdateCrmTaskStatus400Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmTaskStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmTaskStatus403Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmTaskStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmTaskStatus409Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmTaskStatus413Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmTaskStatus415Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateCrmTaskStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmApiError.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type auth_check_option :: term()
  @spec auth_check(Client.t(), [auth_check_option()]) :: {:ok, RelevateSdk.Models.AuthCheckResponse.t()} | {:error, term()}
  def auth_check(client, options \\ []) when is_list(options) do
    path = "/v1/email/auth-check"
    query = []
    headers = []
    headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
    case Client.request(client, :get, path, query, headers, nil, :json, :json, %{401 => RelevateSdk.Errors.AuthCheckStatus401Error, 403 => RelevateSdk.Errors.AuthCheckStatus403Error, 503 => RelevateSdk.Errors.AuthCheckStatus503Error}) do
      {:ok, response} -> {:ok, case response do nil -> nil; map when is_map(map) -> RelevateSdk.Models.AuthCheckResponse.from_map(map); other -> other end}
      {:error, %RelevateSdk.Errors.AuthCheckStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
      {:error, %RelevateSdk.Errors.AuthCheckStatus403Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
      {:error, %RelevateSdk.Errors.AuthCheckStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
      {:error, reason} -> {:error, reason}
    end
  end

  @type list_contacts_option :: {:limit, integer()}
  @spec list_contacts(Client.t(), [list_contacts_option()]) :: {:ok, RelevateSdk.Models.ContactListResponse.t()} | {:error, term()}
  def list_contacts(client, options \\ []) when is_list(options) do
    path = "/v1/email/contacts"
    query = [{"limit", Keyword.get(options, :limit)}]
    headers = []
    headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
    case Client.request(client, :get, path, query, headers, nil, :json, :json, %{401 => RelevateSdk.Errors.ListContactsStatus401Error, 503 => RelevateSdk.Errors.ListContactsStatus503Error}) do
      {:ok, response} -> {:ok, case response do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ContactListResponse.from_map(map); other -> other end}
      {:error, %RelevateSdk.Errors.ListContactsStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
      {:error, %RelevateSdk.Errors.ListContactsStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
      {:error, reason} -> {:error, reason}
    end
  end

  @type create_contact_option :: {:body, RelevateSdk.Models.CreateContact.t()}
  @spec create_contact(Client.t(), [create_contact_option()]) :: {:ok, RelevateSdk.Models.ContactResponse.t()} | {:error, term()}
  def create_contact(client, options \\ []) when is_list(options) do
    with {:ok, body} <- Client.required(options, :body) do
      path = "/v1/email/contacts"
      query = []
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :post, path, query, headers, body, :json, :json, %{401 => RelevateSdk.Errors.CreateContactStatus401Error, 422 => RelevateSdk.Errors.CreateContactStatus422Error, 503 => RelevateSdk.Errors.CreateContactStatus503Error}) do
        {:ok, response} -> {:ok, case response do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ContactResponse.from_map(map); other -> other end}
        {:error, %RelevateSdk.Errors.CreateContactStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateContactStatus422Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.CreateContactStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type query_contacts_option :: {:body, RelevateSdk.Models.ContactQuery.t()}
  @spec query_contacts(Client.t(), [query_contacts_option()]) :: {:ok, RelevateSdk.Models.ContactQueryResponse.t()} | {:error, term()}
  def query_contacts(client, options \\ []) when is_list(options) do
    with {:ok, body} <- Client.required(options, :body) do
      path = "/v1/email/contacts/query"
      query = []
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :post, path, query, headers, body, :json, :json, %{401 => RelevateSdk.Errors.QueryContactsStatus401Error, 422 => RelevateSdk.Errors.QueryContactsStatus422Error, 503 => RelevateSdk.Errors.QueryContactsStatus503Error}) do
        {:ok, response} -> {:ok, case response do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ContactQueryResponse.from_map(map); other -> other end}
        {:error, %RelevateSdk.Errors.QueryContactsStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.QueryContactsStatus422Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.QueryContactsStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type get_contact_option :: {:id, String.t()}
  @spec get_contact(Client.t(), [get_contact_option()]) :: {:ok, RelevateSdk.Models.ContactResponse.t()} | {:error, term()}
  def get_contact(client, options \\ []) when is_list(options) do
    with {:ok, id} <- Client.required(options, :id) do
      path = "/v1/email/contacts/{id}"
      path = String.replace(path, "{id}", URI.encode(to_string(id), &URI.char_unreserved?/1))
      query = []
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :get, path, query, headers, nil, :json, :json, %{401 => RelevateSdk.Errors.GetContactStatus401Error, 404 => RelevateSdk.Errors.GetContactStatus404Error, 503 => RelevateSdk.Errors.GetContactStatus503Error}) do
        {:ok, response} -> {:ok, case response do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ContactResponse.from_map(map); other -> other end}
        {:error, %RelevateSdk.Errors.GetContactStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetContactStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetContactStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type update_contact_option :: {:id, String.t()} | {:body, RelevateSdk.Models.UpdateContact.t()}
  @spec update_contact(Client.t(), [update_contact_option()]) :: {:ok, RelevateSdk.Models.ContactResponse.t()} | {:error, term()}
  def update_contact(client, options \\ []) when is_list(options) do
    with {:ok, id} <- Client.required(options, :id),
         {:ok, body} <- Client.required(options, :body) do
      path = "/v1/email/contacts/{id}"
      path = String.replace(path, "{id}", URI.encode(to_string(id), &URI.char_unreserved?/1))
      query = []
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :patch, path, query, headers, body, :json, :json, %{401 => RelevateSdk.Errors.UpdateContactStatus401Error, 404 => RelevateSdk.Errors.UpdateContactStatus404Error, 422 => RelevateSdk.Errors.UpdateContactStatus422Error, 503 => RelevateSdk.Errors.UpdateContactStatus503Error}) do
        {:ok, response} -> {:ok, case response do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ContactResponse.from_map(map); other -> other end}
        {:error, %RelevateSdk.Errors.UpdateContactStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateContactStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateContactStatus422Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.UpdateContactStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @type list_domains_option :: {:limit, integer()}
  @spec list_domains(Client.t(), [list_domains_option()]) :: {:ok, RelevateSdk.Models.DomainListResponse.t()} | {:error, term()}
  def list_domains(client, options \\ []) when is_list(options) do
    path = "/v1/email/domains"
    query = [{"limit", Keyword.get(options, :limit)}]
    headers = []
    headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
    case Client.request(client, :get, path, query, headers, nil, :json, :json, %{401 => RelevateSdk.Errors.ListDomainsStatus401Error, 503 => RelevateSdk.Errors.ListDomainsStatus503Error}) do
      {:ok, response} -> {:ok, case response do nil -> nil; map when is_map(map) -> RelevateSdk.Models.DomainListResponse.from_map(map); other -> other end}
      {:error, %RelevateSdk.Errors.ListDomainsStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
      {:error, %RelevateSdk.Errors.ListDomainsStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
      {:error, reason} -> {:error, reason}
    end
  end

  @type get_domain_option :: {:id, String.t()}
  @spec get_domain(Client.t(), [get_domain_option()]) :: {:ok, RelevateSdk.Models.DomainResponse.t()} | {:error, term()}
  def get_domain(client, options \\ []) when is_list(options) do
    with {:ok, id} <- Client.required(options, :id) do
      path = "/v1/email/domains/{id}"
      path = String.replace(path, "{id}", URI.encode(to_string(id), &URI.char_unreserved?/1))
      query = []
      headers = []
      headers = headers |> Enum.reject(fn {_name, value} -> is_nil(value) end) |> Enum.map(fn {name, value} -> {name, to_string(value)} end)
      case Client.request(client, :get, path, query, headers, nil, :json, :json, %{401 => RelevateSdk.Errors.GetDomainStatus401Error, 404 => RelevateSdk.Errors.GetDomainStatus404Error, 503 => RelevateSdk.Errors.GetDomainStatus503Error}) do
        {:ok, response} -> {:ok, case response do nil -> nil; map when is_map(map) -> RelevateSdk.Models.DomainResponse.from_map(map); other -> other end}
        {:error, %RelevateSdk.Errors.GetDomainStatus401Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetDomainStatus404Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
        {:error, %RelevateSdk.Errors.GetDomainStatus503Error{} = reason} -> {:error, %{reason | body: case reason.body do nil -> nil; map when is_map(map) -> RelevateSdk.Models.ErrorResponse.from_map(map); other -> other end}}
        {:error, reason} -> {:error, reason}
      end
    end
  end

end
