/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { ContactResponse } from '../ContactResponse.js'
import type { ErrorResponse } from '../ErrorResponse.js'

export type GetContactPath = {
  id: string
}

export type GetContactStatus200 = ContactResponse

export type GetContactStatus401 = ErrorResponse

export type GetContactStatus404 = ErrorResponse

export type GetContactStatus503 = ErrorResponse

export type GetContactOptions = {
  body?: never
  path: GetContactPath
  query?: never
  headers?: never
  cookie?: never
}

export type GetContactResponses = {
  '200': GetContactStatus200
  '401': GetContactStatus401
  '404': GetContactStatus404
  '503': GetContactStatus503
}

/**
 * @description Union of all possible responses
 */
export type GetContactResponse = GetContactStatus200 | GetContactStatus401 | GetContactStatus404 | GetContactStatus503
