/**
 * Generated by Kaji.
 * Do not edit manually.
 * Source: text content
 */

import type { ContactResponse } from '../ContactResponse.js'
import type { ErrorResponse } from '../ErrorResponse.js'
import type { UpdateContact } from '../UpdateContact.js'

export type UpdateContactPath = {
  id: string
}

export type UpdateContactStatus200 = ContactResponse

export type UpdateContactStatus401 = ErrorResponse

export type UpdateContactStatus404 = ErrorResponse

export type UpdateContactStatus422 = ErrorResponse

export type UpdateContactStatus503 = ErrorResponse

export type UpdateContactBody = UpdateContact

export type UpdateContactOptions = {
  body: UpdateContactBody
  path: UpdateContactPath
  query?: never
  headers?: never
  cookie?: never
}

export type UpdateContactResponses = {
  '200': UpdateContactStatus200
  '401': UpdateContactStatus401
  '404': UpdateContactStatus404
  '422': UpdateContactStatus422
  '503': UpdateContactStatus503
}

/**
 * @description Union of all possible responses
 */
export type UpdateContactResponse = UpdateContactStatus200 | UpdateContactStatus401 | UpdateContactStatus404 | UpdateContactStatus422 | UpdateContactStatus503
