<?php

declare(strict_types=1);

namespace Relevate\Sdk\Resources;

use Relevate\Sdk\Client;
use Relevate\Sdk\Models\AuthCheckResponse;
use Relevate\Sdk\Models\ErrorResponse;

// Generated by Kaji. Do not edit.

/** Bounded resource facade slice; composed into AuthCheckResource. */
trait AuthCheckResourceOperations000
{
    public function authCheck(): AuthCheckResponse
    {
        return $this->client->authCheck();
    }

}
