<?php

declare(strict_types=1);

namespace Relevate\Sdk\Resources;

use Relevate\Sdk\Client;
use Relevate\Sdk\Models\DomainListResponse;
use Relevate\Sdk\Models\DomainResponse;
use Relevate\Sdk\Models\ErrorResponse;

// Generated by Kaji. Do not edit.

/** Bounded resource facade slice; composed into DomainsResource. */
trait DomainsResourceOperations000
{
    public function listOperation(?int $limit = null): DomainListResponse
    {
        return $this->client->listDomains($limit);
    }

    public function get(string $id): DomainResponse
    {
        return $this->client->getDomain($id);
    }

}
