<?php

declare(strict_types=1);

namespace Relevate\Sdk\Resources;

use Relevate\Sdk\Client;

// Generated by Kaji. Do not edit.

final class SenderIdentitiesResource
{
    use SenderIdentitiesResourceOperations000;

    public function __construct(private readonly Client $client)
    {
    }
}
