# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Models.CrmListEntry do
  @moduledoc "Generated model for CrmListEntry."
  alias RelevateSdk.JSON

  @enforce_keys [:created_at, :id, :list_id, :record_id, :updated_at, :values]
  defstruct [:created_at, :id, :list_id, :record_id, :updated_at, :values]

  @type t :: %__MODULE__{
    created_at: String.t(),
    id: String.t(),
    list_id: String.t(),
    record_id: String.t(),
    updated_at: String.t(),
    values: map(),
  }

  @spec to_map(t()) :: map()
  def to_map(model) do
    [
      {"created_at", model.created_at},
      {"id", model.id},
      {"list_id", model.list_id},
      {"record_id", model.record_id},
      {"updated_at", model.updated_at},
      {"values", model.values},
    ]
    |> Enum.reject(fn {_key, value} -> is_nil(value) end)
    |> Map.new(fn {key, value} -> {key, JSON.to_wire(value)} end)
  end

  @spec from_map(map()) :: t()
  def from_map(map) do
    %__MODULE__{
      created_at: Map.get(map, "created_at"),
      id: Map.get(map, "id"),
      list_id: Map.get(map, "list_id"),
      record_id: Map.get(map, "record_id"),
      updated_at: Map.get(map, "updated_at"),
      values: Map.get(map, "values"),
    }
  end
end
