# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Models.CrmMetadataDeletedData do
  @moduledoc "Generated model for CrmMetadataDeletedData."
  alias RelevateSdk.JSON

  @enforce_keys [:deleted]
  defstruct [:deleted]

  @type t :: %__MODULE__{
    deleted: boolean(),
  }

  @spec to_map(t()) :: map()
  def to_map(model) do
    [
      {"deleted", model.deleted},
    ]
    |> Enum.reject(fn {_key, value} -> is_nil(value) end)
    |> Map.new(fn {key, value} -> {key, JSON.to_wire(value)} end)
  end

  @spec from_map(map()) :: t()
  def from_map(map) do
    %__MODULE__{
      deleted: Map.get(map, "deleted"),
    }
  end
end
