# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Models.CrmQualityResponse do
  @moduledoc "Generated model for CrmQualityResponse."
  alias RelevateSdk.JSON

  @enforce_keys [:api_version, :data, :page]
  defstruct [:api_version, :data, :page]

  @type t :: %__MODULE__{
    api_version: String.t(),
    data: map(),
    page: map(),
  }

  @spec to_map(t()) :: map()
  def to_map(model) do
    [
      {"api_version", model.api_version},
      {"data", model.data},
      {"page", model.page},
    ]
    |> Enum.reject(fn {_key, value} -> is_nil(value) end)
    |> Map.new(fn {key, value} -> {key, JSON.to_wire(value)} end)
  end

  @spec from_map(map()) :: t()
  def from_map(map) do
    %__MODULE__{
      api_version: Map.get(map, "api_version"),
      data: Map.get(map, "data"),
      page: Map.get(map, "page"),
    }
  end
end
