# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Models.CrmNoteMention do
  @moduledoc "Generated model for CrmNoteMention."
  alias RelevateSdk.JSON

  @enforce_keys [:end_, :record_id, :start]
  defstruct [:end_, :record_id, :start]

  @type t :: %__MODULE__{
    end_: integer(),
    record_id: String.t(),
    start: integer(),
  }

  @spec to_map(t()) :: map()
  def to_map(model) do
    [
      {"end", model.end_},
      {"recordId", model.record_id},
      {"start", model.start},
    ]
    |> Enum.reject(fn {_key, value} -> is_nil(value) end)
    |> Map.new(fn {key, value} -> {key, JSON.to_wire(value)} end)
  end

  @spec from_map(map()) :: t()
  def from_map(map) do
    %__MODULE__{
      end_: Map.get(map, "end"),
      record_id: Map.get(map, "recordId"),
      start: Map.get(map, "start"),
    }
  end
end
