# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Models.CrmNote do
  @moduledoc "Generated model for CrmNote."
  alias RelevateSdk.JSON

  @enforce_keys [:body, :created_at, :id, :mentions, :record_id, :title, :updated_at]
  defstruct [:author_id, :body, :content, :created_at, :deleted_at, :id, :mention_records, :mentions, :record_id, :title, :updated_at]

  @type t :: %__MODULE__{
    author_id: String.t() | nil | nil,
    body: String.t(),
    content: RelevateSdk.Models.CrmNoteDocument.t() | nil | nil,
    created_at: String.t(),
    deleted_at: String.t() | nil | nil,
    id: String.t(),
    mention_records: [map()] | nil,
    mentions: [RelevateSdk.Models.CrmNoteMention.t()],
    record_id: String.t(),
    title: String.t(),
    updated_at: String.t(),
  }

  @spec to_map(t()) :: map()
  def to_map(model) do
    [
      {"author_id", model.author_id},
      {"body", model.body},
      {"content", model.content},
      {"created_at", model.created_at},
      {"deleted_at", model.deleted_at},
      {"id", model.id},
      {"mention_records", model.mention_records},
      {"mentions", model.mentions},
      {"record_id", model.record_id},
      {"title", model.title},
      {"updated_at", model.updated_at},
    ]
    |> Enum.reject(fn {_key, value} -> is_nil(value) end)
    |> Map.new(fn {key, value} -> {key, JSON.to_wire(value)} end)
  end

  @spec from_map(map()) :: t()
  def from_map(map) do
    %__MODULE__{
      author_id: Map.get(map, "author_id"),
      body: Map.get(map, "body"),
      content: Map.get(map, "content"),
      created_at: Map.get(map, "created_at"),
      deleted_at: Map.get(map, "deleted_at"),
      id: Map.get(map, "id"),
      mention_records: Enum.map(Map.get(map, "mention_records") || [], fn item -> item end),
      mentions: Enum.map(Map.get(map, "mentions") || [], fn item -> case item do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmNoteMention.from_map(map); other -> other end end),
      record_id: Map.get(map, "record_id"),
      title: Map.get(map, "title"),
      updated_at: Map.get(map, "updated_at"),
    }
  end
end
