# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Models.CrmObjectDeletionPreviewData do
  @moduledoc "Generated model for CrmObjectDeletionPreviewData."
  alias RelevateSdk.JSON

  @enforce_keys [:blocking_relationships, :list_count, :object, :record_count]
  defstruct [:blocking_relationships, :list_count, :object, :record_count]

  @type t :: %__MODULE__{
    blocking_relationships: [map()],
    list_count: integer(),
    object: RelevateSdk.Models.CrmMetadataObject.t(),
    record_count: integer(),
  }

  @spec to_map(t()) :: map()
  def to_map(model) do
    [
      {"blocking_relationships", model.blocking_relationships},
      {"list_count", model.list_count},
      {"object", model.object},
      {"record_count", model.record_count},
    ]
    |> Enum.reject(fn {_key, value} -> is_nil(value) end)
    |> Map.new(fn {key, value} -> {key, JSON.to_wire(value)} end)
  end

  @spec from_map(map()) :: t()
  def from_map(map) do
    %__MODULE__{
      blocking_relationships: Enum.map(Map.get(map, "blocking_relationships") || [], fn item -> item end),
      list_count: Map.get(map, "list_count"),
      object: case Map.get(map, "object") do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmMetadataObject.from_map(map); other -> other end,
      record_count: Map.get(map, "record_count"),
    }
  end
end
