# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Models.CrmQualityRecord do
  @moduledoc "Generated model for CrmQualityRecord."
  alias RelevateSdk.JSON

  @enforce_keys [:display_name, :duplicate_candidate_count, :duplicate_candidates, :issues, :record_id]
  defstruct [:display_name, :duplicate_candidate_count, :duplicate_candidates, :issues, :record_id]

  @type t :: %__MODULE__{
    display_name: String.t(),
    duplicate_candidate_count: integer(),
    duplicate_candidates: [map()],
    issues: [RelevateSdk.Models.CrmQualityIssue.t()],
    record_id: String.t(),
  }

  @spec to_map(t()) :: map()
  def to_map(model) do
    [
      {"display_name", model.display_name},
      {"duplicate_candidate_count", model.duplicate_candidate_count},
      {"duplicate_candidates", model.duplicate_candidates},
      {"issues", model.issues},
      {"record_id", model.record_id},
    ]
    |> Enum.reject(fn {_key, value} -> is_nil(value) end)
    |> Map.new(fn {key, value} -> {key, JSON.to_wire(value)} end)
  end

  @spec from_map(map()) :: t()
  def from_map(map) do
    %__MODULE__{
      display_name: Map.get(map, "display_name"),
      duplicate_candidate_count: Map.get(map, "duplicate_candidate_count"),
      duplicate_candidates: Enum.map(Map.get(map, "duplicate_candidates") || [], fn item -> item end),
      issues: Enum.map(Map.get(map, "issues") || [], fn item -> case item do nil -> nil; map when is_map(map) -> RelevateSdk.Models.CrmQualityIssue.from_map(map); other -> other end end),
      record_id: Map.get(map, "record_id"),
    }
  end
end
