# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Models.CrmObjectPatch do
  @moduledoc "Generated model for CrmObjectPatch."
  alias RelevateSdk.JSON

  defstruct [:enabled, :icon, :name]

  @type t :: %__MODULE__{
    enabled: boolean() | nil,
    icon: String.t() | nil,
    name: String.t() | nil,
  }

  @spec to_map(t()) :: map()
  def to_map(model) do
    [
      {"enabled", model.enabled},
      {"icon", model.icon},
      {"name", model.name},
    ]
    |> Enum.reject(fn {_key, value} -> is_nil(value) end)
    |> Map.new(fn {key, value} -> {key, JSON.to_wire(value)} end)
  end

  @spec from_map(map()) :: t()
  def from_map(map) do
    %__MODULE__{
      enabled: Map.get(map, "enabled"),
      icon: Map.get(map, "icon"),
      name: Map.get(map, "name"),
    }
  end
end
