# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Models.CrmAttributeCreate do
  @moduledoc "Generated model for CrmAttributeCreate."
  alias RelevateSdk.JSON

  @enforce_keys [:key, :name, :type]
  defstruct [:currency_code, :expression, :key, :multiple, :name, :options, :required, :target_object_id, :type]

  @type t :: %__MODULE__{
    currency_code: String.t() | nil | nil,
    expression: String.t() | nil | nil,
    key: String.t(),
    multiple: boolean() | nil,
    name: String.t(),
    options: [String.t()] | nil,
    required: boolean() | nil,
    target_object_id: String.t() | nil | nil,
    type: "text" | "number" | "currency" | "phone" | "rating" | "location" | "multi_select" | "status" | "relationship" | "formula" | "boolean" | "date" | "timestamp" | "select" | "record" | "user",
  }

  @spec to_map(t()) :: map()
  def to_map(model) do
    [
      {"currency_code", model.currency_code},
      {"expression", model.expression},
      {"key", model.key},
      {"multiple", model.multiple},
      {"name", model.name},
      {"options", model.options},
      {"required", model.required},
      {"target_object_id", model.target_object_id},
      {"type", model.type},
    ]
    |> Enum.reject(fn {_key, value} -> is_nil(value) end)
    |> Map.new(fn {key, value} -> {key, JSON.to_wire(value)} end)
  end

  @spec from_map(map()) :: t()
  def from_map(map) do
    %__MODULE__{
      currency_code: Map.get(map, "currency_code"),
      expression: Map.get(map, "expression"),
      key: Map.get(map, "key"),
      multiple: Map.get(map, "multiple"),
      name: Map.get(map, "name"),
      options: Enum.map(Map.get(map, "options") || [], fn item -> item end),
      required: Map.get(map, "required"),
      target_object_id: Map.get(map, "target_object_id"),
      type: Map.get(map, "type"),
    }
  end
end
