# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Models.CrmApiError do
  @moduledoc "Generated model for CrmApiError."
  alias RelevateSdk.JSON

  @enforce_keys [:api_version, :error]
  defstruct [:api_version, :error]

  @type t :: %__MODULE__{
    api_version: String.t(),
    error: map(),
  }

  @spec to_map(t()) :: map()
  def to_map(model) do
    [
      {"api_version", model.api_version},
      {"error", model.error},
    ]
    |> Enum.reject(fn {_key, value} -> is_nil(value) end)
    |> Map.new(fn {key, value} -> {key, JSON.to_wire(value)} end)
  end

  @spec from_map(map()) :: t()
  def from_map(map) do
    %__MODULE__{
      api_version: Map.get(map, "api_version"),
      error: Map.get(map, "error"),
    }
  end
end
