# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Models.Domain do
  @moduledoc "Generated model for Domain."
  alias RelevateSdk.JSON

  @enforce_keys [:created_at, :dkim_selector, :dmarc_mode, :id, :name, :normalized_name, :receiving_enabled, :status, :updated_at]
  defstruct [:created_at, :dkim_selector, :dmarc_mode, :id, :last_checked_at, :name, :normalized_name, :ownership_verified_at, :receiving_enabled, :receiving_verified_at, :status, :updated_at]

  @type t :: %__MODULE__{
    created_at: String.t(),
    dkim_selector: String.t(),
    dmarc_mode: String.t(),
    id: String.t(),
    last_checked_at: String.t() | nil | nil,
    name: String.t(),
    normalized_name: String.t(),
    ownership_verified_at: String.t() | nil | nil,
    receiving_enabled: boolean(),
    receiving_verified_at: String.t() | nil | nil,
    status: String.t(),
    updated_at: String.t(),
  }

  @spec to_map(t()) :: map()
  def to_map(model) do
    [
      {"created_at", model.created_at},
      {"dkim_selector", model.dkim_selector},
      {"dmarc_mode", model.dmarc_mode},
      {"id", model.id},
      {"last_checked_at", model.last_checked_at},
      {"name", model.name},
      {"normalized_name", model.normalized_name},
      {"ownership_verified_at", model.ownership_verified_at},
      {"receiving_enabled", model.receiving_enabled},
      {"receiving_verified_at", model.receiving_verified_at},
      {"status", model.status},
      {"updated_at", model.updated_at},
    ]
    |> Enum.reject(fn {_key, value} -> is_nil(value) end)
    |> Map.new(fn {key, value} -> {key, JSON.to_wire(value)} end)
  end

  @spec from_map(map()) :: t()
  def from_map(map) do
    %__MODULE__{
      created_at: Map.get(map, "created_at"),
      dkim_selector: Map.get(map, "dkim_selector"),
      dmarc_mode: Map.get(map, "dmarc_mode"),
      id: Map.get(map, "id"),
      last_checked_at: Map.get(map, "last_checked_at"),
      name: Map.get(map, "name"),
      normalized_name: Map.get(map, "normalized_name"),
      ownership_verified_at: Map.get(map, "ownership_verified_at"),
      receiving_enabled: Map.get(map, "receiving_enabled"),
      receiving_verified_at: Map.get(map, "receiving_verified_at"),
      status: Map.get(map, "status"),
      updated_at: Map.get(map, "updated_at"),
    }
  end
end
