# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Models.Page do
  @moduledoc "Generated model for Page."
  alias RelevateSdk.JSON

  @enforce_keys [:limit, :offset]
  defstruct [:limit, :next_offset, :offset]

  @type t :: %__MODULE__{
    limit: integer(),
    next_offset: integer() | nil | nil,
    offset: integer(),
  }

  @spec to_map(t()) :: map()
  def to_map(model) do
    [
      {"limit", model.limit},
      {"next_offset", model.next_offset},
      {"offset", model.offset},
    ]
    |> Enum.reject(fn {_key, value} -> is_nil(value) end)
    |> Map.new(fn {key, value} -> {key, JSON.to_wire(value)} end)
  end

  @spec from_map(map()) :: t()
  def from_map(map) do
    %__MODULE__{
      limit: Map.get(map, "limit"),
      next_offset: Map.get(map, "next_offset"),
      offset: Map.get(map, "offset"),
    }
  end
end
