# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Models.WebhookListResponse do
  @moduledoc "Generated model for WebhookListResponse."
  alias RelevateSdk.JSON

  @enforce_keys [:api_version, :data]
  defstruct [:api_version, :data]

  @type t :: %__MODULE__{
    api_version: String.t(),
    data: [RelevateSdk.Models.Webhook.t()],
  }

  @spec to_map(t()) :: map()
  def to_map(model) do
    [
      {"api_version", model.api_version},
      {"data", model.data},
    ]
    |> Enum.reject(fn {_key, value} -> is_nil(value) end)
    |> Map.new(fn {key, value} -> {key, JSON.to_wire(value)} end)
  end

  @spec from_map(map()) :: t()
  def from_map(map) do
    %__MODULE__{
      api_version: Map.get(map, "api_version"),
      data: Enum.map(Map.get(map, "data") || [], fn item -> case item do nil -> nil; map when is_map(map) -> RelevateSdk.Models.Webhook.from_map(map); other -> other end end),
    }
  end
end
