# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Errors.TrackStatus401Error do
  @moduledoc "Declared 401 response for `track`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.TrackStatus403Error do
  @moduledoc "Declared 403 response for `track`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.TrackStatus409Error do
  @moduledoc "Declared 409 response for `track`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.TrackStatus422Error do
  @moduledoc "Declared 422 response for `track`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.TrackStatus503Error do
  @moduledoc "Declared 503 response for `track`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.ListInboundStatus401Error do
  @moduledoc "Declared 401 response for `list_inbound`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.ListInboundStatus422Error do
  @moduledoc "Declared 422 response for `list_inbound`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.ListInboundStatus503Error do
  @moduledoc "Declared 503 response for `list_inbound`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.GetInboundStatus401Error do
  @moduledoc "Declared 401 response for `get_inbound`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.GetInboundStatus404Error do
  @moduledoc "Declared 404 response for `get_inbound`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.GetInboundStatus503Error do
  @moduledoc "Declared 503 response for `get_inbound`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.ListSegmentsStatus401Error do
  @moduledoc "Declared 401 response for `list_segments`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.ListSegmentsStatus503Error do
  @moduledoc "Declared 503 response for `list_segments`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.GetSegmentStatus401Error do
  @moduledoc "Declared 401 response for `get_segment`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.GetSegmentStatus404Error do
  @moduledoc "Declared 404 response for `get_segment`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.GetSegmentStatus503Error do
  @moduledoc "Declared 503 response for `get_segment`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.ListSenderIdentitiesStatus401Error do
  @moduledoc "Declared 401 response for `list_sender_identities`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.ListSenderIdentitiesStatus503Error do
  @moduledoc "Declared 503 response for `list_sender_identities`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.GetSenderIdentityStatus401Error do
  @moduledoc "Declared 401 response for `get_sender_identity`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.GetSenderIdentityStatus404Error do
  @moduledoc "Declared 404 response for `get_sender_identity`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.GetSenderIdentityStatus503Error do
  @moduledoc "Declared 503 response for `get_sender_identity`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.CreateStatus401Error do
  @moduledoc "Declared 401 response for `create`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.CreateStatus403Error do
  @moduledoc "Declared 403 response for `create`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.CreateStatus409Error do
  @moduledoc "Declared 409 response for `create`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.CreateStatus422Error do
  @moduledoc "Declared 422 response for `create`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.CreateStatus429Error do
  @moduledoc "Declared 429 response for `create`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.CreateStatus503Error do
  @moduledoc "Declared 503 response for `create`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.QueryStatus401Error do
  @moduledoc "Declared 401 response for `query`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.QueryStatus403Error do
  @moduledoc "Declared 403 response for `query`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.QueryStatus422Error do
  @moduledoc "Declared 422 response for `query`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.QueryStatus503Error do
  @moduledoc "Declared 503 response for `query`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.CancelStatus401Error do
  @moduledoc "Declared 401 response for `cancel`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.CancelStatus403Error do
  @moduledoc "Declared 403 response for `cancel`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.CancelStatus404Error do
  @moduledoc "Declared 404 response for `cancel`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.CancelStatus409Error do
  @moduledoc "Declared 409 response for `cancel`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.CancelStatus503Error do
  @moduledoc "Declared 503 response for `cancel`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.GetStatus401Error do
  @moduledoc "Declared 401 response for `get`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.GetStatus403Error do
  @moduledoc "Declared 403 response for `get`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.GetStatus404Error do
  @moduledoc "Declared 404 response for `get`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.GetStatus503Error do
  @moduledoc "Declared 503 response for `get`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.ListWebhooksStatus401Error do
  @moduledoc "Declared 401 response for `list_webhooks`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.ListWebhooksStatus503Error do
  @moduledoc "Declared 503 response for `list_webhooks`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.CreateWebhookStatus401Error do
  @moduledoc "Declared 401 response for `create_webhook`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.CreateWebhookStatus422Error do
  @moduledoc "Declared 422 response for `create_webhook`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.CreateWebhookStatus503Error do
  @moduledoc "Declared 503 response for `create_webhook`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.DeleteWebhookStatus401Error do
  @moduledoc "Declared 401 response for `delete_webhook`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.DeleteWebhookStatus404Error do
  @moduledoc "Declared 404 response for `delete_webhook`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.DeleteWebhookStatus503Error do
  @moduledoc "Declared 503 response for `delete_webhook`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.UpdateWebhookStatus401Error do
  @moduledoc "Declared 401 response for `update_webhook`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.UpdateWebhookStatus404Error do
  @moduledoc "Declared 404 response for `update_webhook`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.UpdateWebhookStatus422Error do
  @moduledoc "Declared 422 response for `update_webhook`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.UpdateWebhookStatus503Error do
  @moduledoc "Declared 503 response for `update_webhook`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.ListDeliveriesStatus401Error do
  @moduledoc "Declared 401 response for `list_deliveries`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.ListDeliveriesStatus422Error do
  @moduledoc "Declared 422 response for `list_deliveries`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end

defmodule RelevateSdk.Errors.ListDeliveriesStatus503Error do
  @moduledoc "Declared 503 response for `list_deliveries`."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end
