package app.relevate.sdk.internal.resources;

import app.relevate.sdk.*;
import app.relevate.sdk.model.*;

// Generated by Kaji. Do not edit.

/** Bounded operations for the AuthCheck resource. */
public class AuthCheckResourcePart000 {
    protected final Client client;

    protected AuthCheckResourcePart000(Client client) { this.client = client; }

    public AuthCheckResponse authCheck() {
        return client.authCheck();
    }

}
