# Generated by Kaji. Do not edit.

defmodule RelevateSdk.API do
  @moduledoc "Typed API operations for Relevate."

  alias RelevateSdk.API.Operations0000

  def list_crm_lists(client, options \\ []), do: Operations0000.list_crm_lists(client, options)

  def create_crm_list(client, options \\ []), do: Operations0000.create_crm_list(client, options)

  def delete_crm_list(client, options \\ []), do: Operations0000.delete_crm_list(client, options)

  def get_crm_list(client, options \\ []), do: Operations0000.get_crm_list(client, options)

  def update_crm_list(client, options \\ []), do: Operations0000.update_crm_list(client, options)

  def list_crm_list_attributes(client, options \\ []), do: Operations0000.list_crm_list_attributes(client, options)

  def create_crm_list_attribute(client, options \\ []), do: Operations0000.create_crm_list_attribute(client, options)

  def delete_crm_list_attribute(client, options \\ []), do: Operations0000.delete_crm_list_attribute(client, options)

  def update_crm_list_attribute(client, options \\ []), do: Operations0000.update_crm_list_attribute(client, options)

  def list_crm_list_entries(client, options \\ []), do: Operations0000.list_crm_list_entries(client, options)

  def create_crm_list_entry(client, options \\ []), do: Operations0000.create_crm_list_entry(client, options)

  def delete_crm_list_entry(client, options \\ []), do: Operations0000.delete_crm_list_entry(client, options)

  def get_crm_list_entry(client, options \\ []), do: Operations0000.get_crm_list_entry(client, options)

  def update_crm_list_entry(client, options \\ []), do: Operations0000.update_crm_list_entry(client, options)

  def delete_crm_note(client, options \\ []), do: Operations0000.delete_crm_note(client, options)

  def get_crm_note(client, options \\ []), do: Operations0000.get_crm_note(client, options)

  def update_crm_note(client, options \\ []), do: Operations0000.update_crm_note(client, options)

  def list_crm_objects(client, options \\ []), do: Operations0000.list_crm_objects(client, options)

  def create_crm_object(client, options \\ []), do: Operations0000.create_crm_object(client, options)

  def delete_crm_object(client, options \\ []), do: Operations0000.delete_crm_object(client, options)

  def get_crm_object(client, options \\ []), do: Operations0000.get_crm_object(client, options)

  def update_crm_object(client, options \\ []), do: Operations0000.update_crm_object(client, options)

  def list_crm_object_attributes(client, options \\ []), do: Operations0000.list_crm_object_attributes(client, options)

  def create_crm_object_attribute(client, options \\ []), do: Operations0000.create_crm_object_attribute(client, options)

  def delete_crm_object_attribute(client, options \\ []), do: Operations0000.delete_crm_object_attribute(client, options)
  alias RelevateSdk.API.Operations0001

  def update_crm_object_attribute(client, options \\ []), do: Operations0001.update_crm_object_attribute(client, options)

  def preview_crm_object_deletion(client, options \\ []), do: Operations0001.preview_crm_object_deletion(client, options)

  def get_crm_object_quality(client, options \\ []), do: Operations0001.get_crm_object_quality(client, options)

  def list_crm_records(client, options \\ []), do: Operations0001.list_crm_records(client, options)

  def create_crm_record(client, options \\ []), do: Operations0001.create_crm_record(client, options)

  def upsert_crm_record(client, options \\ []), do: Operations0001.upsert_crm_record(client, options)

  def archive_crm_record(client, options \\ []), do: Operations0001.archive_crm_record(client, options)

  def get_crm_record(client, options \\ []), do: Operations0001.get_crm_record(client, options)

  def update_crm_record(client, options \\ []), do: Operations0001.update_crm_record(client, options)

  def list_crm_activities(client, options \\ []), do: Operations0001.list_crm_activities(client, options)

  def list_crm_notes(client, options \\ []), do: Operations0001.list_crm_notes(client, options)

  def create_crm_note(client, options \\ []), do: Operations0001.create_crm_note(client, options)

  def list_crm_tasks(client, options \\ []), do: Operations0001.list_crm_tasks(client, options)

  def create_crm_task(client, options \\ []), do: Operations0001.create_crm_task(client, options)

  def delete_crm_task(client, options \\ []), do: Operations0001.delete_crm_task(client, options)

  def get_crm_task(client, options \\ []), do: Operations0001.get_crm_task(client, options)

  def update_crm_task(client, options \\ []), do: Operations0001.update_crm_task(client, options)

  def auth_check(client, options \\ []), do: Operations0001.auth_check(client, options)

  def list_contacts(client, options \\ []), do: Operations0001.list_contacts(client, options)

  def create_contact(client, options \\ []), do: Operations0001.create_contact(client, options)

  def query_contacts(client, options \\ []), do: Operations0001.query_contacts(client, options)

  def get_contact(client, options \\ []), do: Operations0001.get_contact(client, options)

  def update_contact(client, options \\ []), do: Operations0001.update_contact(client, options)

  def list_domains(client, options \\ []), do: Operations0001.list_domains(client, options)

  def get_domain(client, options \\ []), do: Operations0001.get_domain(client, options)
  alias RelevateSdk.API.Operations0002

  def track(client, options \\ []), do: Operations0002.track(client, options)

  def list_inbound(client, options \\ []), do: Operations0002.list_inbound(client, options)

  def get_inbound(client, options \\ []), do: Operations0002.get_inbound(client, options)

  def list_segments(client, options \\ []), do: Operations0002.list_segments(client, options)

  def get_segment(client, options \\ []), do: Operations0002.get_segment(client, options)

  def list_sender_identities(client, options \\ []), do: Operations0002.list_sender_identities(client, options)

  def get_sender_identity(client, options \\ []), do: Operations0002.get_sender_identity(client, options)

  def create(client, options \\ []), do: Operations0002.create(client, options)

  def query(client, options \\ []), do: Operations0002.query(client, options)

  def cancel(client, options \\ []), do: Operations0002.cancel(client, options)

  def get(client, options \\ []), do: Operations0002.get(client, options)

  def list_webhooks(client, options \\ []), do: Operations0002.list_webhooks(client, options)

  def create_webhook(client, options \\ []), do: Operations0002.create_webhook(client, options)

  def delete_webhook(client, options \\ []), do: Operations0002.delete_webhook(client, options)

  def update_webhook(client, options \\ []), do: Operations0002.update_webhook(client, options)

  def list_deliveries(client, options \\ []), do: Operations0002.list_deliveries(client, options)
end
