# Generated by Kaji. Do not edit.

defmodule RelevateSdk.ApiError do
  @moduledoc "An HTTP response outside the 2xx range."
  defexception [:status, :body, :headers]

  @type t :: %__MODULE__{status: pos_integer(), body: term(), headers: list()}

  @impl true
  def message(%__MODULE__{status: status}), do: "Kaji API request failed with status #{status}"
end
