# Generated by Kaji. Do not edit.

defmodule RelevateSdk.Application do
  @moduledoc false
  use Application

  @impl true
  def start(_type, _args) do
    Finch.start_link(name: RelevateSdk.Finch)
  end
end
