package app.relevate.sdk.internal;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import java.util.*;
import app.relevate.sdk.*;
import app.relevate.sdk.model.*;

// Generated by Kaji. Do not edit.

/** Bounded generated operation partition. */
public class Operations001 extends Operations000 {
    protected Operations001(ClientConfig config) { super(config); }

    /** Inputs accepted by UpdateWebhook. */
    public record UpdateWebhookRequest(
            String webhookId,
            HookUpdate body
    ) {}

    /** Invokes PATCH /v1/email/webhooks/{webhook_id}. */
    public WebhookResponse updateWebhook(UpdateWebhookRequest input) {
        Objects.requireNonNull(input, "input");
        try {
        var path = "/v1/email/webhooks/{webhook_id}";
        var query = new ArrayList<QueryParameter>();
        var headers = new java.util.LinkedHashMap<String, String>();
        if (input.webhookId() != null) path = path.replace("{webhook_id}", pathValue(input.webhookId()));
        var response = requestWithRetry("PATCH", path, query, headers, input.body());
        return decode(response, WebhookResponse.class);
        } catch (ApiException error) {
            throw mapUpdateWebhookError(error);
        }
    }

    /** Inputs accepted by ListDeliveries. */
    public record ListDeliveriesRequest(
            String webhookId,
            Long limit
    ) {}

    /** Invokes GET /v1/email/webhooks/{webhook_id}/deliveries. */
    public WebhookDeliveryListResponse listDeliveries(ListDeliveriesRequest input) {
        Objects.requireNonNull(input, "input");
        try {
        var path = "/v1/email/webhooks/{webhook_id}/deliveries";
        var query = new ArrayList<QueryParameter>();
        var headers = new java.util.LinkedHashMap<String, String>();
        if (input.webhookId() != null) path = path.replace("{webhook_id}", pathValue(input.webhookId()));
        query.add(new QueryParameter("limit", input.limit()));
        var response = requestWithRetry("GET", path, query, headers, null);
        return decode(response, WebhookDeliveryListResponse.class);
        } catch (ApiException error) {
            throw mapListDeliveriesError(error);
        }
    }

    private RuntimeException mapUpdateWebhookError(ApiException error) {
        return switch (error.statusCode()) {
            case 401 -> new UpdateWebhookStatus401Exception(error, decodeDeclaredError(error.responseBody(), ErrorResponse.class));
            case 404 -> new UpdateWebhookStatus404Exception(error, decodeDeclaredError(error.responseBody(), ErrorResponse.class));
            case 422 -> new UpdateWebhookStatus422Exception(error, decodeDeclaredError(error.responseBody(), ErrorResponse.class));
            case 503 -> new UpdateWebhookStatus503Exception(error, decodeDeclaredError(error.responseBody(), ErrorResponse.class));
            default -> error;
        };
    }

    public static final class UpdateWebhookStatus401Exception extends ApiException {
        private final ErrorResponse body;
        private UpdateWebhookStatus401Exception(ApiException source, ErrorResponse body) { super(source.statusCode(), source.responseBody(), source.retryAfter()); this.body = body; }
        public ErrorResponse body() { return body; }
    }

    public static final class UpdateWebhookStatus404Exception extends ApiException {
        private final ErrorResponse body;
        private UpdateWebhookStatus404Exception(ApiException source, ErrorResponse body) { super(source.statusCode(), source.responseBody(), source.retryAfter()); this.body = body; }
        public ErrorResponse body() { return body; }
    }

    public static final class UpdateWebhookStatus422Exception extends ApiException {
        private final ErrorResponse body;
        private UpdateWebhookStatus422Exception(ApiException source, ErrorResponse body) { super(source.statusCode(), source.responseBody(), source.retryAfter()); this.body = body; }
        public ErrorResponse body() { return body; }
    }

    public static final class UpdateWebhookStatus503Exception extends ApiException {
        private final ErrorResponse body;
        private UpdateWebhookStatus503Exception(ApiException source, ErrorResponse body) { super(source.statusCode(), source.responseBody(), source.retryAfter()); this.body = body; }
        public ErrorResponse body() { return body; }
    }

    private RuntimeException mapListDeliveriesError(ApiException error) {
        return switch (error.statusCode()) {
            case 401 -> new ListDeliveriesStatus401Exception(error, decodeDeclaredError(error.responseBody(), ErrorResponse.class));
            case 422 -> new ListDeliveriesStatus422Exception(error, decodeDeclaredError(error.responseBody(), ErrorResponse.class));
            case 503 -> new ListDeliveriesStatus503Exception(error, decodeDeclaredError(error.responseBody(), ErrorResponse.class));
            default -> error;
        };
    }

    public static final class ListDeliveriesStatus401Exception extends ApiException {
        private final ErrorResponse body;
        private ListDeliveriesStatus401Exception(ApiException source, ErrorResponse body) { super(source.statusCode(), source.responseBody(), source.retryAfter()); this.body = body; }
        public ErrorResponse body() { return body; }
    }

    public static final class ListDeliveriesStatus422Exception extends ApiException {
        private final ErrorResponse body;
        private ListDeliveriesStatus422Exception(ApiException source, ErrorResponse body) { super(source.statusCode(), source.responseBody(), source.retryAfter()); this.body = body; }
        public ErrorResponse body() { return body; }
    }

    public static final class ListDeliveriesStatus503Exception extends ApiException {
        private final ErrorResponse body;
        private ListDeliveriesStatus503Exception(ApiException source, ErrorResponse body) { super(source.statusCode(), source.responseBody(), source.retryAfter()); this.body = body; }
        public ErrorResponse body() { return body; }
    }

    private <T> T decodeDeclaredError(String response, Class<T> type) {
        if (response == null || response.isBlank()) return null;
        try { return mapper.readValue(response, type); } catch (JsonProcessingException ignored) { return null; }
    }

}
