// <auto-generated />
// Generated by Kaji. Do not edit.

namespace Kaji.RelevateSdk;

// Resource facades delegate to KajiClient so configuration stays centralized.

/// <summary>Typed operations for the Inbound resource.</summary>
public sealed partial class InboundResource
{
    private readonly KajiClient _client;

    internal InboundResource(KajiClient client) => _client = client;

    /// <summary>Invokes GET /v1/email/inbound.</summary>
    public Task<InboundListResponse> ListInboundAsync(long? limit = default, CancellationToken cancellationToken = default) => _client.ListInboundAsync(limit, cancellationToken);

    /// <summary>Invokes GET /v1/email/inbound/{message_id}.</summary>
    public Task<InboundResponse> GetInboundAsync(string messageId, CancellationToken cancellationToken = default) => _client.GetInboundAsync(messageId, cancellationToken);

}
